### ISSUE TITLE
Review and update GPL documentation

### ISSUE THREAD

**Issue by vvbandeira** [The-OpenROAD-Project/OpenROAD#1009]
@mgwoo could you take a look and check if the [gpl README](https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/gpl/README.md) and [gpl doc folder](https://github.com/The-OpenROAD-Project/OpenROAD/tree/master/src/gpl/doc) is updated and all files are accessible from the main read me file?

Also, @abk-openroad raised the following questions during a review:
- Is CImg still a noteworthy feature, given the GUI progress in the past year?
- How does this verbosity level comply with the spdlog / messaging standard?  I hope there is not a discrepancy here... I recall 3 levels and ~5 basic message types, plus reporting, for all integrated OpenROAD engines (tools).
- Is `-timing_driven` the new virtual Resizer flow?

**Comment by mgwoo** [comment]
- Is CImg still a noteworthy feature, given the GUI progress in the past year?
  - I think so. 
- How does this verbosity level comply with the spdlog / messaging standard? I hope there is not a discrepancy here... I recall 3 levels and ~5 basic message types, plus reporting, for all integrated OpenROAD engines (tools).
  - will change this as 5
- Is -timing_driven the new virtual Resizer flow?
  - Yes.
