### ISSUE TITLE
Review and update ICeWall documentation

### ISSUE THREAD

**Issue by vvbandeira** [The-OpenROAD-Project/OpenROAD#1012]
@Colin-Holehouse could you help reviewing the Synopsis and Description lists for ICeWall and its Tcl commands so they match and are updated? Some of these questions where raised by @abk-openroad.

On [this file](https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/ICeWall/doc/set_padring_options.md) for the options:
- `-core_area` and `-die_area`, please explain semantics of how the list of 4 numbers specifies a region. Also, these options are not given in the Synopsis above the table.
- If possible, could you add detail and example for the `-offsets` argument?

Edit more notes:

On [set_bump_options](https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/ICeWall/doc/set_bump_options.md) mentions lower left bump. Are origins (lower left vs. upper left) consistent throughout ICeWall commands and mentioned somewhere?  Also, now that the database will allow 45 degree lines, this command will be deprecated once ICeWall has been modified to write RDL into the database directly.

On [set_padring_options](https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/ICeWall/doc/set_padring_options.md) once a power net is defined, it can be used as the -signal argument for the `add_pad` command, is this an overload of "signal"?

**Comment by vijayank88** [comment]
@vvbandeira 
ICeWall got updated. Is this still relevant?
