### ISSUE TITLE
Can't compile in MacOS when GUI is enabled

### ISSUE THREAD

**Issue by eder-matheus** [The-OpenROAD-Project/OpenROAD#1017]
Logfile with the errors attached.
[compile_error.log](https://github.com/The-OpenROAD-Project/OpenROAD/files/7024189/compile_error.log)

This compile error wasn't occurring before Pull Request https://github.com/The-OpenROAD-Project/OpenROAD/pull/1006

**Comment by arlpetergadfort** [comment]
Not sure why it would break with that. Is it possible that the header for unordered_map is missing and that is the issue?
Would you be able to try adding `#include <unordered_map>` to line 41 in mainWindow.h?

I see another issue where the `keyPressEvent` is incorrectly a public, so that should be moved as well.

**Comment by eder-matheus** [comment]
Thanks, @arlpetergadfort. Adding the `#include <unordered_map>` fixed the compile error for me.

**Comment by arlpetergadfort** [comment]
Great, I'll get the PR approved so this is solved.

**Comment by arlpetergadfort** [comment]
@eder-matheus I did not see your comment about the segfault, so I'll reopen. Is that intermittent? or when loading a specific design? Does it happen on load or when you select a path (looks like load but please confirm)?

**Comment by eder-matheus** [comment]
@arlpetergadfort It happens even if I don't load any design. If I run just ´openroad -gui´, it crashes sometimes. I've just tested it, and I had to run ´openroad -gui´ five consecutive times to get the segfault.

**Comment by arlpetergadfort** [comment]
okay, I'll take a look, there is probably a problem in the staGui code, which just wasn't an issue before switching it over to a dockwidget.

**Comment by arlpetergadfort** [comment]
It's possible there an uninitialized variable. 
Can you try to replace the following in staGui.h (line 199)
`  TimingPathDetailModel() {}` ->   TimingPathDetailModel() { path_ = nullptr; }`
Does that help?

**Comment by maliberty** [comment]
@eder-matheus can you valgrind startup on a mac (or maybe even on linux)?

**Comment by eder-matheus** [comment]
@arlpetergadfort This replacement seems to work. I've run `openroad -gui` multiple times and I didn't face any segfault.

@maliberty Sure, I can (and will) run valgrind on centos.

**Comment by arlpetergadfort** [comment]
the `path_` variable is definitely not initialized (based on the code), so that should probably get fixed as well.
Here is the branch with that change: https://github.com/The-OpenROAD-Project-private/OpenROAD/tree/gui-fix-macos-segfault

**Comment by arlpetergadfort** [comment]
> This is flagged in Coverity
> ![image](https://user-images.githubusercontent.com/761514/130517576-e8c43009-6752-4f6e-93b0-cd62510d1ce0.png)
> 
> @arlpetergadfort do you have access to look at the gui issues in Coverity?

@maliberty no I do not, if you want to give me access, I'd be happy to take a look.

@eder-matheus Could you check the branch I listed above and see if that solves it as well (same change, just modified where the initialization happens)?

**Comment by eder-matheus** [comment]
@arlpetergadfort I've tested your branch and it isn't crashing anymore. I've also run Valgrind and it looks good too.

**Comment by arlpetergadfort** [comment]
> @arlpetergadfort I've tested your branch and it isn't crashing anymore. I've also run Valgrind and it looks good too.

Great, in that case I'll merge that in.
