### ISSUE TITLE
PDN creates two power nets.

### ISSUE THREAD

**Issue by shuolai** [The-OpenROAD-Project/OpenROAD#1058]
I was wondering if OpenROAD supports adding two power nets and one ground net as power rings? 
I tried several PDN command but it seems that I can only add a pair of power rings. (VDD and VSS)
Is there any method I can add another power ring VREG at the same time? 

The following image is what I am expecting.
![power_ring_example](https://user-images.githubusercontent.com/79955802/132056693-afdfa4f1-254f-4dde-929e-4ca16fa8e0b3.png)

**Comment by arlpetergadfort** [comment]
@maliberty yes, I think so. With -secondary_net options.  It would be good if the OP could verify it works for them, but there are test cases that address this in pdn

**Comment by vijayank88** [comment]
@shuolai 
Can you check latest pdn option?

**Comment by gadfort** [comment]
@maliberty is this still a thing?
