### ISSUE TITLE
RePlAce diverged at newStepLength

### ISSUE THREAD

**Issue by getziadz** [The-OpenROAD-Project/OpenROAD#1069]
Error during `run_placement`

```
[NesterovSolve] Iter: 2270 overflow: 1.62017 HPWL: 295349210
[NesterovSolve] Iter: 2280 overflow: 1.62017 HPWL: 295349210
[NesterovSolve] Iter: 2290 overflow: 1.62017 HPWL: 295349210
[ERROR GPL-0305] RePlAce diverged at newStepLength.
Error: or_replace.tcl, 93 GPL-0305
```

Design can be found at https://github.com/bsg-idea/bsg_sky130_designs/tree/partial_design_debug/designs/partial_bp_srams

The design is a simple module that contains hardened SRAMs

**Comment by maliberty** [comment]
If you are using openroad-flow-script then please use

make global_place_issue

to package the testcase.  Otherwise please provide a self-contained tcl file to reproduce the file.

**Comment by getziadz** [comment]
The problem went away after using a custom (larger) DIE_AREA configuration.
