### ISSUE TITLE
cpp_tests fails: /usr/ports/cad/openroad/work/OpenROAD-d1c7001/build/src/odb/test/cpp: No such file or directory

### ISSUE THREAD

**Issue by yurivict** [The-OpenROAD-Project/OpenROAD#1071]
rev. d1c7001

OS: FreeBSD 13

**Comment by maliberty** [comment]
You need to provide some actual logs or data.  I doubt this is a platform issue.

**Comment by yurivict** [comment]
Here is the logs directory: https://people.freebsd.org/~yuri/openroad-OpenDB-test-logs.tgz

**Comment by maliberty** [comment]
There is no plan for OR to support FreeBSD.  We welcome patches but can't spend the resources to track down issues.
