### ISSUE TITLE
test failures: check_buffers, simple_test_clustered, simple_test_clustered_max_cap, check_wire_rc_cts, post_cts_opt, balance_levels

### ISSUE THREAD

**Issue by yurivict** [The-OpenROAD-Project/OpenROAD#1078]
Logs: https://people.freebsd.org/~yuri/openroad-cts-results.tgz

rev. d1c7001
OS: FreeBSD 13

**Comment by maliberty** [comment]
There is no plan for OR to support FreeBSD.  We welcome patches but can't spend the resources to track down issues.
