### ISSUE TITLE
test failure: ispd18_sample

### ISSUE THREAD

**Issue by yurivict** [The-OpenROAD-Project/OpenROAD#1080]
Log: https://people.freebsd.org/~yuri/openroad-drt-results.tgz

rev. d1c7001
OS: FreeBSD 13

**Comment by yurivict** [comment]
This testcase is still failing in rev. 5bc179959

**Comment by maliberty** [comment]
I spun up a gcloud machine (freebsd-12-1) and can reproduce the issue.

**Comment by yurivict** [comment]
I just reran tests on FreeBSD 13 yesterday with the current code - there are several other failuers as well.

**Comment by maliberty** [comment]
There is no plan for OR to support FreeBSD.  We welcome patches but can't spend the resources to track down issues.
