### ISSUE TITLE
off grid macro pins

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#1169]
This is an issue extracted from Matt Venn's OpenLane run.  The route.tcl script in the attached testcase is the reproducer.

The problem is a macro with off-grid pins.  In general we advise against this but this case is uncongested and we should be able to handle it.  We end with unresolved DRVs reported.

[bug.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/7297294/bug.tar.gz)

**Comment by Stephanommg** [comment]
I have made a fix and it ends Dr with 0 viols reported by TR. Are the DRVs you mentioned reported by TR or some commercial tool?

**Comment by Stephanommg** [comment]
Yeah, I didnt have to debug. We can proceed with that PR then.

**Comment by dralabeing** [comment]
@maliberty @Stephanommg Looks like this can be closed.
