### ISSUE TITLE
How do we install OpenROAD in RHEL systems?

### ISSUE THREAD

**Issue by thesukantadey** [The-OpenROAD-Project/OpenROAD#1207]
At present, the supported systems are CentOS 7 and Ubuntu 20.04. How do we install OpenROAD in Red Hat Systems? Any leads in this regard will be appreciated.

**Comment by vvbandeira** [comment]
@thesukantadey I would suggest you go through the [`DependencyInstall.sh`](https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/etc/DependencyInstaller.sh) script following the CentOS control-flow and adapt the commands as needed. After installing the dependencies, you should be able to build the app.

Please if you find a recipe that works for RHEL, consider submitting a PR.

**Comment by maliberty** [comment]
No response for a month.
