### ISSUE TITLE
CTS crashes while executing clock_tree_synthesis call

### ISSUE THREAD

**Issue by dineshannayya** [The-OpenROAD-Project/OpenROAD#1221]
OpenRoad version: v2.0-1424-gf864efbae (Latest version)

During the Openlane based CTS script, while executing "clock_tree_synthesis" tool crashes with segmentation fault

Example Test:
[exp2.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/7381915/exp2.tar.gz)

Run command: run_cmd
Run Log:
<pre>[INFO CTS-0084] Compiling LUT.
Min. len    Max. len    Min. cap    Max. cap    Min. slew   Max. slew
2           8           1           36          1           150         
[WARNING CTS-0043] 6336 wires are pure wire and no slew degradation.
TritonCTS forced slew degradation on these wires.
[INFO CTS-0046]     Number of wire segments: 162480.
[INFO CTS-0047]     Number of keys in characterization LUT: 1797.
[INFO CTS-0048]     Actual min input cap: 1.
[INFO CTS-0001] Running TritonCTS with user-specified clock roots: bist_clk.
[INFO CTS-0095] Net &quot;bist_clk&quot; found.
[INFO CTS-0010]  Clock net &quot;bist_clk&quot; has 2 sinks.
[INFO CTS-0008] TritonCTS found 1 clock nets.
[INFO CTS-0097] Characterization used 4 buffer(s) types.
[INFO CTS-0027] Generating H-Tree topology for net bist_clk.
[INFO CTS-0028]  Total number of sinks: 2.
[INFO CTS-0029]  Sinks will be clustered in groups of up to 20 and with maximum cluster diameter of 50.0 um.
[INFO CTS-0030]  Number of static layers: 0.
[INFO CTS-0020]  Wire segment unit: 13000  dbu (13 um).
[INFO CTS-0023]  Original sink region: [(107180, 55445), (108802, 115600)].
[INFO CTS-0024]  Normalized sink region: [(8.24462, 4.265), (8.36938, 8.89231)].
[INFO CTS-0025]     Width:  0.1248.
[INFO CTS-0026]     Height: 4.6273.
[WARNING CTS-0045] Creating fake entries in the LUT.
 Level 1
    Direction: Vertical
    Sinks per sub-region: 1
    Sub-region size: 0.1248 X 2.3137
[INFO CTS-0034]     Segment length (rounded): 1.
    Key: 162664 outSlew: 11 load: 1 length: 1 isBuffered: true
[INFO CTS-0032]  Stop criterion found. Max number of sinks is 15.
[INFO CTS-0035]  Number of sinks covered: 2.
[INFO CTS-0036]  Average source sink dist: 17888.00 dbu.
[INFO CTS-0037]  Number of outlier sinks: 0.
Segmentation fault (core dumped)
</pre>

**Comment by maliberty** [comment]
Your input netlist already has clock buffers:
    - clkbuf_0_bist_clk sky130_fd_sc_hd__clkbuf_16 + PLACED ( 108560 54400 ) N ;
    - clkbuf_1_0_0_bist_clk sky130_fd_sc_hd__clkbuf_1 + PLACED ( 59340 57120 ) FS ;
    - clkbuf_1_1_0_bist_clk sky130_fd_sc_hd__clkbuf_1 + PLACED ( 169740 65280 ) N ;
    - clkbuf_2_0_0_bist_clk sky130_fd_sc_hd__clkbuf_1 + PLACED ( 62560 57120 ) FS ;
    - clkbuf_2_1_0_bist_clk sky130_fd_sc_hd__clkbuf_1 + PLACED ( 46920 65280 ) FN ;
...

Why are you inserting a clock tree again?
