### ISSUE TITLE
GUI can't read well formed lef/lib

### ISSUE THREAD

**Issue by mi-and-core** [The-OpenROAD-Project/OpenROAD#1229]
OR/OS : OpenROAD v2.0-1426-gd8dbd6bc4 / ubuntu 20.4

How to reproduce (in unmodified ORFS) : 
`source setup_env.sh && cd flow && make && make gui_final`

GUI messages in Scripting-Panel :
```
[INFO ODB-0222] Reading LEF file: ./platforms/nangate45/lef/NangateOpenCellLibrary.tech.lef
[WARNING ODB-0219] Error: ERROR (LEFPARS-1): Lef parser has encountered an error in file 
 ./platforms/nangate45/lef/NangateOpenCellLibrary.tech.lef at line 40, on token 0.0050.
 Problem can be syntax error on the lef file or an invalid parameter name.
 Double check the syntax on the lef file with the LEFDEF Reference Manual.
 
[INFO ODB-0222] Reading LEF file: ./platforms/nangate45/lef/NangateOpenCellLibrary.macro.mod.lef
[WARNING ODB-0219] Error: ERROR (LEFPARS-1): Lef parser has encountered an error in file 
 ./platforms/nangate45/lef/NangateOpenCellLibrary.macro.mod.lef at line 9, on token 0.76.
 Problem can be syntax error on the lef file or an invalid parameter name.
 Double check the syntax on the lef file with the LEFDEF Reference Manual.
 
[WARNING STA-0139] ./platforms/nangate45/lib/NangateOpenCellLibrary_typical.lib line 237, 0.0010 is not a float.
[WARNING STA-0139] ./platforms/nangate45/lib/NangateOpenCellLibrary_typical.lib line 237, 0.0020 is not a float.
[WARNING STA-0139] ./platforms/nangate45/lib/NangateOpenCellLibrary_typical.lib line 237, 0.0030 is not a float.
[WARNING STA-0139] ./platforms/nangate45/lib/NangateOpenCellLibrary_typical.lib line 237, 0.0050 is not a float.
```
and more [WARNING STA-0139] when further reading the lib ... until message limit reached and stopped working

Note: 
 ./platforms/nangate45/lef/NangateOpenCellLibrary.tech.lef 
 ./platforms/nangate45/lef/NangateOpenCellLibrary.macro.mod.lef
 ./platforms/nangate45/lib/NangateOpenCellLibrary_typical.lib
looks all well **well formed** ( e.g. read_lef, read_lib does work as expected when called in CL OR ) 

Note:
[WARNING ODB-0219] errorCB() in tools/OpenROAD/src/odb/src/lefin/reader.cpp
[WARNING STA-0139] check_float() in tools/OpenROAD/src/sta/tcl/Util.tcl:359

**Comment by maliberty** [comment]
One other developer (@Stephanommg ) has reported something similar but no other developer could reproduce it.  It is interesting that you are on ubuntu as he is as well.   Are you using virtual box or docker?

**Comment by maliberty** [comment]
@luis201420 now reports this as well.  He will try to debug.
