### ISSUE TITLE
Floorplanning - tracks origin(offset)

### ISSUE THREAD

**Issue by ax3ghazy** [The-OpenROAD-Project/OpenROAD#123]
Hello,

Currently, the floorplanner produces the same set of tracks regardless of the die area definition based on the tracks file. This causes issues with unconventional definitions of the die area (e.g., not starting at ( 0 0 )). (see <a href="https://user-images.githubusercontent.com/19731159/75060932-614fff80-54e8-11ea-8b28-ed941b7d6098.png">this</a>).

Aren't the tracks supposed to follow the die area origin instead of assuming it starts at 0,0? Or were such cases intended to be handled by the tracks file; for example, by manually adding the required shifts there.

Thanks.

**Comment by jjcherry56** [comment]
fixed by 7d06a44 init_fp offset tracks by die origin
