### ISSUE TITLE
opendp overlapping cells

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenROAD#126]
Hello,
Opendp places cells over tapcells in the middle of the floorplan. It seems that providing the same input parameters (def and lef) to opendp that a legacy version of opendp doesn't produce the same wrong behavior (specifically this version https://github.com/sanggido/OpenDP).
Thank you

**Comment by jjcherry56** [comment]
no test case, no response

**Comment by kareefardi** [comment]
@jjcherry56 Sorry should have mentioned this. Would you please check with @tspyrou for a private repo for the test case

**Comment by jjcherry56** [comment]
roger.  happy to look at it if there is a test case

**Comment by jjcherry56** [comment]
I have the testcase now. Can you point me to a specific instance that is problematic? I don't have any graphics to make it obvious.

**Comment by kareefardi** [comment]
Hello, these are the cells that are reported overlapping from opendp. Is that what you are asking for? I can provide screenshots if needed
```
overlap_check ==> FAIL ( cell PHY_72 overlaps _757_ )  ( 83860, 20360 )
overlap_check ==> FAIL ( cell PHY_73 overlaps _582_ )  ( 43840, 23760 )
overlap_check ==> FAIL ( cell PHY_76 overlaps _576_ )  ( 83860, 33960 )
overlap_check ==> FAIL ( cell PHY_83 overlaps _490_ )  ( 43840, 57760 )
overlap_check ==> FAIL ( cell PHY_92 overlaps _457_ )  ( 83860, 88360 )
overlap_check ==> FAIL ( cell PHY_93 overlaps _733_ )  ( 43840, 91760 )
overlap_check ==> FAIL ( cell PHY_95 overlaps _476_ )  ( 43840, 98560 )
overlap_check ==> FAIL ( cell PHY_96 overlaps _467_ )  ( 83860, 101960 )
```

**Comment by jjcherry56** [comment]
That's exactly what I'm looking for.

**Comment by jjcherry56** [comment]
How did you get that report?
When I run the stand alone opendp it aborts because there are no
power/ground nets defined.
I can only get that result if I remove the exit and recompile.

**Comment by jjcherry56** [comment]
fixed by f510c1a opendp issue 126

**Comment by kareefardi** [comment]
@jjcherry56 Thanks for the effort. I tried it and they don't overlap now. However, The gap between the tap cell and the neighboring cells doesn't seem to respect the min cell/site width (0.46 in this case). I attached a screenshot describing that. Same test case as before. This specific cell is "PHY_92" among others like PYH_89 and PHY_68. If you would like, I can open another issue.
![Screenshot from 2020-02-25 18-23-32](https://user-images.githubusercontent.com/12303699/75267079-f2cab480-57fb-11ea-843b-e6c85df00334.png)

**Comment by jjcherry56** [comment]
Excuse our ignorance, but where is the gap specified? I think I know how to
address it, but I can't if I don't know what the rules are. I'm asking on
this end also

**Comment by kareefardi** [comment]
If by gap you are referring to the 0.46, then that's the site width defined in the lef.

But on further inspection of the test case, I noticed that tapcells are misaligned. For instance, in this row:
```
ROW ROW_0 <site> 3360 3360 FS DO 248 BY 1 STEP 460 0 ;
``` 
There is this tapcell:
```
PHY_66 <tap cell> + FIXED ( 43700 3360 ) FS ;
```
Since 43700-3360 is not a multiple of 460 (the site width), I think this misalignment will cause issues with having weird gaps between cells, which I do not believe is opendp's fault.

I do wonder however if the above case should be flagged by opendp in one of it's checks.

**Comment by jjcherry56** [comment]
To my knowledge there is no requirement for fixed placed cells to be
aligned with the rows.

However, the fact that the tapcells are not on the grid is a problem, but
not an opendp issue.
Apparently tapcell is supposed to respect the rows when placing the tap
cells and is not.
I suggest you file a different issue against tapcell with a testcase
showing exactly how you added them.

**Comment by kareefardi** [comment]
Alright, thanks a lot for your help.

**Comment by eder-matheus** [comment]
Hi, @kareefardi. You can find an example script for tapcell here: https://github.com/The-OpenROAD-Project/OpenROAD/blob/openroad/src/tapcell/etc/scripts/example_45nm.tcl.

This should be enough to have a properly tapcell insertion.
