### ISSUE TITLE
Resizer buffers tri-stated nets

### ISSUE THREAD

**Issue by Manarabdelaty** [The-OpenROAD-Project/OpenROAD#1290]
Resizer inserts buffers on nets that are driven by a tri-state cell. I am attaching a test case for which resizer inserts a buffer on an output port (`mgmt_gpio_in`) which is driven by a tri-state cell.

[rsz_test_case.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/7512431/rsz_test_case.zip)

**Comment by jjcherry56** [comment]
fixed
