### ISSUE TITLE
OpenDP bug in set_placement_padding 

### ISSUE THREAD

**Issue by sewkim** [The-OpenROAD-Project/OpenROAD#138]
Hi James, 

The set_placement_padding command with '-global -left 30' generated the seg fault. 
Could you check the attached testcase?

[bug01.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/4303839/bug01.tar.gz)

I have used the following commit in OpenROAD repo:
https://github.com/The-OpenROAD-Project/OpenROAD/commit/4187ce74b7f7dccb126f9870383511eca24132b5

Kinds,
Seungwon Kim

**Comment by jjcherry56** [comment]
fixed in 94b3848 opendp issue 138

**Comment by jjcherry56** [comment]
In the future, please to not copy files from the test directory and rename them. I reuse files in the test directory and do not want to have multiple copies of the same data. I shouldn't have to guess and diff to find your def is the same as one that was already there.

**Comment by sewkim** [comment]
I see, I'll be more careful in future. Thank you for your response.
