### ISSUE TITLE
openroad -gui doesn't work

### ISSUE THREAD

**Issue by parkjw97** [The-OpenROAD-Project/OpenROAD#1478]
After cmake .. and make I run openroad -gui. But nothing opened. Only the phrase below appeared and was not implemented.

```
~/OpenROAD$ openroad -gui
openroad: command not found

```

**Comment by maliberty** [comment]
This has nothing to do with the gui - it can't find the executable at all.  I suspect you don't have it in your path.

**Comment by QuantamHD** [comment]
By default cmake doesn't install the binary, it just builds it. I suspect that if you run the following command it will work `./build/src/openroad -gui`
