### ISSUE TITLE
tapcell overlap with endcap

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenROAD#151]
Hello,

Using tapcell tool to insert tapcells and decaps cells, depending on the input distance and the design size, can lead to overlapping tapcells with the right decap column. Please check with @tspyrou for a private repo for a test case. 

Thanks

**Comment by tspyrou** [comment]
Eder, thanks for looking into this. I am talking to Kareem now and he was happy to see you assigned it to yourself.

**Comment by eder-matheus** [comment]
Hi, @kareefardi.

I've updated tapcell at this [branch](https://github.com/The-OpenROAD-Project/OpenROAD/tree/fix/tapcell_overlap). It should not create overlaps anymore when using the script for 45nm.
The change for 14nm will come up soon.

Thanks.

**Comment by tspyrou** [comment]
This branch has been integrated and this issue should be resolved now.
