### ISSUE TITLE
OpenROAD GUI: is it possible to generate by script a jpeg or png from a selection?

### ISSUE THREAD

**Issue by iruhm** [The-OpenROAD-Project/OpenROAD#1528]
I have this small TCL script and I would like to directly script the jpeg or png generation to get the figure with the highlighted nets
 
for {set i 0} {$i < 10} {incr i} {
    select -type Net -name clknet_$i* -highlight $i
}

**Comment by maliberty** [comment]
See https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/scripts/save_images.tcl for examples

**Comment by vijayank88** [comment]
@iruhm 
Please refer latest OpenROAD gui features. Still you need any help on this?

**Comment by titan73** [comment]
I've tested saving an image with highlighted nets using the code example:
```
set nets {cd d cp q}
for {set i 0} {$i < [llength $nets]} {incr i} {
    select -type Net -name [lindex $nets $i] -highlight $i
}

set height [ord::dbu_to_microns [[[ord::get_db_block] getBBox] getDY]]
set resolution [expr $height / 1000]
save_image -resolution $resolution design.png
```

I got a image nets highlighted:

![design](https://github.com/user-attachments/assets/e1f0f9fa-fc43-4ff2-894d-30df0ae3cf9b)

I think we can close this issue.
