### ISSUE TITLE
tritonMacroplace liberty /.lib dependance

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenROAD#154]
Hello,

It seems that tritonMacroplace depends on defining all the design cells and macros in a .lib and needs to be read using `read_liberty`. Otherwise, it crashes after outputting `Generating Sequantial Graph...`. To replicate this, simply omit one of the read lib in tritonMacroplace test cases. 

Thanks

**Comment by tspyrou** [comment]
Let's start with a good error message versus a crash.

**Comment by rovinski** [comment]
As I understand it, this issue should be resolved by #336
