### ISSUE TITLE
Integrate Google's AI Macro Placer: Now Open Source 

### ISSUE THREAD

**Issue by QuantamHD** [The-OpenROAD-Project/OpenROAD#1563]
We should integrate Google's AI Macro Placer into OpenROAD. https://github.com/google-research/circuit_training

**Comment by maliberty** [comment]
I suggest starting with a loose integration into either ORFS or OL.  @QuantamHD is this something you want to tackle?

**Comment by QuantamHD** [comment]
Do we have any macro heavy designs?

**Comment by maliberty** [comment]
bp_* and swerv* have the most of the public test cases.

**Comment by manili** [comment]
Hi,
@maliberty and @QuantamHD:
Any progresses after almost a year?

**Comment by maliberty** [comment]
No, we have been working on RTL-MP as our macro placement solution (in src/mpl2).  You are welcome to pick up the loose coupling if you are interested.
