### ISSUE TITLE
drt: routing finishes with 0 violations, but creates a short on met1

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenROAD#1577]
While chasing an LVS issue in a design, it looks like detailed routing created a short on met1 without reporting it as a violation:

```
    Completing 100% with 0 violations.
    elapsed time = 00:00:00, memory = 25517.50 (MB).
[INFO DRT-0199]   Number of violations = 0.
```

But there is a short between nets `net718` and `_017753_` on `met1`. This is a screenshot of just met1:

![drt-short](https://user-images.githubusercontent.com/2029971/150668775-ed10b56b-6e38-442a-a249-8b6b6ff958b8.png)

Coordinates: `1448.994`, `167.121`

**Comment by antonblanchard** [comment]
Testcase: [drt-drc-bug.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/7920019/drt-drc-bug.tar.gz)

**Comment by osamahammad21** [comment]
Working on it

**Comment by antonblanchard** [comment]
Thanks @osamahammad21! Any clues here?

**Comment by maliberty** [comment]
There is a lot of discussion going on.  The basic issue is that the short falls right on the boundary between two workers and there is some conflict over ownership of the shapes and markers.  It is getting attention.

**Comment by antonblanchard** [comment]
Thanks @maliberty, that gives me a possible workaround (running with `ROUTING_CORES=1`)

**Comment by maliberty** [comment]
Its not such the number of threads as it is the boundary condition.  I don't think it will help but you can try.

**Comment by QuantamHD** [comment]
Do we need to run convolutions over the routing grid,  or is there a more efficient solution here?

**Comment by maliberty** [comment]
There's just a bug that needs fixing

**Comment by osamahammad21** [comment]
Changing the number of threads won't change a thing. I have a local change that solves this violation. But the real problem I see here is that 0 violations doesn't actually mean 0 violations. This is because of the nature of GC being run on separate workers not on the whole design, so it's affected by what the drWorker initializes it with.

**Comment by osamahammad21** [comment]
@antonblanchard The pr is merged into master, so the issue is fixed now.
