### ISSUE TITLE
opensta get_cells -filter not filtering when called alongside -of_objects

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenROAD#1582]
As the title says,
```
get_cells -filter ref_name==<cell_ref>
```
while this doesn't.
```
get_cells -filter ref_name==<cell_ref> -of_objects <net>
```
A quick look at the source code and seems like the -filter handler may not be properly scoped (unless that is intentional, then it should reflect in the documentation)

Thanks.

**Comment by tspyrou** [comment]
This is a bug, the filter should be respected.

**Comment by jjcherry56** [comment]
fixed
