### ISSUE TITLE
Floorplan with constraint on number of pins

### ISSUE THREAD

**Issue by miniskar** [The-OpenROAD-Project/OpenROAD#1584]
I am getting a below error while synthesizing the opensource RISCV  using OpenRoad tools during the floorplan. I have used freepdk45 for my work. Can someone guide me how to resolve this error ?

OpenROAD 1 v2.0-880-gd1c7001ad
Error: sc_floorplan.tcl, 101 PPL-0024
floorplan/0/floorplan.log:[ERROR PPL-0024] Number of pins 1521 exceeds max possible 1247.

**Comment by maliberty** [comment]
You have more pins than can fit around the perimeter of your design.  You need either fewer pins, less space between pins, or a larger die area.
