### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ashkanr65** [The-OpenROAD-Project/OpenROAD#1618]
Hi,
I am trying to install OpenRoad. However after the command "cmake .." I get this error.
Does anybody have any idea how can I solve this issue?
![image](https://user-images.githubusercontent.com/35424938/152508950-ee507e3a-0890-4d3d-8f5b-913513922e31.png)

**Comment by maliberty** [comment]
Have you installed the dependencies with ./etc/DependencyInstaller.sh per https://openroad.readthedocs.io/en/latest/main/README.html

It looks like you are missing spdlog

**Comment by ashkanr65** [comment]
> Have you installed the dependencies with ./etc/DependencyInstaller.sh per https://openroad.readthedocs.io/en/latest/main/README.html
> 
> It looks like you are missing spdlog

I installed the dependencies and but I get the same error. I have even installed spdlog separately and I received the same error.

**Comment by vijayank88** [comment]
@ashkanr65 
Have you installed both -run and -dev?
      ./etc/DependencyInstaller.sh -run      # installs dependencies to run a pre-compiled binary
       ./etc/DependencyInstaller.sh -dev   # installs dependencies to compile the openroad binary

Try to clone again in new directory and install it

**Comment by maliberty** [comment]
Stale
