### ISSUE TITLE
Add check for off-grid dbBPin shapes

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#1634]
In https://github.com/The-OpenROAD-Project/OpenLane/issues/912 the root cause was an off-grid IO pin that lead to a pin access failure (all APs fail with off-grid errors).  

We should have a pre-check at the start of routing that runs gc on each of the dbPin to give a clearer warning about such a problem.

**Comment by rovinski** [comment]
On a related note, maybe it's a good idea to force `place_pin` to snap to the manufacturing grid.

**Comment by vijayank88** [comment]
@maliberty 
I recently came across similar PR related to off-grid check. It's resolved right?

**Comment by maliberty** [comment]
@osamahammad21 is this covered by your recent change?

**Comment by osamahammad21** [comment]
No, my previous PR checks on cells only.

**Comment by refaay** [comment]
Issue solved in PR #3961.
