### ISSUE TITLE
global routing failing

### ISSUE THREAD

**Issue by DarylK78** [The-OpenROAD-Project/OpenROAD#1646]
Running a design with 60K placeable gates, seeing routing congestion issues and not sure how to debug.

I am unable to attach my operoad.zip as it say "is not included in the list"

**Comment by maliberty** [comment]
Perhaps it dislikes the extension or you have the issue in https://github.com/github/hub/issues/1479

Try changing it to .zip1 and see if it works.

**Comment by DarylK78** [comment]
Actually seems to be an issue with the filesize, is there a max on how large files to upload can be in the comments?

**Comment by maliberty** [comment]
Probably but idk.  You can always put the file in some cloud storage and provide a link (eg google drive, dropbucket).

**Comment by vijayank88** [comment]
@DarylK78 
Yes there is file size limitation to attach here. If you're facing issue, upload file in your personal repo and share link here.

**Comment by DarylK78** [comment]
I was able to get the archive to a manageable size, this was run with the PL_TARGET_DENSITY at 0.25 and the FP_CORE_UTIL at 25.  Still seeing too much congestion

[openroad.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/8106460/openroad.zip)

**Comment by vijayank88** [comment]
@DarylK78 
Core has enough free space. But still I'm seeing high congestion near macro and std cell area as well.
```
set ::env(PL_MACRO_CHANNEL) "10 10"
set ::env(PL_MACRO_HALO) "10 10"
```
Can you try this setting in your OpenLane config.tcl and re-run the flow.

Possible try to place macros manullay based functionality.

**Comment by eder-matheus** [comment]
I see this in the congestion map:
<img width="669" alt="image" src="https://user-images.githubusercontent.com/43450810/156426850-6f680650-c9c4-49bd-b764-ef9e502f4a36.png">
Perhaps the placement density is too large? The global router ends with high congestion even when I don't use the resources adjustments.

**Comment by mousaq92** [comment]
How do you get these heat maps in the GUI?

**Comment by eder-matheus** [comment]
> How do you get these heat maps in the GUI?

In the `Display Control`, go to `Heat Maps` and select what heat map you want to visualize. In the figure below, I'm showing only the routing congestion heat map:
<img width="304" alt="Screen Shot 2022-03-02 at 21 46 36" src="https://user-images.githubusercontent.com/43450810/156474560-d02fd897-945f-43c6-9e7b-2c09e38316aa.png">

**Comment by mousaq92** [comment]
Thanks.

**Comment by Sya0** [comment]
> I see this in the congestion map: <img alt="image" width="669" src="https://user-images.githubusercontent.com/43450810/156426850-6f680650-c9c4-49bd-b764-ef9e502f4a36.png"> Perhaps the placement density is too large? The global router ends with high congestion even when I don't use the resources adjustments.

@mousaq92, @eder-matheus 
Sorry to interrupt but is this klayout?

**Comment by vijayank88** [comment]
@Sya0 its OpenROAD GUI
Command to use: `openroad -gui`

**Comment by DarylK78** [comment]
I took the advice to a add macro channels, and now it is able to global route but runs into issues with diodes

See latest run here:

[openroad.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/8179731/openroad.zip)
.

**Comment by luis201420** [comment]
@DarylK78 Could you upload the tarball containing the stage before the global placement?

**Comment by DarylK78** [comment]
This one is the tarball of the placement step I believe

[openroad.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/8217858/openroad.zip)

**Comment by DarylK78** [comment]
This one runs the init_floorplan

[floorplan.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/8217977/floorplan.zip)

**Comment by eder-matheus** [comment]
Thanks very much, @DarylK78!

**Comment by ravi-varadarajan** [comment]
I examined the congested areas and it is due the dense concentration of combinational cells (4 input nor or ao22/oa22) in the congested area. You should be able to resolve this by using non zero  global and detailed placement padding. We will also examine the init_floorplan tarball -- thanks

**Comment by eder-matheus** [comment]
> I took the advice to a add macro channels, and now it is able to global route but runs into issues with diodes
> 
> See latest run here:
> 
> [openroad.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/8179731/openroad.zip) .

The latest version of OpenROAD have a fix for the diodes issue. Can you try that?

**Comment by DarylK78** [comment]
I was able to get it to route by using DIODE_STRATEGY 4 and turning off fill.  

I'm also seeing a lot of slew violations which might be affecting the diode issue (nets are too long).  I will go back to placement and try some additional things, and also attempt to use the latest version of openroad as well.

**Comment by vijayank88** [comment]
Closing as resolved based on user comment.
