### ISSUE TITLE
[ord::get_db_block] findNet   for a bus signal

### ISSUE THREAD

**Issue by iruhm** [The-OpenROAD-Project/OpenROAD#1653]
I would like to find a bus signal net with findNet:

`[ord::get_db_block] findNet us00.a\[6\]`
NULL
`[ord::get_db_block] findNet us00.a[6]`
NULL

The get_nets command is working with this command

`get_nets us00.a\[6\]`
_906fffb8b5550000_p_Net

What is the correct command to get the odb__dbNet for the bus signal?
I used the sky130hd/aes design for testing.

**Comment by maliberty** [comment]
>>> [ord::get_db_block] findNet {us00.a\[6\]}
_f021110a00000000_p_odb__dbNet
>>> [ord::get_db_block] findNet "us00.a\\\[6\\\]"
_f021110a00000000_p_odb__dbNet
