### ISSUE TITLE
Routing congestion too high error

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenROAD#1655]
I'm using OpenLane Tag: [2022.02.21_02.33.47](https://github.com/The-OpenROAD-Project/OpenLane/releases/tag/2022.02.21_02.33.47)
wb_interconnect is mpw-3 shuttle precheck passed design.

If I use same design in current OR App, failed at global routing. Log as follows:
```
[INFO GRT-0053] Routing resources analysis:
          Routing      Original      Derated      Resource
Layer     Direction    Resources     Resources    Reduction (%)
---------------------------------------------------------------
li1        Vertical            0             0          0.00%
met1       Horizontal     178080         70200          60.58%
met2       Vertical       133560         94466          29.27%
met3       Horizontal      89040         60345          32.23%
met4       Vertical        53424         33949          36.45%
met5       Horizontal      17808          7749          56.49%
---------------------------------------------------------------

[INFO GRT-0101] Running extra iterations to remove overflow.
[INFO GRT-0103] Extra Run for hard benchmark.
[INFO GRT-0197] Via related to pin nodes: 13726
[INFO GRT-0198] Via related Steiner nodes: 669
[INFO GRT-0199] Via filling finished.
[INFO GRT-0111] Final number of vias: 31730
[INFO GRT-0112] Final usage 3D: 205552
[ERROR GRT-0118] Routing congestion too high.
Error: groute.tcl, 69 GRT-0118
[ERROR]: during executing openroad script /openlane/scripts/openroad/groute.tcl
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
child process exited abnormally

```
Issue reproducible tar file attached here. 
[openroad_issue_reproducible.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/8106828/openroad_issue_reproducible.zip)

Expectation: Tool should complete routing stage

**Comment by eder-matheus** [comment]
@vijayank88 Similar to https://github.com/The-OpenROAD-Project/OpenROAD/issues/1620, I was able to complete the global routing with no errors by reducing the global adjustment (`GLB_RT_ADJUSTMENT`) from `0.3` to `0.1`. What is the placement density of this design?

**Comment by mousaq92** [comment]
Hello,

(GLB_RT_ADJUSTMENT) "0.1" does pass global routing. However, all I see are filler cells in the design. Please correct me if I am mistaken.

![image](https://user-images.githubusercontent.com/98984518/156473627-a1821f45-ecbc-4dbc-9df1-ac260d062567.png)

**Comment by eder-matheus** [comment]
@mousaq92 In the `Display Control`, look at `Instances` and check what is selected to be shown. You probably have to add the "StdCells" option. Check the figure below:
<img width="268" alt="Screen Shot 2022-03-02 at 21 44 08" src="https://user-images.githubusercontent.com/43450810/156474267-74cc21c6-7a4e-4293-9f01-f55e64c42303.png">

**Comment by mousaq92** [comment]
Got it thanks.

**Comment by vijayank88** [comment]
@eder-matheus 
By reducing the global adjustment (GLB_RT_ADJUSTMENT) from 0.3 to 0.1 resolved congestion issue.
