### ISSUE TITLE
tapcell site misalign

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenROAD#178]
Hello,

In some cases (which I don't what are the reasons behind them), tapcells are inserted in a location that is not aligned with sites. Please check with @tspyrou for a private repo with a test case.

Thanks,
kareem farid

**Comment by eder-matheus** [comment]
Fix for the issue at this [branch](https://github.com/The-OpenROAD-Project/OpenROAD/tree/fix/tapcell).

After Jenkins runs all tests, a pull request will be open to the openroad branch

**Comment by kareefardi** [comment]
Thanks, tested and fixed now
