### ISSUE TITLE
Build error with tclreadline patch

### ISSUE THREAD

**Issue by arlpetergadfort** [The-OpenROAD-Project/OpenROAD#180]
Thanks for including the readline.
When I pulled and compiled the new commit (1635259) I get a compile error: 'std::array' is not a member of 'std'. To correct this Main.cc needed to have #include<array> included along with the tclreadline.h.
This was on a Ubuntu 20.04 install.

**Comment by maliberty** [comment]
Thanks for the report.  I've added "#include <array>" to Main.cc.
