### ISSUE TITLE
openroad build completed on Ubuntu; however, I get openroadd commanddd not found.

### ISSUE THREAD

**Issue by alaasal** [The-OpenROAD-Project/OpenROAD#181]
I tried to bulid openrod on ubuntu 18 the build completes successfully but when I run the command open road I get the error command openroad not found. 
![image](https://user-images.githubusercontent.com/38817722/78148426-24efb780-7435-11ea-9b7d-d7668abaa981.png)

**Comment by maliberty** [comment]
I expect you don't have it in your path.  See if /home/user/OpenROAD-flow/tools/OpenROAD/build/src/openroad works.

**Comment by rovinski** [comment]
Hi @alaasal,

It looks like you are using OpenROAD-flow. There is a script `setup_env.sh` which will set up your environment.

**Comment by alaasal** [comment]
Thanks all, I didn't have the command in my path; however, sourcing setup_env.sh didn't solve that and I had to add openroad and tritonroute to my path myself.

**Comment by rovinski** [comment]
Sourcing `setup_env.sh` should work unless you didn't use the `build_openroad.sh` script to build. If so, please file an issue against [OpenROAD-flow](https://github.com/The-OpenROAD-Project/OpenROAD-flow).
