### ISSUE TITLE
How to update OpenROAD on ubuntu 20.04.4

### ISSUE THREAD

**Issue by jarvis-lorry** [The-OpenROAD-Project/OpenROAD#1816]
I have version v2.0-880-gd1c7001ad of OpenROAD installed.  How do I install the latest version?  I can't clone the github on top of my existing version.

**Comment by vijayank88** [comment]
@jarvis-lorry 
Follow below steps from OpenROAD directory:
```
git checkout master
git pull
git submodule init
git submodule update
git submodule sync
git clean -xdi
./etc/Build.sh
```

**Comment by jarvis-lorry** [comment]
Thank you, @vijayank88 
I've been able to install the update of OpenROAD.  Now I have to install the latest version of klayout.

**Comment by vijayank88** [comment]
@jarvis-lorry 
As update on OpenROAD got fixed, closing this issue
