### ISSUE TITLE
dpl: standard cells flipped

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenROAD#1840]
I tried taping out Microwatt/Caravel using Openlane with a recent OpenROAD and https://github.com/The-OpenROAD-Project/OpenLane/pull/1059 applied. I'm seeing a strange problem where all standard cells appear to be flipped, such that they are powered backwards.

Test case is at:  [reverse-dpl.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/8643804/reverse-dpl.tar.gz)

**Comment by antonblanchard** [comment]
I started looking through dpl, and noticed a few things:

- `Opendp::checkPowerLine` doesn't appear to check any height=1 cells at all
- We go to a lot of trouble to work out where the power and ground rails are (eg `Opendp::findRowPower`). Do we need to do that or just look at the orientation out of odb?

**Comment by antonblanchard** [comment]
I'm not sure if it matters but there are an odd number of met1 rails in this design

**Comment by maliberty** [comment]
findRowPower is just wrong as it is going to look at the ring not the first row in your test case.  Probably it worked before by luck depending on which ring is first.

**Comment by maliberty** [comment]
> findRowPower is just wrong as it is going to look at the ring not the first row in your test case. Probably it worked before by luck depending on which ring is first.

Its more than just that.  I agree orientation should be enough.

**Comment by antonblanchard** [comment]
Thanks @maliberty, I can confirm it fixed the original issue.
