### ISSUE TITLE
Hierarchical Support Needed 

### ISSUE THREAD

**Issue by QuantamHD** [The-OpenROAD-Project/OpenROAD#1910]
Hi @maliberty,

We have another internal user of OpenROAD, and they're trying to run more analysis with OpenSTA and OpenROAD. They would like to preserve the hierarchy information. @saywhite can add more details. 

What would be the fastest path to getting OpenDB to preserve this hierarchy information?

**Comment by maliberty** [comment]
standalone opensta can keep the full hierarchical netlist for timing.

**Comment by QuantamHD** [comment]
@saywhite added some custom functions to standalone STA, but noticed they stopped working once linked into OpenROAD. Namely, to list out all the hierarchical modules. The previous statement could be incorrect. @saywhite can you add more details?

**Comment by maliberty** [comment]
odb has physical information but is a flat db
standalone sta is a fully hierarchical model but has no physical information

Ideally we want both physical information and full hierarchy but we don't have that and its a lot of work.  We settled on have odb have an instance tree for now.  Full hierarchy affects more than the db but since sta is an analysis tool it doesn't have to deal with netlist edits.

**Comment by saywhite** [comment]
During dbSTA link_design:
```
void
dbLinkDesign(const char *top_cell_name,
	     dbVerilogNetwork *verilog_network,
	     dbDatabase *db,
             Logger *logger)
{
  bool link_make_black_boxes = true;
  bool success = verilog_network->linkNetwork(top_cell_name,
					      link_make_black_boxes,
					      verilog_network->report());
  if (success) {
    Verilog2db v2db(verilog_network, db, logger);
    v2db.makeBlock();
    v2db.makeDbNetlist();
    deleteVerilogReader();
  }
}
```
the verilog_network is the network object created here, which calls openSTA's concreteNetwork function;
In makeDbModule, the network_ seems to be aware of hierarchical instances (I also verified through testcases). 

```
// Recursively builds odb's dbModule/dbModInst hierarchy corresponding
// to the sta network rooted at inst.  parent is the dbModule to build
// the hierarchy under. If null the top module is used.

void
Verilog2db::makeDbModule(Instance* inst, dbModule* parent)
{
  Cell* cell = network_->cell(inst);
...
  InstanceChildIterator* child_iter = network_->childIterator(inst);
  while (child_iter->hasNext()) {
    Instance* child = child_iter->next();
    if (network_->isHierarchical(child)) {
            makeDbModule(child, module);
    } else {
...
}
```

So I have three questions:

1) which part flattens the design?
2) is concreteNetwork a flattened or hierarchical network?
3) what happens to openSTA's built-in network?

**Comment by maliberty** [comment]
Your answer is already in the code you posted: Verilog2db.  It builds a flat odb from the dbVerilogNetwork built during sta's read_verilog.   dbNetwork is an adaptor to the flat odb that sta then uses.

I already said that openSTA built-in network is not used in OR.  It has no physical information and is not suitable.

**Comment by QuantamHD** [comment]
Can we keep the hierarchical information as metadata rather than making it structural? So instances and nets could keep track of what module they are in and who their parents are without impacting the current API?

For networking modifications we could just make a simple rule that fan in controls your "hierarchy label" with some conflict resolution algorithm based on alphabetical order, or something like that.

**Comment by maliberty** [comment]
Flat nets in odb are not in a single module but represent a whole collection of hierarchical nets that span modules.   Instances already do keep track.

The solution to this problem is known and substituting something hackier isn't desirable.  If you want to work on this problem I'm glad to offer guidance.

**Comment by maliberty** [comment]
It would be more helpful to know what you are trying to accomplish

**Comment by saywhite** [comment]
Thanks Matt for clarification. I think verilog2db should already satisfy my need for hierarchical instance tracing purpose in this case. I was just curious about the role of STA's built-in network since the behavior is different when invoking the openSTA standalone. We can close this ticket now.
