### ISSUE TITLE
qt5-default package from DependencyInstaller.sh is deprecated

### ISSUE THREAD

**Issue by luccareinehr** [The-OpenROAD-Project/OpenROAD#1922]
Hi,

Newer versions of Debian do not have the qt5-default package in their repositories anymore (see [this forum post](https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04)). Thus, running the Dependency Installer script gives a "package is not available" error.

I'm using Ubuntu 22.04

**Comment by maliberty** [comment]
@vvbandeira any progress on this?

**Comment by wjrforcyber** [comment]
Any progress? Is this necessary for the future build?

**Comment by maliberty** [comment]
@vvbandeira please resolve this as its been pending a long time.
