### ISSUE TITLE
After run the flow successfully, the DRC is not clean

### ISSUE THREAD

**Issue by Elon-J** [The-OpenROAD-Project/OpenROAD#1933]
When I try to increase the output load ability of my block, after passing the OpenRoad flow successfully, the DRC is not clean. What should I adjust?
Attach my detail_route_issue_file:

[detail_route_NON_CLK_GEN_sky130hd_base_2022-06-04_07-30.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/8837249/detail_route_NON_CLK_GEN_sky130hd_base_2022-06-04_07-30.tar.gz)

Attach my block repository:
https://github.com/Elon-J/OpenROAD-flow-scripts/tree/master/flow/designs/sky130hd/NON_CLK_GEN
Attach my report file, magic DRC report and layout DRC report:

[6_report.log](https://github.com/The-OpenROAD-Project/OpenROAD/files/8837223/6_report.log)

[sky130_drc.txt](https://github.com/The-OpenROAD-Project/OpenROAD/files/8837220/sky130_drc.txt)

[6_final_drc.txt](https://github.com/The-OpenROAD-Project/OpenROAD/files/8837222/6_final_drc.txt)

**Comment by Elon-J** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/88715865/171989190-1551505f-5146-4763-8252-ce3b018dbfe9.png">

**Comment by Elon-J** [comment]
I also have try many verisons including adjust different core areas.

**Comment by vijayank88** [comment]
@Elon-J 
Please execute following commands from `flow` directory and attach zip file.
```
make detail_route_issue
```

**Comment by Elon-J** [comment]
OK

**Comment by Elon-J** [comment]
I have updated my first comment.

**Comment by vijayank88** [comment]
@Elon-J 
Detail routing completed with 0 DRC errors.
```
[INFO DRT-0195] Start 57th optimization iteration.
    Completing 10% with 0 violations.
    elapsed time = 00:00:00, memory = 149.02 (MB).
    Completing 20% with 0 violations.
    elapsed time = 00:00:00, memory = 149.02 (MB).
    Completing 30% with 0 violations.
    elapsed time = 00:00:00, memory = 149.03 (MB).
    Completing 40% with 0 violations.
    elapsed time = 00:00:00, memory = 149.03 (MB).
[INFO DRT-0199]   Number of violations = 0.
```
Its something error coming from KLayout.

Please try to load and check those overlapping error.

**Comment by Elon-J** [comment]
@vijayank88 , Thank you very much! Let me check it!

**Comment by Elon-J** [comment]
@vijayank88 , By the way, actually I also check it using magic, there are also some DRC errors.

**Comment by msaligane** [comment]
@Elon-J can you add the drc report and maybe zoomed in screenshots. That would be helpful to understand what is wrong.

**Comment by vijayank88** [comment]
@msaligane please check this slack channel conversation: https://skywater-pdk.slack.com/archives/C0161A4A59V/p1654326142362839

**Comment by msaligane** [comment]
@vijayank88 thanks! 
@Elon-J what is your fix for the buf_16?

**Comment by Elon-J** [comment]
@msaligane , I just try to increase the drive ability to generate a new CLK, and this problem has been fixed.

**Comment by maliberty** [comment]
Is this resolved?
