### ISSUE TITLE
DRT: met3 min area violation

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenROAD#1940]
I'm seeing a single met3 minimum area violation when taping out Microwatt using a recent OpenROAD (commit 0b8b7ae255f8fbbbefa57d443949b84e73eed757).

The issue is at 1147.305, 965.775

![magic-drc](https://user-images.githubusercontent.com/2029971/172107929-d78923be-b205-4658-a8ab-1b398ac46427.png)

The DRC issue was found with magic, but I was able to reproduce it with the klayout DRC deck.

Test case: [met3_min_area.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/8842337/met3_min_area.tar.gz)

**Comment by maliberty** [comment]
Does the router show any drcs?

**Comment by antonblanchard** [comment]
> Does the router show any drcs?

It completes without any DRC errors:

```
[INFO DRT-0199]   Number of violations = 0.
```

**Comment by Stephanommg** [comment]
The fix is on master branch now.
