### ISSUE TITLE
When I try to connect every macro block into a big one I meet this problem

### ISSUE THREAD

**Issue by Elon-J** [The-OpenROAD-Project/OpenROAD#1943]
How can I connect the VPWR and VGND in my Macro blocks to the top-level power ring using pdn.cfg? Attach my pdn.cfg file.

[pdn.txt](https://github.com/The-OpenROAD-Project/OpenROAD/files/8856700/pdn.txt)

**Comment by msaligane** [comment]
@Elon-J Your GitHub issue has no details and no test case. Jianwei: Please provide as much details as possible so others could help you!

**Comment by arlpetergadfort** [comment]
@msaligane @Elon-J based on the file it appears they are using the deprecated version of PDNgen, so they should probably start by updating to the current version

**Comment by maliberty** [comment]
@Elon-J do you still need help?  There is nothing further we can do without action from you.
