### ISSUE TITLE
RSZ: setup repair on asap7 dies with "unsupported path type" error

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenROAD#1995]
When testing a design with the ASAP7 PDK, I hit an error when doing setup repair:

```
Repair setup violations...
[CRITICAL STA-0259] unsupported path type
```

This also reproduces with the gcd test in ORFS. An issue tarball: [cts_gcd_asap7_base_2022-06-25_06-25.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/8980613/cts_gcd_asap7_base_2022-06-25_06-25.tar.gz)

**Comment by jjcherry56** [comment]
I ran scripts/cts.tcl with the latest OR and it does not reproduce this issue. I honestly don't see any way the code could get to that line since it is inside a debugging function that isn't called by any user commands.

**Comment by antonblanchard** [comment]
@jjcherry56 sorry for that, I was sure I rebuilt from pristine upstream source but obviously one of my debug patches was still applied.
