### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by FFY00** [The-OpenROAD-Project/OpenROAD#205]
Hello, I am interested in packaging OpenROAD. This requires for a release to exist, so I was wondering if you have any plans about this? Perhaps a timeline?

Thanks,
Filipe

**Comment by maliberty** [comment]
We are tentatively planning a 1.0 release around Q3.  What sort of packing do you have in mind?

**Comment by FFY00** [comment]
I want to package this for Arch Linux.

**Comment by sequencer** [comment]
@FFY00 a git version has been packages in aur.

**Comment by FFY00** [comment]
The AUR is not a package repository, it is a PKGBUILD repository. This means users will have to build the package themselves and it may break anytime due to untracked soname changes. Having it in the official repositories should be much better.

**Comment by sequencer** [comment]
Yes, we have to wait for a release for OpenROAD before packaging it into community. Maybe I can push it to the archlinuxcn repository firstly to get rid of the rebuilding burden. After we get the first release, it can upstream into official repository.
