### ISSUE TITLE
filler_placement places cells on top of macros

### ISSUE THREAD

**Issue by rovinski** [The-OpenROAD-Project/OpenROAD#206]
When I run filler_placement, I see that fill cells get placed on top of block macros:
![image](https://user-images.githubusercontent.com/3936698/79275979-309b9f00-7e75-11ea-8dc9-17db39b419f7.png)

These sites should not be filled because they have the cell sites removed:
![image](https://user-images.githubusercontent.com/3936698/79275941-1a8dde80-7e75-11ea-82f6-47951aec94f8.png)

Test case: 
[fillcell_tinyRocket_nangate45_2020-04-14_17-13.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/4477928/fillcell_tinyRocket_nangate45_2020-04-14_17-13.tar.gz)

**Comment by rovinski** [comment]
This was resolved at some point.

**Comment by rovinski** [comment]
This issue has resurfaced (or perhaps never went away and I was looking at the wrong view). The same case is valid.

**Comment by jjcherry56** [comment]
fixed by commit fe43ab7 opendp no fillers over blocks
