### ISSUE TITLE
report_design_area_metrics TCL command in GUI

### ISSUE THREAD

**Issue by stevvik** [The-OpenROAD-Project/OpenROAD#2233]
Hi!
I found, that in GUI 'report_design_area_metrics' command is proposed in autocompletion list, but it does  nothing.
However, 'report_design_area' command works (according to the documentation). But it is absent in autocompletion command list.

**Comment by maliberty** [comment]
report_design_area_metrics is intended for storing into the metrics file not generating user output.  I'll fix the issue that report_design_area is not part of autocomplete.

**Comment by maliberty** [comment]
It doesn't actually write the file but just stores the value in an internal db for collection with other metrics.  Its not a command people will generally use interactively.
