### ISSUE TITLE
padframe: rotating the corners moves them outside of the chip area

### ISSUE THREAD

**Issue by Syndace** [The-OpenROAD-Project/OpenROAD#2253]
When I define out corner padcell using

```TCL
define_pad_cell \
    -name corner \
    -corner \
    -cell_name corner \
    -orient { ll R0 lr R90 ur R180 ul R270 } \
    -physical_only
```

it's in the correct position but rotated incorrectly. When I try to adjust the rotation by 180° as follows:

```TCL
define_pad_cell \
    -name corner \
    -corner \
    -cell_name corner \
    -orient { ll R180 lr R270 ur R0 ul R90 } \
    -physical_only
```

the cell is rotated correctly, but positioned outside of the chip area:

![corner-rotation-bug](https://user-images.githubusercontent.com/5029529/189156662-8f381782-ceac-4fb4-b54b-b6b306172d55.png)

I guess the origin of the cell needs to be adjusted/is adjusted incorrectly after rotation.

**Comment by maliberty** [comment]
Can you provide a test case or is this under NDA?

**Comment by Syndace** [comment]
NDA, but I'll try to build an open-source test case. Will report back when I'm done.

**Comment by Syndace** [comment]
Okay, this can be trivially reproduced with one of the tests. Change into `src/pad/test`, modify line 99 of `tcl_interface.tcl`:

```
@@ -96,7 +96,7 @@ define_pad_cell \
 define_pad_cell \
   -name PAD_CORNER \
   -corner \
-  -orient {ll R0 lr R90 ur R180 ul R270} \
+  -orient {ll R90 lr R180 ur R270 ul R0} \
   -physical_only
 
 define_pad_cell \
```

and run `openroad -gui tcl_interface.tcl`. The GUI will open, run the test and show the following:

![corner-rotation-bug](https://user-images.githubusercontent.com/5029529/189345083-33122ea6-d5c5-4948-bb7f-33c9e86fda19.png)

I know this isn't really a "test case", just instructions for reproducing. Is that enough for you or do you want me to prepare something else?

**Comment by maliberty** [comment]
I think that is enough; I'll give it a try.
@Colin-Holehouse any ideas?

**Comment by maliberty** [comment]
Fixed with https://github.com/The-OpenROAD-Project/OpenROAD/pull/2272

**Comment by Syndace** [comment]
Can confirm this is fixed, thanks!
