### ISSUE TITLE
global routing failed

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenROAD#2346]
OpenLane CI failures for latest OpenROAD updates: https://github.com/The-OpenROAD-Project/OpenLane/pull/1303

OpenROAD Commit: `OpenROAD v2.0-5170-gd919ca2d4 `
Test case:
[issue_reproducible.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/9738869/issue_reproducible.zip)

Logs:
```
[INFO GRT-0015] Inserted 5 diodes.
[INFO GRT-0009] rerouting 139 nets.
[INFO GRT-0001] Minimum degree: 2
[INFO GRT-0002] Maximum degree: 11
[INFO GRT-0006] Repairing antennas, iteration 2.
[INFO GRT-0043] No OR_DEFAULT vias defined.
[INFO GRT-0012] Found 1 antenna violations.
[INFO GRT-0015] Inserted 1 diodes.
[INFO GRT-0009] rerouting 12 nets.
[INFO GRT-0001] Minimum degree: 2
[INFO GRT-0002] Maximum degree: 11
[ERROR GRT-0228] Horizontal edge usage exceeds the maximum allowed.
Error: groute.tcl, 41 GRT-0228
while evaluating source run.tcl
```

**Comment by vijayank88** [comment]
As per log if I change the `DIODE_INSERTION_STRATEGY` flow works fine and completes global routing stage.

**Comment by maliberty** [comment]
I'm testing a fix now.

**Comment by maliberty** [comment]
Apparently my fix takes care of the one design I looked at but there are still others that have issues...

**Comment by vijayank88** [comment]
@maliberty 
Thanks. Let me know if you need test case for other issues.

**Comment by maliberty** [comment]
Thanks but I extracted another myself

**Comment by maliberty** [comment]
@luis201420 you can ignore the reproducer here and use the one I sent you for y_huff in slack

**Comment by maliberty** [comment]
@vijayank88 is this still relevant?

**Comment by vijayank88** [comment]
resolved.
