### ISSUE TITLE
Standard cells of type buffer are not connected to power

### ISSUE THREAD

**Issue by lulu9312** [The-OpenROAD-Project/OpenROAD#2383]
Buffer cells does not connect to power rails.

**Here's the screenshot :**
![std_buf](https://user-images.githubusercontent.com/61928883/196748347-79432a1b-3379-46fc-8181-ba303e76e290.png)

I saw a similar issue while running gcd design as well.

**Comment by lulu9312** [comment]
I tried uploading file to reproduce the issue but I don't know for some reason it's not uploading.

**Comment by maliberty** [comment]
Only certain file types are allowed by GH so perhaps that is your issue.  Do you have a global_connect statement to connect these instances?

**Comment by lulu9312** [comment]
Yes. I have used global_connect statement.
Here's the file to reproduce this case:
[detail_route_ldo_sky130hvl_base_2022-10-20_10-22.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/9826400/detail_route_ldo_sky130hvl_base_2022-10-20_10-22.tar.gz)

**Comment by maliberty** [comment]
It appears that you need to run your global connect statements again as the instance in question must have been created afterwards.

@arlpetergadfort does you recent change in odb provide a way to do this from the db or do the commands need to be run again?

**Comment by arlpetergadfort** [comment]
@maliberty if the flow is fully in ODB, then yes, the rules are saves in the database and they can be rerun at anytime with `global_connect`.

**Comment by maliberty** [comment]
@lulu9312 what flow are you using?  ORFS? OL? other?

**Comment by lulu9312** [comment]
@maliberty I am using ORFS flow. I have added global_connect statement before grobal route, now the cells are connected to power.

![buf_correct](https://user-images.githubusercontent.com/61928883/197778945-8cb8dd1b-6ed4-4fb6-adf2-8b6bce110998.png)
