### ISSUE TITLE
suggestion: include fmt and spdlog as submodules?

### ISSUE THREAD

**Issue by donn** [The-OpenROAD-Project/OpenROAD#2418]
Building OR is something of a problem now on some operating systems given that fmt recently had a new major version release which package managers such as brew and pacman have upgraded to.

As you already include abc in the build process which is much larger than either of those packages, I'm wondering why not simply build fmt and spdlog? You get the ability to pin both versions to avoid this kind of chaos down the line, and its two less dependencies to install.

**Comment by QuantamHD** [comment]
I'd advocate against this approach. I think it's probably better to stay compatible with both versions. 

https://github.com/The-OpenROAD-Project/OpenROAD/issues/2386
