### ISSUE TITLE
PDNGEN Array Spacing Violation

### ISSUE THREAD

**Issue by QuantamHD** [The-OpenROAD-Project/OpenROAD#2497]
It looks like PDNGen may not be complying with a particular array spacing rule in GF180MCU.

https://github.com/efabless/caravel_user_project/issues/185

Specifically 

https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_sc_mcu7t5v0/blob/d3798681284ea9b96bfd57bfda20948ac86767e4/tech/gf180mcu_5LM_1TM_9K_7t_tech.lef#L111

**Comment by maliberty** [comment]
@arlpetergadfort thoughts?

**Comment by arlpetergadfort** [comment]
@maliberty @QuantamHD looks real, not sure why its missing this (it might be honoring the LEF85 ones and missing the non-LEF58, with a testcase I would be able to replicate and fix the issue.

**Comment by maliberty** [comment]
@arlpetergadfort this is related to gf180 caravel and I've asked for a test case already from efabless

**Comment by maliberty** [comment]
@kareefardi please attached the test case to this issue.

**Comment by arlpetergadfort** [comment]
@maliberty Looking around the LEF parser, I cannot see where the array spacing data is stored? There is clearly handling for it in the lef parser itself, but I can't see where it gets added to ODB.

**Comment by QuantamHD** [comment]
@arlpetergadfort It looks like it's set in odb here.   

https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/odb/src/lefin/ArraySpacingParser.cpp#L64

**Comment by arlpetergadfort** [comment]
@QuantamHD those are only the LEF58_ARRAYSPACING rules as far as I can tell. (it's only triggered on the LEF58_ARRAYSPACING keyword).

**Comment by arlpetergadfort** [comment]
This is where that keyword is added to the lefiLayer, but that data is never access again: https://github.com/The-OpenROAD-Project/OpenROAD/blob/c653563d31c25f39cc23f84c3d487aea7ca30136/src/odb/src/lef/lef/lefiLayer.cpp#L3750

**Comment by maliberty** [comment]
It looks like we don't store it currently for the base rule but do for the property.  That just means somebody has to add the  code to query the lef parser and build up the odb structure.  @arlpetergadfort is this something you want to handle or do you prefer I do it?

**Comment by QuantamHD** [comment]
@proppy Could you provide a test case?

**Comment by kareefardi** [comment]
here is a test case [issue_reproducible.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/10020940/issue_reproducible.tar.gz)

**Comment by arlpetergadfort** [comment]
@kareefardi how was this issue generated? The ODB does not have the array spacing rules in it, which leads me to think it was not run with the head of OpenROAD or now run from the beginning. Could you please update OpenROAD and rerun from the start to ensure the tech lef if read in with the new version.

**Comment by kareefardi** [comment]
Yes it is using an older version of openroad. I will generate a new one based on the current head.

**Comment by kareefardi** [comment]
Here is another reproducible. this time there is a change in vias inserted looks like vias are using 0.36um spacing. [issue_reproducible.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/10026155/issue_reproducible.tar.gz)

**Comment by maliberty** [comment]
@kareefardi is the 0.36 acceptable (ie is this resolved)?

**Comment by QuantamHD** [comment]
@kareefardi Is there still a DRC violation?

**Comment by kareefardi** [comment]
It is DRC clean now
