### ISSUE TITLE
Investigate the monotonic router in fastroute

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#2560]
The FastRoute 2.0 and later papers all mention monotonic routing.   FastRouteCore::routeMonotonicAll is never called anywhere in the code so it seems to be unused in practice.  Someone should investigate:

1) Does it work as the papers describe?
2) Does it help if inserted into FastRouteCore::run before maze routing?

**Comment by QuantamHD** [comment]
Paper link https://ieeexplore.ieee.org/document/4196040
