### ISSUE TITLE
Running the GCD flow

### ISSUE THREAD

**Issue by luarss** [The-OpenROAD-Project/OpenROAD#2563]
### Describe the bug

I am using the docker build for OR-flowscripts. When running the default gcd flow for NanGate45, I realised that the hold violation count and setup violation count are inconsistent in the final logs. 

Check 6_report.log and 6_report.json, we see different numbers.

**In 6_report.log**

![image](https://user-images.githubusercontent.com/39641663/205257260-deadaf22-ce34-4413-b797-55782ea0dddf.png)

**In 6_report.json**

![image](https://user-images.githubusercontent.com/39641663/205257305-81d9556c-ecd2-4b47-99bf-0873da14f93a.png)

### Expected Behavior

To my best understanding these two variables should be the same value? I saw the definitions are different in the two source files. So my confusion is which is the correct definition for hold/setup violation? If it is the former I can repost it the flow-scripts repo.

OpenROAD/src/Metrics.tcl
![image](https://user-images.githubusercontent.com/39641663/205256258-ab789c85-70ff-43f1-8248-ceadf0443637.png)

OpenROAD-flow-scripts/flow/scripts/report_metrics.tcl
![image](https://user-images.githubusercontent.com/39641663/205256590-278500d2-58eb-484a-b526-d5eb810f34f9.png)

### Environment

```shell
docker
```

### To Reproduce

.

**Comment by vijayank88** [comment]
@luarss 
Yes, its bug from script `OpenROAD-flow-scripts/flow/scripts/report_metrics.tcl`.
I am not sure, but this issue was already discussed and I thought its fixed. I will check the PR list.

@vvbandeira fyi
