### ISSUE TITLE
Error in detail placement

### ISSUE THREAD

**Issue by vinayrayapati** [The-OpenROAD-Project/OpenROAD#2564]
### Describe the bug

Error in Detail placement
[CRITICAL DPL-0026] legalPt called on fixed cell.

<img width="572" alt="Screenshot 2022-12-02 at 6 36 46 PM" src="https://user-images.githubusercontent.com/110079631/205299675-b7a56cca-8f51-4f83-8e0c-a862e844ae69.png">

### Expected Behavior

Succesfull placement

### Environment

```shell
Please pull the latest changes and try again, if problem persists file a github issue with the re-producible test case.
```

### To Reproduce

[Issue_reproducible.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/10141299/Issue_reproducible.zip)

**Comment by vijayank88** [comment]
The attached test case is not valid. Please provide steps to reproduce.
Also you're using outdated OpenROAD version, update and try.

**Comment by vijayank88** [comment]
`Please don't attach screenshot, always copy paste the logs in texts in given template`

As per the log trying to copy `3_5_place_dp.odb` and file not found and flow failing.

**Comment by vinayrayapati** [comment]
@vijayank88 I am using OpenROAD in macOS. `3_5_place_dp.odb` file is the output of the detail placement. Since there is an error in the detail placement, the output file is not created and the next step is giving error as no file or directory. The actual error is `[CRITICAL DPL-0026] legalPt called on fixed cell`.

**Comment by vijayank88** [comment]
Please re-open an issue with test case, if still there is an issue with latest OpenROAD commits.
