### ISSUE TITLE
grt creates guides in areas with no space for a track

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenROAD#2615]
### Describe the bug

While building up test cases for TA I found what looks like a grt issue. Here you can see an obstruction (dark blue) that almost covers the gcell. There is nowhere near enough space for a single track. Even so, the global guide for net `w0_in` goes through this obstructed gcell:

![grt-1](https://user-images.githubusercontent.com/2029971/207486887-5ba8c1bd-d46e-4f73-81d2-559e1318a982.png)

You can see the drt result, where it had to go off guide to resolve it. Even if I add a large derating (40%), grt still wants to route a track through it.

I'm not sure if it's a gui issue, but it's interesting that top row of gcells is not square.

### Expected Behavior

We don't create global routing guides through gcells that do not have enough space for a track.

### Environment

```shell
Git commit: e634017c847e09aa54aa78d2b1386474f975b771
os: Fedora Linux 36 (Workstation Edition)
cmake version 3.24.2
gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
clang version 14.0.5 (Fedora 14.0.5-1.fc36)
```

### To Reproduce

Test case:  [drt-1.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/10223645/drt-1.tar.gz)

**Comment by maliberty** [comment]
If the design size is not an integral number of gcells the the top/right cell will be taller/wider than the others.  It is better to avoid a fractional gcell.  

The main issue looks like a bug.

**Comment by QuantamHD** [comment]
Fixes https://github.com/The-OpenROAD-Project/OpenROAD/pull/2616

**Comment by antonblanchard** [comment]
This is now fixed
