### ISSUE TITLE
cts viewer highlight cofusing for mulitple clocks

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#2637]
### Describe the bug

If I open sky130hd/microwatt I see:

![image](https://user-images.githubusercontent.com/761514/207980434-7b14b513-4ecc-4f49-9705-666564a8ec02.png)

It seems both clocks are being highlighted at once.  

### Expected Behavior

I think we should only highlight for the clock in the active tab.

### Environment

```shell
head of master
```

### To Reproduce

as above

**Comment by gadfort** [comment]
@maliberty would you still want to be able to turn off the clock rendering all together? Ie. so you can view the tree without the rendering or do you think that would not be a useful control?

**Comment by maliberty** [comment]
I think that would be useful too

**Comment by gadfort** [comment]
@maliberty when I run the skyhd microwatt I get
```
[INFO][FLOW-xxxx] Using manual macro placement file ./designs/sky130hd/microwatt/microwatt.macro_placement.cfg
Error: macro_place.tcl, 125 Cannot find instance soc0.bram.bram0.ram_0.memory_0
```

**Comment by maliberty** [comment]
It passed in last night's CI.  Something odd is happening in your setup.

**Comment by gadfort** [comment]
> It passed in last night's CI.  Something odd is happening in your setup.

Yes, I had turned off flattening its working again
