### ISSUE TITLE
pdngen missing repair strap

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#2638]
### Describe the bug

With the update to hier-rtlmp & cts a problem has developed in ng45/bp_be_top where psm errors on a disconnected power grid.  
```
[WARNING PSM-0038] Unconnected PDN node on net VDD at location (10.070um, 505.400um), layer: 1.
[WARNING PSM-0039] Unconnected instance PHY_2260 at location (10.070um, 505.400um) layer: 1.
[WARNING PSM-0039] Unconnected instance PHY_2250 at location (10.070um, 505.400um) layer: 1.
...
```
It appears that pdn is not putting in a repair strap in a channel on the left:

![image](https://user-images.githubusercontent.com/761514/208022266-fd74b8a9-14f8-49c8-9a5f-c904842ad954.png)

You can see a repair strap in the lower portion of the channel but not in the upper portion.  

I have temporarily disabled psm on this design.  When this is fixed it should be re-enabled.

### Expected Behavior

A fully connected power grid.

### Environment

```shell
head of master
```

### To Reproduce

DESIGN_CONFIG=./designs/nangate45/bp_be_top/config.mk make

**Comment by gadfort** [comment]
@maliberty I ran the command, but my output looks mirrored from the picture you uploaded. And I haven't been able to see the issue yet on it.

**Comment by maliberty** [comment]
Maybe something else changed - I'll rerun it and attach a test case if I can reproduce it.

**Comment by maliberty** [comment]
Something has changed and the problem disappeared due to change in macro locations.  That's teach me to not record the commit id.  I'll close this and reopen if the problem returns.
