### ISSUE TITLE
PDN needs to support vias in macro pins

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#2653]
### Describe the bug

See the discussion in https://github.com/The-OpenROAD-Project/OpenROAD/pull/2650

PDN errors out if a macro pin contains a via

### Expected Behavior

PDN completes

### Environment

```shell
Latest OR
```

### To Reproduce

No public test case is available but one can easily be generated

**Comment by oharboe** [comment]
To reproduce, use this pull request:

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/709
