### ISSUE TITLE
Detail route ends with DRC violations

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenROAD#2680]
### Describe the bug

With OpenROAD commit `7c85c140308f01b73f57ea1117f3e43f39abd437` attached design successfully completed routing without any violations.

Same design creates short violations with latest OpenROAD commit.

### Expected Behavior

Complete detail routing

### OpenROAD Environment

```shell
`4f1108b6f558718ed142cbb6c1f5ba20958195ca`
```

### OpenLane Environment

```shell
OpenLane Tag 2022.12.29
OpenROAD Commit `4f1108b6f558718ed142cbb6c1f5ba20958195ca`
```

### To Reproduce

Due to file size limit, test case uploaded here: https://slack-files.com/T01699QAZBQ-F04H11VDY4S-7f29fa9423

### Relevant log output

```shell
[INFO DRT-0195] Start 64th optimization iteration.
    Completing 10% with 1065 violations.
    elapsed time = 00:00:00, memory = 17330.63 (MB).
    Completing 20% with 1065 violations.
    elapsed time = 00:00:00, memory = 17331.92 (MB).
    Completing 30% with 1064 violations.
    elapsed time = 00:01:12, memory = 17570.39 (MB).
    Completing 40% with 1064 violations.
    elapsed time = 00:01:12, memory = 17570.77 (MB).
    Completing 50% with 1062 violations.
    elapsed time = 00:03:15, memory = 17872.86 (MB).
    Completing 60% with 1062 violations.
    elapsed time = 00:03:15, memory = 17872.86 (MB).
    Completing 70% with 1062 violations.
    elapsed time = 00:03:15, memory = 17872.86 (MB).
    Completing 80% with 1062 violations.
    elapsed time = 00:04:17, memory = 18168.96 (MB).
    Completing 90% with 1062 violations.
    elapsed time = 00:04:17, memory = 18169.19 (MB).
    Completing 100% with 1062 violations.
    elapsed time = 00:06:29, memory = 18387.95 (MB).
[INFO DRT-0199]   Number of violations = 1062.
Viol/Layer        met1   met2
Short              307    755
[INFO DRT-0267] cpu time = 00:25:23, elapsed time = 00:06:30, memory = 18382.40 (MB), peak = 18724.14 (MB)
```

### Additional Context

CI pass patmos_chip successfully with OpenLane tag 2022.12.23 and previous tags: (https://jenkins.openroad.tools/blue/organizations/jenkins/OpenLane-MPW-CI-Public%2Fproduction-large-1/detail/PR-124/1/pipeline/366)
CI fails with 2022.12.25 and above(After OpenROAD commit Update): https://jenkins.openroad.tools/blue/organizations/jenkins/OpenLane-MPW-CI-Public%2Funstable-large-1/detail/main/65/pipeline/323

**Comment by maliberty** [comment]
When I run your test case:
```
Error: droute.tcl, 15 cannot read file /home/vijayan/FORK_OPENROAD/OL_MPW_CI/OpenLane-MPW-CI/OpenLane/pdks/sky130A/libs.ref/sky130_sram_macros/lib/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib.
```

Please upload a self-contained test

**Comment by vijayank88** [comment]
Include missing library with test case again here: https://slack-files.com/T01699QAZBQ-F04GR7YN7U7-8803993c7d

**Comment by maliberty** [comment]
All the violations are on top of a macro:
![image](https://user-images.githubusercontent.com/761514/210260636-9b55d3bf-e946-411e-aaeb-fd0239931fd6.png)

If I look at one of the nets the guide goes right through the macro on met2:
![image](https://user-images.githubusercontent.com/761514/210260686-76c0add2-f7ad-4c66-9165-31d0227dd263.png)

so the problem is in global routing.  Please prepare a test case for the global router.

**Comment by vijayank88** [comment]
@maliberty Attached Global routing stage test case: https://slack-files.com/T01699QAZBQ-F04H82ASCBV-f5ad3a03f6

**Comment by maliberty** [comment]
@luis201420 please look at why there are guides go through the macro that should be blocking them

**Comment by vijayank88** [comment]
@maliberty @luis201420 
Please stop debugging this issue.
It was the problem of `GRT_OBS` not defined properly.
There was extra space during `\` definition and its caused violation.
After fixing that empty space now its passing routing stage locally without any issue.
