### ISSUE TITLE
`utl::metric_float` outputs invalid JSON in case of `inf` values

### ISSUE THREAD

**Issue by donn** [The-OpenROAD-Project/OpenROAD#2715]
### Describe the bug

Generating metrics with infinite values generates invalid JSON files.

![Screen Shot 2023-01-07 at 9 36 07 PM](https://user-images.githubusercontent.com/12652988/211165583-1202593c-91dd-472f-b0cf-3e2670a50677.png)

JSON generally does not have full support for IEEE754 and infinite values are not allowed. I'm… not sure what the alternative here would be exactly but compliant JSON parsers will reject the output file.

### Expected Behavior

A parseable JSON file.

Can the values be intercepted and dumped as strings, "+Infinity" or "-Infinity", perhaps?

### Environment

```shell
Git commit: bc67783cb6d819f39828a6a511ae771c9e2f083f
kernel: Linux 5.15.0-1025-gcp
os: Ubuntu 20.04.4 LTS (Focal Fossa)
cmake version 3.22.2
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
clang version 10.0.0-4ubuntu1
```

### To Reproduce

[repro.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/10366981/repro.tar.gz)

**Comment by QuantamHD** [comment]
@gadfort I think you made this change

**Comment by gadfort** [comment]
I've filed a PR to fix it since we were having the same issue. Just pending approval

**Comment by gadfort** [comment]
#2712 is the PR for reference

**Comment by gadfort** [comment]
Actually looking at this, I think this might be a divide by 0 issue.

**Comment by maliberty** [comment]
It is which I'll fix.

**Comment by maliberty** [comment]
Do you still want to proceed?  https://github.com/The-OpenROAD-Project/OpenROAD/pull/2721

**Comment by gadfort** [comment]
I'm okay with #2721 if the metrics logger needs to be augmented we can revisit
