### ISSUE TITLE
More specific types of TNS and WS Metrics

### ISSUE THREAD

**Issue by donn** [The-OpenROAD-Project/OpenROAD#2735]
### Description

Currently there are a variety of TNS and WS metrics:

```tcl
sta::report_tns_metric -setup
sta::report_tns_metric -hold
sta::report_worst_slack_metric -setup
sta::report_worst_slack_metric -hold
sta::report_erc_metrics
sta::report_power_metric
sta::report_design_area_metrics
```

This is great- we're wondering if there's a way to add more specific types of TNS and WS metrics though, like worst input to register, worst register to register, etc. We plan to integrate metrics with OpenLane such that the flow can dynamically configure itself based on the extracted metrics, and the ones I mentioned would be helpful.	

### Suggested Solution

Add more commands! (or flags)

**Comment by tspyrou** [comment]
https://github.com/The-OpenROAD-Project/OpenSTA/blob/695b0bed2f6c43cdff51c8b1ba43653b01313150/tcl/Search.tcl#L87
find_timing_paths -from [all_inputs] -to [all_outputs] returns a list of paths which can be probed for slack.
This can be written in tcl.
