### ISSUE TITLE
Should we fork LEMON

### ISSUE THREAD

**Issue by QuantamHD** [The-OpenROAD-Project/OpenROAD#2791]
### Description

The [LEMON](https://lemon.cs.elte.hu/trac/lemon) library is a required by OpenROAD, but the maintainers are not very responsive to bug fixes.

The last official release of LEMON was in 2014, but it has commits as recent as 2020. We've since run into some problem with the library not supporting C++20, and were required to introduce patches.

LEMON is pretty widely distributed by package managers so by requiring a custom version of this library we're potentially introducing a conflict. If we do so I think it would be best to hard fork LEMON and make sure to rename its install directory.

**Comment by maliberty** [comment]
Are your patches only required to compile lemon and not to use it as a library?  If so we should try to contribute them back and see what happens.

**Comment by QuantamHD** [comment]
LEMON is largely a header only lib, and the patch affects the header.

**Comment by maliberty** [comment]
So the widely distributed version by package managers will never work with c++ unless they do a new release?  That seems like enough of an issue to fork over if they will not take the changes and put out a release.  Perhaps try asking on their email lists and see if there is anyone willing/able to do a release.

**Comment by mithro** [comment]
FYI - Be careful, if you fork a project you are now responsible for all its maintenance going forward.

**Comment by gadfort** [comment]
When I suggested forking this, it was over the prospect that OpenROAD is dependent on this project, but they have not been responsive to patches like the one required for C++20. I don't think OpenROAD project should take over the project (clearly over the last 10 years, people have been happy with no fixes, so I would imagine that this would not add much in overhead).  LEMON does not appear in Ubuntu 20's repos, so I would guess that this would drop over time as they become more and more incompatible with modern compilers.

The only maintenance this project should be responsible for, is that required for OpenROAD (in my opinion).

**Comment by maliberty** [comment]
I don't feel any need to be "responsible for all its maintenance going forward"

**Comment by gadfort** [comment]
I know this topic is a bit stale, but it looks like the lemon downloads are not working... So I think it's worth revisiting at least to ensure functional installs

**Comment by QuantamHD** [comment]
Agreed. @vvbandeira can you create a repo called LEMON in the organization, and give myself and @gadfort  push access

**Comment by gadfort** [comment]
@QuantamHD do you happen to have a copy? I don't seem to have one on any of my machines.

**Comment by maliberty** [comment]
@gadfort https://github.com/mdfbaam/Lemon appears to be a copy for now

@vvbandeira looks like their site is down which is a good argument for doing this.

**Comment by QuantamHD** [comment]
I have a copy of the mercurial repo at work. Internet archive should also have a copy.

**Comment by QuantamHD** [comment]
Here's the copy of the [mercurial](https://www.mercurial-scm.org/) repo.  You'll need to download mercurial if you want to use SCM commands. right now the repo's head is at my C++20 changes.

[lemon.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/11012324/lemon.tar.gz)

**Comment by maliberty** [comment]
The lemon website is back online

**Comment by gadfort** [comment]
@maliberty it would appear this is down again

**Comment by maliberty** [comment]
We should make a GH mirror in our project.
