### ISSUE TITLE
Use/add SWIG 4.1.0 configuration in CI runs

### ISSUE THREAD

**Issue by cdleary** [The-OpenROAD-Project/OpenROAD#2794]
### Description

See https://github.com/The-OpenROAD-Project/OpenROAD/issues/2777#issuecomment-1397757102 -- since it's the version referenced in https://github.com/The-OpenROAD-Project/OpenROAD/blob/50e6ee4f8ba5b70ad98b48d4637ef15f388cf73a/etc/DependencyInstaller.sh#L12 we should probably ensure it has coverage in the CI image.

**Comment by vvbandeira** [comment]
Updated CI image, see #2731 logs.
