### ISSUE TITLE
list the installation requirements somewhere

### ISSUE THREAD

**Issue by mattvenn** [The-OpenROAD-Project/OpenROAD#2811]
### Description

I needed spdlog and I'm stuck with finding out what lemon is.
A list of requirements would be good, and even better a list of common package names so that I could apt-get install easily.

**Comment by vijayank88** [comment]
@mattvenn 
By running  `./etc/DependencyInstaller.sh -local` will install required packages.
https://github.com/The-OpenROAD-Project/OpenROAD#install-dependencies
What is the error got during installation?

**Comment by mattvenn** [comment]
thanks!
