### ISSUE TITLE
pins are not constrainted to the correct edge during floorplanning causing bogus error messages

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#2819]
### Describe the bug

Run:

```
make DESIGN_CONFIG=designs/asap7/mock-array-big/Element/config.mk floorplan
make DESIGN_CONFIG=designs/asap7/mock-array-big/Element/config.mk gui_floorplan
```

### Expected Behavior

The pins should be constrained to the correct edge during floorplanning, otherwise one can get bogus errors about there not being enough space for pins on the edges.

### Environment

```shell
Git commit: 53c6e6dfd60130d056eeda896d1d75b0a632f739
kernel: Linux 5.15.0-58-generic
os: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
cmake version 3.24.2
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Ubuntu clang version 14.0.0-1ubuntu1
```

### To Reproduce

Use commands above with the example in master.

### Relevant log output

This is an *example* of a bogus error. This happens in a local design I can't share, but I believe I have correctly identified the root cause: a bogus error during floorplanning because pin placement constraints are not in effect.

```
Using 1u default distance from corners.
[INFO PPL-0007] Random pin placement.
[ERROR PPL-0072] Number of pins (32) exceed number of valid positions (10).
Error: io_placement_random.tcl, 14 PPL-0072
```

### Screenshots

Only ins_1 and outs_1 pins should be on the right edge: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/b30bac97a008e33d609c3710338793c9508f78b5/flow/designs/asap7/mock-array-big/Element/io.tcl#L25

The outs_3 should not appear on the right edge according to the pin constraints:

![image](https://user-images.githubusercontent.com/2798822/214856197-41ee8c7c-e4b1-4be3-8613-caebc6855b37.png)

After placement, the pins are constrained to the expected edge, ins_1 and outs_1 pins:

![image](https://user-images.githubusercontent.com/2798822/214856493-cbe966db-9f4f-40f5-9266-4b70c805de5c.png)

**Comment by eder-matheus** [comment]
@oharboe I've used the `mock_array_big` design to test my fixes, which is working now. Both constraints and mirrored pins are working on the random pin placement (the one that runs during floorplan). Could you try this branch: https://github.com/The-OpenROAD-Project/OpenROAD/pull/2822?
