### ISSUE TITLE
Add "Goto Position" to the GUI

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#2832]
### Description

Have an equivalent to KLayout's "Goto Position"
![image](https://user-images.githubusercontent.com/761514/215865936-1414a1b6-1232-4ff7-9568-d1c08577ce65.png)

When the dialog appears the default entry appears to be based on the current view.

From a discussion w/ @antonblanchard

**Comment by maliberty** [comment]
I think the KLayout dialog should not be directly copied as these should be three distinct entry widgets.  DBU or microns should be supported as in the rest of the GUI.

**Comment by gadfort** [comment]
@maliberty It should be relatively easy to implement. But not 100% on the timeline.

**Comment by antonblanchard** [comment]
> I think the KLayout dialog should not be directly copied as these should be three distinct entry widgets. DBU or microns should be supported as in the rest of the GUI.

Sounds good. There are a few other things that annoy me about the klayout goto, so we don't have to copy it completely.

eg if you just put in x,y without a window size it doesn't zoom and just places crosshairs on the point. That requires you to manually zoom to the point. If, on the other hand, you reopen the goto dialog to add the window size, the x,y settings have been reset.

**Comment by gadfort** [comment]
@antonblanchard are you suggesting that the x,y be prepopulated with the current center?

**Comment by maliberty** [comment]
It seems like the dialog is pre populated with the current x, y, s

**Comment by maliberty** [comment]
https://github.com/The-OpenROAD-Project/OpenROAD/pull/2974
