### ISSUE TITLE
Make command in ibex processor crashes after 70% 

### ISSUE THREAD

**Issue by Eyantra698Sumanto** [The-OpenROAD-Project/OpenROAD#2988]
### Describe the bug

OpenROAD crashed after 70% with a lot of violations for the [Ibex Controller](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/designs/src/ibex/ibex_controller.v)..

### Expected Behavior

OpenROAD should not crash and the no. of violations should be less.

### To Reproduce

Run `make "DESIGN_CONFIG=./designs/asap7/ibex/config.mk"` in the OpenROAD flow scripts.

### Screenshots

![image](https://user-images.githubusercontent.com/58599984/223680113-a79eeba6-c069-417c-9b70-6f65d67eb2bc.png)

### Additional Context

Bug reported by Subhradip Chakraborty.

**Comment by maliberty** [comment]
The design passes in the nightly CI so it is likely a local problem.  This report is too vague to be actionable.  What commit id?  What platform?  Are you running out of memory?

**Comment by vvbandeira** [comment]
@Eyantra698Sumanto 

Please follow the Issue template closely. There are instructions that must be followed to help us understand the problem:

![image](https://user-images.githubusercontent.com/9001905/223729398-865e1b77-a62b-4e0b-b3d4-74e205604b33.png)

**Comment by vijayank88** [comment]
As per slack channel discussion with user, in VM they had only 4GB RAM. So once it reaches peak it got exited.

Increase the swap memory for your system and try again.
