### ISSUE TITLE
[ERROR PPL-0013] Internal error, placed more pins than exist (97 out of 65).

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3055]
### Describe the bug

When I use the new -group and -order set_io_constrains feature, I get the error above.

### Expected Behavior

No error

### Environment

```shell
It is recommened to pull the latest changes.
If problem persists, file a github issue with the re-producible test case.
kernel: Linux 5.15.0-67-generic
os: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
cmake version 3.22.1
```

### To Reproduce

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/905

**Comment by oharboe** [comment]
@eder-matheus @maliberty I was able to reproduce it, see build log for https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/905

**Comment by eder-matheus** [comment]
@oharboe Sorry for the delay. I was having trouble to reproduce it on my Mac. Something is weird with the `make issue` for this new design.

Anyway, this PR should fix the issue: https://github.com/The-OpenROAD-Project/OpenROAD/pull/3075
Could you check with your internal testcase?

**Comment by maliberty** [comment]
There was a bug in make issue that I fixed this week.
