### ISSUE TITLE
Default colors in ASAP7 are too dark when used on black

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3165]
### Description

The text against black for these pins is illegible.

![image](https://user-images.githubusercontent.com/2798822/231435663-42365724-0288-45d3-b624-807f2edb4d8f.png)

### Suggested Solution

Have a default color scheme that's better adapted to be readable against black background.

### Additional Context

Of course it is possible to change the colors in the GUI, but this feature request is about readability in the default case without needing to configure things.

**Comment by antonblanchard** [comment]
I've also noticed that the lowest layer color (dark blue / RGB(0, 0, 254)) is hard to see, eg the preferred/non preferred tracks. Perhaps the color palette used is more suited to a white background.

https://github.com/The-OpenROAD-Project/OpenROAD/blob/9f3dc03de34aacd843716e10988c80e56abc448d/src/gui/src/displayControls.cpp#L1726

**Comment by maliberty** [comment]
We could turn off the alpha for the text which would make it a bit clearer.  The color of the text matches the layer color which is useful if you have pins on multiple layers.  
![image](https://user-images.githubusercontent.com/761514/231661630-2c4a3d73-29d7-4cd2-aa9f-e005eef1e0f9.png)
 vs 
![image](https://user-images.githubusercontent.com/761514/231661672-1ab64924-1fbb-4954-a2d0-11ab1dccf556.png)
We could just draw it in white as instead.

@gadfort @rovinski any preferences?

**Comment by maliberty** [comment]
I see that http://vrl.cs.brown.edu/color has changed some since I generated those colors (more knobs).  I don't get the same set anymore fwiw.  I'm open to suggestions.  The first three layers have traditional values and I wouldn't change them too far.

**Comment by gadfort** [comment]
@maliberty I would prefer to preserve the color of the text to match that of the layer, so removing the alpha might be a good solution

**Comment by maliberty** [comment]
@antonblanchard you might try setting the alpha=255 for m1 and see if that helps with tracks.

**Comment by gadfort** [comment]
@maliberty is this still a thing?

**Comment by oharboe** [comment]
Yes, still hard to see.

**Comment by maliberty** [comment]
I don't find it hard to see in this case
![image](https://github.com/user-attachments/assets/58bd0195-b5df-48b1-b087-7e979e2b8de3)

do you disagree?

**Comment by oharboe** [comment]
> I don't find it hard to see in this case ![image](https://private-user-images.githubusercontent.com/761514/377717712-58bd0195-b5df-48b1-b087-7e979e2b8de3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMjY2NTgsIm5iZiI6MTcyOTIyNjM1OCwicGF0aCI6Ii83NjE1MTQvMzc3NzE3NzEyLTU4YmQwMTk1LWI1ZGYtNDhiMS1iMDg3LTdlOTc5ZTJiOGRlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwNDM5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTdkNjM4YWE1YzljM2NlYTE0NzM3YmU4M2Y1ZTE1ODQ2YWM3MGYxMzI3OWZlYTc1NmNhZTJiYzViM2MwM2JmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8-DXqZFBMgIbtXmLPda6EmCfHOZCOBLggXOyYwUWgMc)
> 
> do you disagree?

I find it hard to see, yes. I'll ask a few colleagues.

**Comment by maliberty** [comment]
Do you find it hard to see other shapes on that layer or just the text?

**Comment by oharboe** [comment]
> Do you find it hard to see other shapes on that layer or just the text?

Both.

**Comment by maliberty** [comment]
> The text against black for these pins is illegible.

If this a general color issue and not a text issue that's somewhat different.  You can change the color by double clicking the color chip.

**Comment by oharboe** [comment]
> > The text against black for these pins is illegible.
> 
> If this a general color issue and not a text issue that's somewhat different. You can change the color by double clicking the color chip.

The feature request here is that openroad ships with color scheme(s) that don't have to be tweaked to get something readable.

**Comment by maliberty** [comment]
I tried http://vrl.cs.brown.edu/color with 
![image](https://github.com/user-attachments/assets/6c6bdc7f-4538-465d-8343-734f9a1a9e32)
![image](https://github.com/user-attachments/assets/0afb2d91-0acc-4b8a-8452-3c826dc062e8)
 
and get
![image](https://github.com/user-attachments/assets/9322df2f-de64-4322-9324-b747b80e9bee)

How does that seem?  Perhaps you can play around and see if you find a palette that works for you.

**Comment by maliberty** [comment]
Readability is subjective - I find it does that already.  You need to be more specific/helpful to get anything to happen.

**Comment by oharboe** [comment]
Pointer to OpenROAD code where this is stored?

**Comment by oharboe** [comment]
> Readability is subjective - I find it does that already. You need to be more specific/helpful to get anything to happen.

I'll try to make it quantitative: running a poll now.

**Comment by maliberty** [comment]
https://github.com/The-OpenROAD-Project/OpenROAD/blob/b972b34737c9382bbcf0ca492ecec74d3e958622/src/gui/src/displayControls.cpp#L1912

**Comment by oharboe** [comment]
@maliberty Quick poll by 3 colleagues no-one thought it was easy, 2x hard to read, 1x readable but could be brighted.

**Comment by maliberty** [comment]
I already gave a suggestion above but got no response.

**Comment by oharboe** [comment]
I made a PR... https://github.com/The-OpenROAD-Project/OpenROAD/pull/5982
