### ISSUE TITLE
make gui_target is not able to find .odb file

### ISSUE THREAD

**Issue by ripudamank2** [The-OpenROAD-Project/OpenROAD#3184]
### Describe the bug

[INFO][FLOW] Using platform directory ./platforms/nangate45
make: *** No rule to make target 'gui_6_final.odb', needed by 'gui_final'.  Stop.

How can i update OpenRoad ?

### Expected Behavior

it should open gui 

### Environment

```shell
[WARNING] Your current OpenROAD version is outdated.
It is recommened to pull the latest changes.
If problem persists, file a github issue with the re-producible test case.
kernel: Linux 5.19.0-38-generic
os: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
cmake version 3.24.2
CMake Error: The source directory "/home/embedded/Documents/OpenROAD-flow-scripts" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

### To Reproduce

make DESIGN_CONFIG=./designs/sky130hd/ibex/config.mk

**Comment by maliberty** [comment]
Does results/sky130hd/ibex/6_final.odb exist?  The gui target only loads an existing file.

**Comment by ripudamank2** [comment]
![image](https://user-images.githubusercontent.com/8544850/232283370-cb13eeca-d3a9-47d4-aac3-cbc3a2aa22c6.png)

**Comment by ripudamank2** [comment]
I found the issue i was using "make gui_final" but to open the design I need to do `make gui_final DESIGN_CONFIG=./designs/sky130hd/ibex/config.m`
