### ISSUE TITLE
start with -gui core dump

### ISSUE THREAD

**Issue by ydxc** [The-OpenROAD-Project/OpenROAD#3186]
### Describe the bug

❯ ./openroad -gui
Signal 11 received
Stack trace:
 0# 0x0000560C4F630D5B in ./openroad
 1# 0x00007EFE5B960090 in /lib/x86_64-linux-gnu/libc.so.6
 2# 0x0000560C4F828D26 in ./openroad
 3# std::_Function_handler<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const (), std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()> >::_M_invoke(std::_Any_data const&) in ./openroad
 4# gui::HeatMapDataSource::setSettings(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::variant<bool, int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::variant<bool, int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&) in ./openroad
 5# gui::HeatMapRenderer::setSettings(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::variant<bool, int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::variant<bool, int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&) in ./openroad
 6# gui::DisplayControls::registerRenderer(gui::Renderer*) in ./openroad
 7# gui::Gui::registerRenderer(gui::Renderer*) in ./openroad
 8# gui::Gui::registerHeatMap(gui::HeatMapDataSource*) in ./openroad
 9# sta::PowerDensityDataSource::PowerDensityDataSource(sta::dbSta*, utl::Logger*) in ./openroad
10# ord::initDbSta(ord::OpenRoad*) in ./openroad
11# ord::OpenRoad::init(Tcl_Interp*) in ./openroad
12# ord::tclAppInit(Tcl_Interp*) in ./openroad
13# gui::TclCmdInputWidget::setTclInterp(Tcl_Interp*, bool, std::function<void ()> const&) in ./openroad
14# gui::startGui(int&, char**, Tcl_Interp*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) in ./openroad
15# ord::tclAppInit(Tcl_Interp*) in ./openroad
16# Tcl_MainEx in /usr/lib/x86_64-linux-gnu/libtcl8.6.so
17# main in ./openroad
18# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
19# _start in ./openroad
[1]    8186 segmentation fault (core dumped)  ./openroad -gui

### Expected Behavior

null

### Environment

```shell
null
```

### To Reproduce

null

**Comment by maliberty** [comment]
I just found the same and fixed in https://github.com/The-OpenROAD-Project/OpenROAD/pull/3185
