### ISSUE TITLE
Names on floorplan of macros is illegible with out of the box colors (light yellow on light grey)

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3188]
### Description

![image](https://user-images.githubusercontent.com/2798822/232333820-ea6cf9b4-6bbc-48d5-8dcc-02cf948dafb9.png)

### Suggested Solution

Better default color scheme without need for configuration.

**Comment by AcKoucher** [comment]
@oharboe Would it be possible to get a larger print screen of the problem?

**Comment by oharboe** [comment]
@AcKoucher I wonder if the color scheme changed. 

Here is a screenshot from https://github.com/The-OpenROAD-Project/OpenROAD/issues/3484

Quite readable out of the box...


![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/3f2bd189-7337-4b05-a281-9c3ad34b03df)

**Comment by maliberty** [comment]
I don't think anything has changed.  It might depend on what layers you have showing as your first image was against a more gray background.

**Comment by oharboe** [comment]
I have forgotten how I got the grey background and I don't have that design any longer(it was confidential, so I couldn't share it). I don't have a reproduction case from mock-array-big.

Close?
