### ISSUE TITLE
Rows are not read from settings

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#3219]
### Describe the bug

Since #3204 the rows are always on when you start the OR gui.  I believe we don't handle the settings now that it is per site.

### Expected Behavior

I think we should store the overall row settings (on/off) even if we don't store the per site values which would be PDK dependent.

### Environment

```shell
head of master
```

### To Reproduce

any design

**Comment by gadfort** [comment]
@maliberty if there are two sites and only one is on, should that count as both on when the GUI restarts or as both off?

**Comment by maliberty** [comment]
Its a bit arbitrary but I would count it as on since they are at least interested in something to do with rows.

**Comment by maliberty** [comment]
We might change the default to Unchecked as well.
