### ISSUE TITLE
Problems with 2 gByte limit in file handling

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3225]
### Describe the bug

Do a pass of the source code to hunt down 32 bit int problems with file pointers.

With .odb files, this can reach the gigabyte size and overflow the 32 bit size of int.

Example of a problem, I found 47 uses of ftell() and several of them used int (32 bit on x86 Ubuntu):

https://github.com/The-OpenROAD-Project/OpenROAD/blob/0b74722ee863e76ed6a648c33927b91cf1d9e6a9/src/odb/include/odb/dbStream.h#L235

### Expected Behavior

Handle >2gByte files

### Environment

```shell
master
```

### To Reproduce

search as above to find the spots to be fixed

**Comment by maliberty** [comment]
That example is dead code.  The problem description itself is too vague to be actionable.  I haven't observed any issues with files > 2gb (including those from you).

**Comment by oharboe** [comment]
> That example is dead code. The problem description itself is too vague to be actionable. I haven't observed any issues with files > 2gb (including those from you).

@maliberty Search for tellg(), you will find lots of cases which store the result in an "int", which is 4 bytes.

Example, this will overflow with >2gByte files:

![image](https://user-images.githubusercontent.com/2798822/233929310-d66d3984-c16e-4ccf-b0f8-d6d5737e1307.png)

Certainly .odb files can be > 2gByte, I don't know about which file types that can realistically be >2gByte.
