### ISSUE TITLE
Render in background

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3279]
### Description

When I click to enable heatmap, the GUI becomes unresponsive for a long time.

I need to click on heatmap to configure it and enable it. This means changing, say, 4 parameters(min, max, legend, enable). Now I have to wait 4 * 20 seconds.

### Suggested Solution

Do heavy calculations in the background and leave GUI responsive.

**Comment by maliberty** [comment]
The database is not thread safe and collisions could happen (say you started the global router while the congestion map was being calculated).  It would require some special limited operation mode and it would be tricky to get right.  It has been discussed before but hasn't risen to the top because of the effort involved relative to the gain.

**Comment by oharboe** [comment]
> The database is not thread safe and collisions could happen (say you started the global router while the congestion map was being calculated). It would require some special limited operation mode and it would be tricky to get right. It has been discussed before but hasn't risen to the top because of the effort involved relative to the gain.

I see.


As a first step, it would be nice to push out rendering so that it isnt done 4x when changing heatmap settings.

**Comment by maliberty** [comment]
@gadfort thoughts?

**Comment by gadfort** [comment]
Once the heatmap is computed it's just drawing it thats the issue (which shoudn't take too long).
It's not until the heatmap is needed that it is populated to avoid slowing down actually useful work in OpenROAD. There might be other inefficiencies that could be addressed, but as long as the database doesn't allow for threaded the options are somewhat limited.

@oharboe where does this 4x come from?

**Comment by maliberty** [comment]
@gadfort what makes the computation of the heatmap slow?

**Comment by gadfort** [comment]
There are some r-tree lookups (which are not that slow) and some add and multiply, but thats really it.
When it comes to the congestion map, the real issue it probably when zoomed out on a big design there can be a lot of gcells to draw. If the bins for congestion maps were larger it would be faster.

**Comment by oharboe** [comment]
> Once the heatmap is computed it's just drawing it thats the issue (which shoudn't take too long). It's not until the heatmap is needed that it is populated to avoid slowing down actually useful work in OpenROAD. There might be other inefficiencies that could be addressed, but as long as the database doesn't allow for threaded the options are somewhat limited.
> 
> @oharboe where does this 4x come from?

Any time you click in the heatmap GUI, the screen is rerendered; I need 4 clicks. Every time I change the min max number by a single digit, e.g. from 0 to 80, the screen is rerendered.

**Comment by maliberty** [comment]
I could see 2X
- Click to turn off one heat map
- Click to turn on another heat map

Where do the other two clicks go?

**Comment by oharboe** [comment]
> I could see 2X
> 
> * Click to turn off one heat map
> * Click to turn on another heat map
> 
> Where do the other two clicks go?

Configure, double click, change min max, enable legend, enable heat map.

**Comment by oharboe** [comment]
A generalized solution to #3278 would be a good first step to make working with bulky .odb files tolerable.
