### ISSUE TITLE
It is not possible to scroll to the leftmost letter of long port names

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3333]
### Description

There's text to the left that I can't see for ports with long names:

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/9240b746-45ee-45c7-a286-c031d14985d4)

Same for top, right and bottom.

### Suggested Solution

Allow scrolling far enough to read the entire portname.

**Comment by maliberty** [comment]
@gadfort do you have time to look at this?

**Comment by gadfort** [comment]
@maliberty if there is no urgency, sure, later this week I can

**Comment by maliberty** [comment]
I think that's fine as you can always see the name in the inspector

**Comment by maliberty** [comment]
@gadfort I'll give this to @AcKoucher unless you think you'll have time
