### ISSUE TITLE
Bottom leftmost port rendered width a left side arrow

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3334]
### Describe the bug

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/cc33e81f-7152-47d4-ba1c-821133523812)

### Expected Behavior

Should have a up/down arrow for ports on bottom

### Environment

```shell
latest master
```

### To Reproduce

@maliberty has the testcase data

**Comment by maliberty** [comment]
Fixed with #3337
