### ISSUE TITLE
Fallback of io constraints is placed at oposite sides of macros at top level

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3338]
### Description

When the io constraints fall back, because a full optimization is too time consuming, the leftmost position is used on the bottom of macro and rightmost positions are used on the top of the macro, which leads to a diagonal route:

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/d76755ca-a034-46db-8ae4-7724300fa7d4)

Another example of where placing the pins to the bottom left instead of bottom middle in the case of a fallback for placing a large group causes problems in placement. The pins at the bottom of the macro below are actually routed out of the macro. If the pins had been placed in the middle of the macro at the bottom of this macro, then this would have yielded a much better result in this case.

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/b364b311-ed5d-40c0-ad48-899815e6eed8)

### Suggested Solution

Place the pins in the middle of the assigned edge in the case of a fallback from full optimization.

Although it is possible to manually specify a range on the edge, this is incovenient during exploration where the dimensions of the design are in flux and we're iterating on finding a first cut reasonable floorplan.

**Comment by eder-matheus** [comment]
Is this happening during random pin placement or during the regular pin placement?

**Comment by eder-matheus** [comment]
@oharboe Could you try this: https://github.com/The-OpenROAD-Project/OpenROAD/pull/3374?

**Comment by oharboe** [comment]
> @oharboe Could you try this: #3374?

gui_floorplan, pins are not centered. That's not a requirement, but would have been nice: faster turnaround times.

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/8cf8695f-50ed-409d-84c4-4d7ec37586e5)

**Comment by eder-matheus** [comment]
Are they constrained to the edge? I have made a few tests with it and it was working on my end.

**Comment by oharboe** [comment]
> Are they constrained to the edge? I have made a few tests with it and it was working on my end.

Yes. The bottom pin constraints are:

```
set_io_pin_constraint -group -order -region bottom:* -pin_names ...
```

**Comment by oharboe** [comment]
Yes, this works!

gui_place gives the expected result, centered pins, at the bottom.

The only question that remains is whether you intended for pins to be centered already at the floorplanning stage...

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/128748ab-33c9-4df9-9c41-33a0448e68c9)

**Comment by eder-matheus** [comment]
> Yes, this works!
> 
> gui_place gives the expected result, centered pins, at the bottom.
> 
> The only question that remains is whether you intended for pins to be centered already at the floorplanning stage...
> 
> ![image](https://user-images.githubusercontent.com/2798822/240372422-128748ab-33c9-4df9-9c41-33a0448e68c9.png)

Yeah, this is supposed to work only on non-random pin placement. I will try to do the same for random placement and let you know when I'm done.

**Comment by eder-matheus** [comment]
@oharboe I believe that during the random mode, these large groups are not placed in fallback mode. Could you check the log file?

Also, having the fallback groups placed in the middle during the placement stage is enough for your usage?

**Comment by oharboe** [comment]
> @oharboe I believe that during the random mode, these large groups are not placed in fallback mode. Could you check the log file?

That does appear to be the case.

These warnings are only present in 3_2_place_iop.log

```
[WARNING PPL-0092] Pin group of size 2832 does not fit any section. Adding to fallback mode.
[WARNING PPL-0092] Pin group of size 1220 does not fit any section. Adding to fallback mode.
[WARNING PPL-0092] Pin group of size 579 does not fit any section. Adding to fallback mode.
[INFO PPL-0100] Group of size 2832 placed during fallback mode.
[INFO PPL-0100] Group of size 1220 placed during fallback mode.
[INFO PPL-0100] Group of size 579 placed during fallback mode.
```


> Also, having the fallback groups placed in the middle during the placement stage is enough for your usage?

Yes.

I think it looks good, looking forward to it being merged and using it :-)
