### ISSUE TITLE
Hunt down all locale specific C library usage and decide which should be locked to C locale

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3349]
### Describe the bug

strtof() is locale (human) oriented, if parsing computer formats and not facing humans, strtof_l() should be used.

See https://github.com/The-OpenROAD-Project/OpenROAD/discussions/3314

### Expected Behavior

Computer readable format should not be affected by locale

### Environment

```shell
master
```

### To Reproduce

See https://github.com/The-OpenROAD-Project/OpenROAD/discussions/3314

### Additional Context

Several functions in the C library are affected by the current locale settings. These functions handle character classification, string manipulation, and numeric formatting. Here are some common functions that are influenced by the locale:

Character Classification:

isalnum: Tests whether a character is alphanumeric.
isalpha: Tests whether a character is alphabetic.
isdigit: Tests whether a character is a decimal digit.
islower: Tests whether a character is a lowercase letter.
isspace: Tests whether a character is whitespace.
isupper: Tests whether a character is an uppercase letter.
tolower: Converts a character to lowercase.
toupper: Converts a character to uppercase.
String Manipulation:

strcoll: Compares two strings using collation rules.
strxfrm: Transforms a string using collation rules.
strtok: Breaks a string into tokens.
strtok_r: Thread-safe version of strtok.
Numeric Formatting and Parsing:

printf, fprintf, sprintf, snprintf: Formatting functions for printing to strings or files.
scanf, fscanf, sscanf: Input parsing functions.
strtod, strtof, strtold: String to floating-point conversion functions.
strtol, strtoll, strtoul, strtoull: String to integer conversion functions.
wcstod, wcstof, wcstold: Wide string to floating-point conversion functions.
wcstol, wcstoll, wcstoul, wcstoull: Wide string to integer conversion functions.
These functions, when influenced by the locale, take into account locale-specific settings such as character classification, collation order, numeric separators, decimal point symbols, and thousands separators.

To control the locale settings, you can use the functions setlocale and newlocale from the <locale.h> header. These functions allow you to set the locale for the entire program or create locale objects for specific purposes.

It's important to note that the specific functions affected by locale may vary slightly depending on the C library implementation and the platform you're working on.

**Comment by maliberty** [comment]
We override the locale to avoid doing this.  See my comments in https://github.com/The-OpenROAD-Project/OpenROAD/discussions/3314

**Comment by QuantamHD** [comment]
I disagree on closing this Matt. We can slowly transition.

**Comment by QuantamHD** [comment]
Here's all the usages of strof in OpenROAD

<img width="724" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD/assets/3784748/a99ba364-75e1-4f99-9bcc-d06234f822ac">

**Comment by maliberty** [comment]
I consider this very low priority but am glad to leave it open if you want to work on it.  Good luck with sta/...

**Comment by oharboe** [comment]
@maliberty If there is a strong motivation to fix this, then it will be fixed, no need to track this issue.
