### ISSUE TITLE
Update Build.md for instructions on enabling ASAN

### ISSUE THREAD

**Issue by Iyury1** [The-OpenROAD-Project/OpenROAD#3433]
### Description

A new CMake build argument was added by #3427. The variable ASAN enables building OpenROAD with Address Sanitizer. The  build instructions in OpenROAD/docs/user/Build.md does not mention this new variable. 

### Suggested Solution

Append to Build.md a short section explaining how to use this variable:

### Build with Address Sanitizer
To enable building with Address Sanitizer, use the argument `-DASAN=ON`. Setting the `ASAN` variable to `ON` adds necessary compile and link options for using Address Sanitizer.

> **Note:** Address Sanitizer adds instrumentation for detecting memory errors. Enabling this option will cause OpenROAD to run slower and consume more RAM.

**Comment by maliberty** [comment]
Do you want to make a PR for the doc update?
