### ISSUE TITLE
Resizer repair_design -max_wire_length

### ISSUE THREAD

**Issue by agorararmard** [The-OpenROAD-Project/OpenROAD#353]
As the number of cells increases with the same wire_length, the resizer crashes with a segmentation fault. We posted a test case in the shared OpenLane/OpenRoad repo.

**Comment by maliberty** [comment]
In this test case you removed all the clock buffers from the .lib.  OpenSTA expects to be able to find a library port when it disconnects from a net.  Would you provide a less trimmed .lib?

We can work on a better message as well.
