### ISSUE TITLE
TritonCTS segmentation Fault

### ISSUE THREAD

**Issue by agorararmard** [The-OpenROAD-Project/OpenROAD#354]
TritonCTS always crashes with a segmentation fault at its first step. We posted a test case in the shared OpenLane/OpenRoad repo.

**Comment by maliberty** [comment]
This test case won't work as the first buffer specified in buf_list is removed from the trimmed.lib.  You can't do CTS without a liberty for the cell.  The on-the-fly characterization requires a liberty for delay.

We should have a better error handling in this case.

**Comment by maliberty** [comment]
The head of the openroad branch now fails with:
Error: No Liberty cell found for <...>.
