### ISSUE TITLE
OpenROAD slowdown when timing driven placement/CTS/routing is used. 

### ISSUE THREAD

**Issue by openroadie** [The-OpenROAD-Project/OpenROAD#3588]
### Describe the bug

>>>>>>>> I've noticed a significant slowdown in OpenROAD over the last two weeks.
>>>>>>>> I'm trying to narrow down what might be to blame.
>>>>>>>> But for reference two weeks ago our ZeroSOC example took:
>>>>>>>> v2.0-8780 - a7f84d55d849dd56b4b06b8e3ef36fb68ee500f5
>>>>>>>> Place: 02:46.110
>>>>>>>> CTS: 02:59.520
>>>>>>>> Route: 22:46.849
>>>>>>>>
>>>>>>>> Now:
>>>>>>>> v2.0-8997 - ffa127cb22da12c0fd1fe787e2119651cad06806
>>>>>>>> Place: 43:50.960 (a 21x slowdown)
>>>>>>>> CTS: 23:57.950 (a 11x slowdown)
>>>>>>>> Route: 17:53.140 (5 mins faster)

### Expected Behavior

The runtime should remain more or less the same as before. 

### Environment

```shell
N/A for now.
```

### To Reproduce

N/A for now

### Relevant log output

```shell
N/A for now
```

### Screenshots

N/A for now

cc: @maliberty @gadfort @louiic @tspyrou @vvbandeira

**Comment by openroadie** [comment]
![sc1](https://github.com/The-OpenROAD-Project/OpenROAD/assets/114895267/f4b975e1-04d6-4545-851f-42d1531e5dd5)

Here is a runtime comparison between the following SHAs:

a7f84d55d849dd56b4b06b8e3ef36fb68ee500f5
ffa127cb22da12c0fd1fe787e2119651cad06806

As you can see, the differences in runtime for various functions are comparable barring some noise.

**Comment by QuantamHD** [comment]
Can you get a linux perf profile for both runs, and then run them in [perf diff ](https://manpages.ubuntu.com/manpages/jammy/man1/perf-diff.1.html)?

The fact that both CTS and GPL have slowed down makes me think it's an STA related issue.

**Comment by openroadie** [comment]
@QuantamHD Please see screenshot above.

**Comment by openroadie** [comment]
@gadfort Try as I might, I just do not see any slowdown. I have tried the ZeroAsic design as well as ORFS asap7/aes and asap7/riscv32. I double checked that we are running timing driven placement for my runs and I am comparing the latest master against  3ec606c02

**Comment by gadfort** [comment]
@openroadie I'm still debugging my way through this since you don't see the same issue. I've discovered the issue is only present (atleast in my testing) with the padring present. If I don't call `connect_by_abutment` the slowdown appears to go away. The only thing that code is going is make sure a bunch of iterms are connected to nets.  I'm trying see if anything is happening that in that code that shouldn't. I'll update once I have more information.
