### ISSUE TITLE
support removing dont_touch in deltaDebug.py

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3616]
### Description

The `dont_touch` nets can contain significant confidential information.

### Suggested Solution

Although deltaDebug.py will work correctly on designs that have `dont_touch` after https://github.com/The-OpenROAD-Project/OpenROAD/pull/3614, it would be better if these nets can be removed entirely to whittle away confidential information.

Ref https://github.com/The-OpenROAD-Project/OpenROAD/issues/3609#issuecomment-1633157986, I believe what is needed is to create a test-case and verify that the commented out code below doesn't crash.

```
$ git diff
diff --git a/src/odb/src/db/dbITerm.cpp b/src/odb/src/db/dbITerm.cpp
index 92365272e..087c976e3 100644
--- a/src/odb/src/db/dbITerm.cpp
+++ b/src/odb/src/db/dbITerm.cpp
@@ -526,23 +526,23 @@ void dbITerm::disconnect()
     return;
 
   _dbInst* inst = iterm->getInst();
-  if (inst->_flags._dont_touch) {
-    inst->getLogger()->error(
-        utl::ODB,
-        370,
-        "Attempt to disconnect iterm of dont_touch instance {}",
-        inst->_name);
-  }
+  // if (inst->_flags._dont_touch) {
+  //   inst->getLogger()->error(
+  //       utl::ODB,
+  //       370,
+  //       "Attempt to disconnect iterm of dont_touch instance {}",
+  //       inst->_name);
+  // }
 
   _dbBlock* block = (_dbBlock*) iterm->getOwner();
   _dbNet* net = block->_net_tbl->getPtr(iterm->_net);
 
-  if (net->_flags._dont_touch) {
-    inst->getLogger()->error(utl::ODB,
-                             372,
-                             "Attempt to disconnect iterm of dont_touch net {}",
-                             net->_name);
-  }
+  // if (net->_flags._dont_touch) {
+  //   inst->getLogger()->error(utl::ODB,
+  //                            372,
+  //                            "Attempt to disconnect iterm of dont_touch net {}",
+  //                            net->_name);
+  // }
 
   for (auto callback : block->_callbacks)
     callback->inDbITermPreDisconnect(this);
diff --git a/src/odb/src/db/dbNet.cpp b/src/odb/src/db/dbNet.cpp
index 45030a3a5..73dbe6c81 100644
--- a/src/odb/src/db/dbNet.cpp
+++ b/src/odb/src/db/dbNet.cpp
@@ -2941,8 +2941,8 @@ void dbNet::destroy(dbNet* net_)
   _dbBlock* block = (_dbBlock*) net->getOwner();
 
   if (net->_flags._dont_touch) {
-    net->getLogger()->error(
-        utl::ODB, 364, "Attempt to destroy dont_touch net {}", net->_name);
+    // net->getLogger()->error(
+    //     utl::ODB, 364, "Attempt to destroy dont_touch net {}", net->_name);
   }
 
   dbSet<dbITerm> iterms = net_->getITerms();
@@ -2979,12 +2979,12 @@ void dbNet::destroy(dbNet* net_)
   }
 
   if (block->_journal) {
-    debugPrint(block->getImpl()->getLogger(),
-               utl::ODB,
-               "DB_ECO",
-               1,
-               "ECO: destroy net, id: {}",
-               net->getId());
+    // debugPrint(block->getImpl()->getLogger(),
+    //            utl::ODB,
+    //            "DB_ECO",
+    //            1,
+    //            "ECO: destroy net, id: {}",
+    //            net->getId());
     block->_journal->beginAction(dbJournal::DELETE_OBJECT);
     block->_journal->pushParam(dbNetObj);
     block->_journal->pushParam(net->getId());
```

**Comment by maliberty** [comment]
Some problems might require the dont touch in order to reproduce.  We could have an option to remove the dont touch status.

**Comment by oharboe** [comment]
> Some problems might require the dont touch in order to reproduce. We could have an option to remove the dont touch status.

Default should be to remove as much as possible, I think.

I think the primary concern of deltaDebug.py is confidentiality. Certainly there are size optimizations that are not done and make foo_issue includes.pretty much everything...

**Comment by maliberty** [comment]
The primary concern is to reproduce the problem first.  The script was written for reducing problems for faster debug.  Confidentiality wasn't even a consideration at that time.

**Comment by oharboe** [comment]
> The primary concern is to reproduce the problem first. The script was written for reducing problems for faster debug. Confidentiality wasn't even a consideration at that time.

I see. So to support this workflow for confidentiality purposes is indeed a feature request.

**Comment by maliberty** [comment]
Making the design smaller serves both purposes though.  I'll send a PR for you test and see if it can reduce further.

**Comment by maliberty** [comment]
@oharboe please try https://github.com/The-OpenROAD-Project/OpenROAD/pull/3623 and see if it works better at reducing your test case

**Comment by oharboe** [comment]
> @oharboe please try #3623 and see if it works better at reducing your test case

Seems to work well :-)
