### ISSUE TITLE
make write_lef and others write out files atomically

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3658]
### Description

A half-written .lef file can be lying around after a crash which complicates e.g. `deltaDebug.py`.

Suggestion:

1. modify all `write_*` commands to write to a temp file
2. when the write completes, rename temp file to final name

This way there are no partial files lying around

**Comment by annapetrosyan26** [comment]
Hello @maliberty @oharboe , I'd like to work on this issue. Could you please assign it to me ?

**Comment by oharboe** [comment]
@annapetrosyan26 You can simply create a pull request without being assigned this task, I don't have the role to assign github issues in this project.

I haven't seen that @maliberty assigns github issues to new contributors, but perhaps that's something that would be approperiate?

**Comment by annapetrosyan26** [comment]
Thank you @oharboe for the clarification. Then I'll work on the issue and once the code is ready I will create a pull request.

**Comment by oharboe** [comment]
@maliberty Fixed, no?

**Comment by maliberty** [comment]
Fixed in https://github.com/The-OpenROAD-Project/OpenROAD/pull/5109
