### ISSUE TITLE
Don't write unrequested report in check_placement

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#3727]
### Describe the bug

In check_placement the code has:
```
  set file_name "failures_report.json"
  if { [info exists keys(-report_file_name) ] } {
    set file_name $keys(-report_file_name)
  }
```
This means failures_report.json is dumped in the working directory whenever no report is requested.  

### Expected Behavior

Please change this to not write anything if -report_file_name is not used.

### Environment

```shell
head of master
```

### To Reproduce

as above

**Comment by maliberty** [comment]
@eder-matheus FYI

**Comment by maliberty** [comment]
aside: please also make an ORFS PR to use -report_file_name

**Comment by maliberty** [comment]
@mina1460 eta?

**Comment by mina1460** [comment]
@maliberty 
today
