### ISSUE TITLE
Right click on timing path and inject OpenSTA command to report that path

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3739]
### Description

Today I have to manually type up the report_checks command for a timing path if I want to drill down for more information or create some variant.

### Suggested Solution

It would be nice to be able to right click on a path and have an OpenSTA command injected into the console that the user can then refine.

**Comment by AcKoucher** [comment]
@oharboe So the idea is that, when right clicking a selected path in Timing Report, the command should be "written" in the scripting widget's TCL commands space for the user to refine? Or the report_checks which corresponds to the right clicked path should run directly in the console?

**Comment by oharboe** [comment]
> @oharboe So the idea is that, when right clicking a selected path in Timing Report, the command should be "written" in the scripting widget's TCL commands space for the user to refine?

Yes.

**Comment by AcKoucher** [comment]
Something like:
`report_checks -from <start> -to <end>`

would be enough?

**Comment by oharboe** [comment]
> Something like: `report_checks -from <start> -to <end>`
> 
> would be enough?

yes. though i would add all the fields and options so the user can just delete what he doesnt need or want.

This is "marketing" of the underlying fearure as well as convenience.

**Comment by maliberty** [comment]
You'll want -path_delay (min|max) depending on the tab.  Also "-fields {slew cap input nets fanout} -format full_clock_expanded" are closer to what the GUI shows.
