### ISSUE TITLE
seems like a typo in module par. please check!

### ISSUE THREAD

**Issue by Steven89Liu** [The-OpenROAD-Project/OpenROAD#3828]
### Describe the bug

https://github.com/The-OpenROAD-Project/OpenROAD/blob/83770be334d117a755f6e1a3f3a8e4cd332b8191/src/par/src/TritonPart.cpp#L1824

### Expected Behavior

it should call the GetLowerVertexBalance().

### Environment

```shell
by code review.
```

### To Reproduce

by code review.

**Comment by vvbandeira** [comment]
@ZhiangWang033 could you take a look?

**Comment by maliberty** [comment]
Thanks - this looks like a clear copy-paste error.
