### ISSUE TITLE
Render labels on top of the macro instead of to the left when zoomed out

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3829]
### Description

open floorplan.odb in the GUI, zoom in/out.

zoomed out, the labels are to the left of the macros in some cases, but not all:

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/ea1224de-ff25-4298-886d-4dfeae5a4679)

[floorplan_microwatt_sky130hd_base_2023-08-09_13-52.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/12302250/floorplan_microwatt_sky130hd_base_2023-08-09_13-52.tar.gz)

**Comment by gadfort** [comment]
@oharboe this is probably a result of your change for the centering.

**Comment by oharboe** [comment]
> @oharboe this is probably a result of your change for the centering.

I need a bit of help of deciphering all the rotations, translations and coordinate systems there...

**Comment by gadfort** [comment]
you are adding a positive xOffset in one case and negative in the other?
It also looks like the text is not really centered (slight below the center and slightly to the left of center).

**Comment by gadfort** [comment]
@oharboe I don't know if I have time today to help

**Comment by oharboe** [comment]
> @oharboe I don't know if I have time today to help

No rush for my part and I don't think anyone else either... I just wanted to get a reproducible test-case registered with this issue so it could be attended to in due time.

The current implementation works quite well.

I think it is struggling when the labels are long and the centering could be improved.

**Comment by stefanottili** [comment]
I personally don’t think 90 degree rotated instance names are very readable and hope there are no upside down ones.
Luckily few technologies allow 90 degree rotations these days.

**Comment by maliberty** [comment]
@stefanottili there are some macros that are tall and thin where rotation is the only useful orientation.  We could vary the threshold.

The label rotation is a function of the macro bounds and is never upside down or backwards.
