### ISSUE TITLE
Add ability to drag the view with the mouse

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3840]
It would make moving around the design a lot easier.

The arrow keys is a bit clunky compared to dragging the view with the mouse.

_Originally posted by @oharboe in https://github.com/The-OpenROAD-Project/OpenROAD/discussions/3812_

**Comment by AcKoucher** [comment]
To be sure, drag should be triggered by shift+leftmouse?

**Comment by oharboe** [comment]
> To be sure, dragging should be triggered by shift+leftmouse?

I don't know what recommendation to make here.... Something that isn't surprising for users of other EDA tools... Whatever that is...

For my part shift+leftmouse would work for me, if I could see or find in the GUI this combination...

**Comment by maliberty** [comment]
in klayout it is the middle mouse button that does drag
