### ISSUE TITLE
TritonCTS: multiple cell names in variable CTS_BUF_CELL cause segmentation fault

### ISSUE THREAD

**Issue by gkamendje** [The-OpenROAD-Project/OpenROAD#389]
Having multiple cell names in the variable CTS_BUF_CELL causes TritonCTS to crash with segmentation fault. 
With multiple cell names in this variable, the call 
`odb::dbMaster* master = _db->findMaster(inst.getMaster().c_str());`
on line 329 of file OpenROAD/src/TritonCTS/src/DbWrapper.cpp returns a null pointer.This null pointer is passed to the function `odb::dbInst::create `
`odb::dbInst::create (block_=0x14eaddf8, master_=0x0, name_=0x7ffffffec830 "clkbuf_0_clk")`
and the line 1228     _dbInstHdr* inst_hdr = block->_inst_hdr_hash.find(master->_id); in file 
OpenROAD/src/OpenDB/src/db/dbInst.cpp causes a segmentation fault. 
I think a check should be built in to ensure that this variable has only one cell name. 

By the way, while looking at the code I noticed the following inefficiencies:

https://github.com/The-OpenROAD-Project/OpenROAD/blob/2f8a74e18004f12a48a38f98689b66d9fdc8db0e/src/TritonCTS/src/DbWrapper.cpp#L113-L118

The function `getNumClocks()` is called 3 times instead of calling once, saving the return value in a variable and subsequently using the variable later in the code.

**Comment by maliberty** [comment]
We will address the crash.  The "inefficiency" is unimportant as the function is trivially inlined by the compiler:

        unsigned getNumClocks() const { return _numberOfClocks; }
