### ISSUE TITLE
Make antenna checker understand global route format

### ISSUE THREAD

**Issue by eder-matheus** [The-OpenROAD-Project/OpenROAD#3892]
### Description

When evaluating the global routing results for antenna violations, we translate the global route format (i.e., global segments) to actual wires, having to create local connections with the pins.

This translation sometimes has issues, leading to crashes, specifically on the `odb::orderWires` function.

### Suggested Solution

The antenna checker tool should be able to understand the global route format, removing the necessity of translating the global route to wires. This would remove a large piece of code that performs the translation, remove the calls for `odb::orderWires`, and basically would simplify the process of checking antenna violations on the global route results.

A suggested approach is to use boost::polygon to create the routing topology from the wires. With that, orderWires would not be needed at all, and the antenna checker would traverse only through the boost::polygon structure.

### Additional Context

I'm not 100% sure if supporting the global route format in the antenna checker is possible. Any input on potential problems this could lead will be appreciated.

**Comment by maliberty** [comment]
I think this is possible. Antenna checking just needs a topology and metal area attached.

**Comment by openroadie** [comment]
@maliberty : We discussed it in the weekly meeting and I was going to take a look since @eder-matheus has some other higher priority items on his list.

**Comment by maliberty** [comment]
In https://github.com/The-OpenROAD-Project/OpenROAD/pull/4673 I've accepted some degradation in sky130hs/aes that originates from a new detour leading to more antenna fixing.  Once the antenna fixing is improved please see if this design is improved.  Currently there are some odd antennas on the driver side.
