### ISSUE TITLE
Error when I compile the flow folder in the image.

### ISSUE THREAD

**Issue by ybai62868** [The-OpenROAD-Project/OpenROAD#390]
When I **docker run -it openroad/flow image** and **cd** to flow folder to use **make** to help me compile.
I got the following information:
---
Design area 25593 u^2 100% utilization.
0:00.83elapsed 100%CPU 60784memKB
mkdir -p ./objects/nangate45/gcd
sed 's,<lef-files>.*</lef-files>,<lef-files>/OpenROAD-flow/flow/platforms/nangate45/lef/NangateOpenCellLibrary.tech.lef</lef-files> <lef-files>/OpenROAD-flow/flow/platforms/nangate45/lef/NangateOpenCellLibrary.macro.mod.lef</lef-files>,g' platforms/nangate45/FreePDK45.lyt > objects/nangate45/gcd/klayout.lyt
(/usr/bin/time -f "%Eelapsed %PCPU %MmemKB" klayout -zz -rd design_name=gcd \
        -rd in_def=./results/nangate45/gcd/5_route.def \
        -rd in_gds="./platforms/nangate45/gds/NangateOpenCellLibrary.gds " \
        -rd out_gds=results/nangate45/gcd/6_1_merged.gds \
        -rd tech_file=./objects/nangate45/gcd/klayout.lyt \
        -rm ./util/def2gds.py) 2>&1 | tee ./logs/nangate45/gcd/6_1_merge.log
/usr/bin/time: cannot run klayout: No such file or directory
0:00.00elapsed 88%CPU 1196memKB
make: *** [results/nangate45/gcd/6_1_merged.gds] Error 127
---
I can't find the gds file which is generated by the openroad.
Do you know how to solve it? Thanks a lot!

**Comment by maliberty** [comment]
The problem is : cannot run klayout

Did you use the Dockerfile from OpenROAD-flow?  It should have installed it:

yum localinstall https://www.klayout.org/downloads/CentOS_7/klayout-0.26.4-0.x86_64.rpm -y
