### ISSUE TITLE
Update io placement to have an option to output the placement to a .tcl file

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3909]
### Description

I'm using routing by abutment for two different macros that need to have the same pin-layout.

If I use `PLACE_PINS_ARGS=-annealing`, I get different pin layout for these two macros.

### Suggested Solution

Add option to io placement to write out the pin-placement to a .tcl file. This .tcl file can then be fed into the second macro and pin layout will be identical.

Furthermore, it would be great to have the pins in this file grouped by edges (generate a comment to indicate edge). This would allow using a combination where only one edge is copy and pasted from an io placement annealing run.

Another use-case for this .tcl file is to write out best found solutions for long running io placement efforts. The user can then hand-tweak the best result.

There should be some sort of output for long running io placement efforts.

Ideally the io placement would print out a recommendation to improve convergence speed, like "reduce number of pins on left edge by 10%", or something.

**Comment by eder-matheus** [comment]
@oharboe If it is guaranteed that the two different macros have the same track positions, we can use the `place_pin` command for each IO pin of the design. So the output .tcl file would be a list of calls for the `place_pin` command, like this:

```
place_pin -pin_name pin0 -layer layer -location "x0 y0"
place_pin -pin_name pin1 -layer layer -location "x1 y1"
...
place_pin -pin_name pinN -layer layer -location "xN yN"
```

We could easily group the pins by edge in this format. The only problem is that this file can be huge with one line per pin, but I think this is not a blocker.

About the output for long runtime, do you think an `-timeout` option could help? The annealing run would end after reaching the timeout, and the current result would be the final assignment, followed by a warning message and the suggestion of a new configuration for the constraints.

**Comment by oharboe** [comment]
> @oharboe If it is guaranteed that the two different macros have the same track positions, we can use the `place_pin` command for each IO pin of the design. So the output .tcl file would be a list of calls for the `place_pin` command, like this:
> 
> ```
> place_pin -pin_name pin0 -layer layer -location "x0 y0"
> place_pin -pin_name pin1 -layer layer -location "x1 y1"
> ...
> place_pin -pin_name pinN -layer layer -location "xN yN"
> ```
> 
> We could easily group the pins by edge in this format.

:+1: 

This would allow me to cut and paste some pins for my use-case and also to use the annealing.

> The only problem is that this file can be huge with one line per pin, but I think this is not a blocker.

Size doesn't really matter here, no. It's thousands of lines for thousands of pins. That's easily understood.


> 
> About the output for long runtime, do you think an `-timeout` option could help? The annealing run would end after reaching the timeout, and the current result would be the final assignment, followed by a warning message and the suggestion of a new configuration for the constraints.

I think perhaps an "effort" similar to detailed routing/global routing would make sense. I'm thinking this default should be something reasonable, like minutes and then the user can bump it up. The results should be idempotent, so it shouldn't matter how fast your CPU is.

**Comment by eder-matheus** [comment]
> > @oharboe If it is guaranteed that the two different macros have the same track positions, we can use the `place_pin` command for each IO pin of the design. So the output .tcl file would be a list of calls for the `place_pin` command, like this:
> > ```
> > place_pin -pin_name pin0 -layer layer -location "x0 y0"
> > place_pin -pin_name pin1 -layer layer -location "x1 y1"
> > ...
> > place_pin -pin_name pinN -layer layer -location "xN yN"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We could easily group the pins by edge in this format.
> 
> 👍
> 
> This would allow me to cut and paste some pins for my use-case and also to use the annealing.
> 
> > The only problem is that this file can be huge with one line per pin, but I think this is not a blocker.
> 
> Size doesn't really matter here, no. It's thousands of lines for thousands of pins. That's easily understood.
> 
> > About the output for long runtime, do you think an `-timeout` option could help? The annealing run would end after reaching the timeout, and the current result would be the final assignment, followed by a warning message and the suggestion of a new configuration for the constraints.
> 
> I think perhaps an "effort" similar to detailed routing/global routing would make sense. I'm thinking this default should be something reasonable, like minutes and then the user can bump it up. The results should be idempotent, so it shouldn't matter how fast your CPU is.

Sounds good. I will address this issue in two PRs, starting with the .tcl file with the IO placement and then another PR for the long runtimes.
