### ISSUE TITLE
DRT-0418 "no pins on routing grid" for a pin that's covered by 6 routing tracks

### ISSUE THREAD

**Issue by stefanottili** [The-OpenROAD-Project/OpenROAD#3928]
### Describe the bug

[WARNING DRT-0418] Term inst143924/Q1[3] has no pins on routing grid

but the pin is accessible from at least 6 routing tracks

<img width="309" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD/assets/25827408/61ed82d8-5bd5-4cf2-9b8f-085ec55c6b72">

### Expected Behavior

no warning

### Environment

```shell
M1 MacBook Ventura
OpenROAD v2.0-10072-g70db1404a (Aug 29 2023)
```

### To Reproduce

read_lef ispd19_test6/ispd19_test6.input.lef.gz
read_def ispd19_test6/ispd19_test6.input.def.gz
set_thread_count 8
set_routing_layers -signal Metal2-Metal9 -clock Metal2-Metal9
set_global_routing_layer_adjustment Metal2-Metal9 0.5
#global_route -verbose
read_guides ispd19_test6/ispd19_test6.guide 
detailed_route -output_drc 5_route_drc.rpt -verbose 1
write_db route.db
exit

**Comment by rovinski** [comment]
I think the problem is that the warning is issued when the center of a pin doesn't lie on a routing track. The warning doesn't change any behavior of detailed route so it can safely be ignored, but it indicates that the check needs to be refined a little more.
