### ISSUE TITLE
[WARNING PPL-0036] Number of sections is 1404 while the maximum recommended value is 600 this may negatively affect performance.

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3933]
### Description

Improve error message. What is a "section" and how does it relate to floorplan area?

### Suggested Solution

The error message should give some actionable advice, like "increase area such that width + height is n% greater" or somesuch.

**Comment by maliberty** [comment]
Is this with the old ppl?

**Comment by oharboe** [comment]
> Is this with the old ppl?

Yes. The error is correct, the area is too small(not enough space on the edges).

This feature request is about.making the error more immediately actionable.

**Comment by eder-matheus** [comment]
@oharboe Could you share the complete PPL log? I want to understand the flow of messages you're having in this design.

**Comment by oharboe** [comment]
I will reopen if I have the complete logs.
