### ISSUE TITLE
set_domain_area floorplan not fit into GUI

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenROAD#4014]
### Describe the bug

I've executed the [upf_test.tcl](https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/ifp/test/upf_test.tcl) with ifp test case.
The power domain area seems not fit into OpenROAD gui.

![upf_test_ifp_issue](https://github.com/The-OpenROAD-Project/OpenROAD/assets/85787913/bb8f1d04-d1ba-4943-81cb-87d89ee89a6d)

### Expected Behavior

Fit all relevant db into OpenROAD gui.

### Environment

```shell
With latest master
```

### To Reproduce

```
cd src/ifp/test
openroad upf_test.tcl
```

**Comment by maliberty** [comment]
I think it is just a poorly constructed test case as having objects outside the die area doesn't make much sense.   Perhaps that should just be an error at the end of ifp.

**Comment by gadfort** [comment]
@maliberty what would the error condition be? the power domain is defined before the floorplan.

**Comment by maliberty** [comment]
@gadfort the error would be from the end of initialize_floorplan that there are objects (here regions) outside the die area

**Comment by gadfort** [comment]
does `initialize_floorplan` create the domain areas? If so, I would say yes (or initialize_floorplan  should scale correctly to get the domains included

**Comment by maliberty** [comment]
@gadfort it doesn't create them but they exist beforehand (at least in this test) so we can check them.

**Comment by rovinski** [comment]
Seems like it should definitely be an error somewhere.

**Comment by vijayank88** [comment]
@maliberty 
Is this resolved?

I am getting blank screen in GUI. Not able to reproduce this now.

**Comment by maliberty** [comment]
I fixed the test case.  If I turn on rows I see

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/761514/8784bf9d-064e-4b53-a2db-c0863cd96830)

**Comment by vijayank88** [comment]
@maliberty 
I've updated to latest master and ran the test case. If I load with `gui::show` it return empty.
Also can you help to restore OpenROAD gui with default background. I'm getting grey color background.
![upf_testcase](https://github.com/The-OpenROAD-Project/OpenROAD/assets/85787913/1bb525ae-c9d8-45a0-b093-1dbfdae9b2f8)

**Comment by maliberty** [comment]
I don't see the gray screen you describe:
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/761514/d8ceb039-7f82-43c9-ac0f-3ad6caee2932)

On what OS are you running?  What exact set of steps are you doing?

**Comment by vijayank88** [comment]
CentOS 7.. GCP machine..
Vitor have have access to that machine as admin.

**Comment by maliberty** [comment]
@vvbandeira please help me to get access to reproduce this issue.  I recall Seyi had something similar a while ago.

**Comment by vijayank88** [comment]
I checked with commit ID 46f712bf130726641921fca4b3a6f6940eb1061b and it's got resolved now.
