### ISSUE TITLE
zoom in/out to the position of the mouse in the view, not the view center

### ISSUE THREAD

**Issue by stefanottili** [The-OpenROAD-Project/OpenROAD#4033]
### Description

The current OpenRoad behavior is to zoom in/out of the center of the view.

It's much more useful when the point to zoom in or out to is determined by the position of the mouse cursor in the view.
This is the default behavior of klayout.

### Suggested Solution

"Zoom in window" is already using the mouse cursor to determine the new view coordinates by drawing the new view bounding box.
So using the mouse position for keyboard or mouse wheel zoom in/out instead of the view center should be fairly straight forward.

**Comment by maliberty** [comment]
It has always zoomed around the mouse point. If that's changed it is a new bug

**Comment by AcKoucher** [comment]
@stefanottili Zooming with Ctrl+Wheel already zooms in/out based on the cursor position.

So, to be clear, what is being reported here is that zooming in/out with keyboard should have the same behavior?

**Comment by stefanottili** [comment]
Yes

**Comment by maliberty** [comment]
That seems much less intuitive to me. When I navigate from the keyboard I don't expect the mouse to be involved

**Comment by stefanottili** [comment]
klayout's behavior is when you don't have the mouse in the layout view, use the center of the view for z/Z (zoom in/out).
if the mouse is in the layout view, zoom in/out at the mouse location. 
Which I find very intuitive.
klayout also doesn't require the ctrl-key to pressed to use the mouse wheel.
In that sense it doesn't require the keyboard to be involved when using the mouse to zoom.
And with fit and zoom out gesture (move mouse up right/up left) you really don't need the keyboard.

**Comment by stefanottili** [comment]
Thanks for working on this, but unfortunately it doesn't quite work as expected.

There seems to be some zoom out limit on the positioning of a chip in the view that get's in the way.

After a "fit" point the mouse cursor to the bottom right corner of the chip.
Hitting z to zoom in the expectation is that the point the cursor points to will stay under the cursor, 
so subsequent z will keep on zooming in on where the cursor points.

This only works once the zoom level reaches a certain point, but it should work on a full chip view too.

**Comment by AcKoucher** [comment]
This could be another issue, as this has to do with how the function that handles the zoom itself works. Zooming with mouse should result in the same problem.

**Comment by stefanottili** [comment]
How to proceed here ?
This feature request has been closed even though the feature doesn’t quite work for points at the edge of the view. The point the mouse is pointing to doesn’t stay under the cursor.
Am I supposed to create a new bug report ?

**Comment by maliberty** [comment]
The problem seems closely related so I'll reopen.  It does occur with the mouse as well.
