### ISSUE TITLE
Improve RTLMP so that it can lay out mock-array in an array

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4085]
### Description

unzip [rtlmp.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/12808850/rtlmp.zip)

```
$ ./run-me-mock-array-asap7-base.sh 
OpenROAD v2.0-10574-gd04de2f32 
[deleted]
```

Placement result, not an array:

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/775bdffe-011a-4ca8-be5e-df33800c2da5)

### Suggested Solution

Should result in an array.

**Comment by AcKoucher** [comment]
@oharboe What criteria should induce the 8x8 array centering in the die? The predominant criteria used for the mechanism used by mpl2 is wirelength, however moving the array inside the die doesn't affect it at all due to the symmetry.

**Comment by oharboe** [comment]
@AcKoucher @maliberty I dont know... We have discussed some sort of placement constraint language. Perhaps that is needed here to break the symmetry?

**Comment by AcKoucher** [comment]
@oharboe With the changes in #4704 and #4705 we'll be able to centralize mock-array by setting the boundary weight parameter in HierRTLMP to 0. Would that be acceptable?

The default functionality of mpl2 is to push macros away from the center which is exactly the opposite behavior of what we'd want here.

**Comment by oharboe** [comment]
@AcKoucher Sounds like a solid step forward.

@maliberty Any luck in getting.macro placement constraints articulated?
