### ISSUE TITLE
Error: cts.tcl, 110 couldn't execute "eqy": no such file or directory, asap7 jpeg

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4092]
### Describe the bug

Run: `./build_openroad --local --latest`

To reproduce:

```
$ make DESIGN_CONFIG=designs/nangate45/gcd/config.mk generate_abstract
[deleted]
OpenROAD v2.0-10646-g0dff30da2
[deleted]
[WARNING RSZ-0062] Unable to repair all setup violations.
[INFO RSZ-0033] No hold violations found.
Error: cts.tcl, 110 couldn't execute "eqy": no such file or directory
Command exited with non-zero status 1
Elapsed time: 0:03.21[h:]min:sec. CPU time: user 3.18 sys 0.02 (99%). Peak memory: 111884KB.
make[1]: *** [Makefile:669: do-4_1_cts] Error 1
make: *** [Makefile:669: results/nangate45/gcd/base/4_1_cts.odb] Error 2
```

### Expected Behavior

Should run to completion without error

### Environment

```shell
Git commit: e70606743bb66db93f0a918975bff23455ad16c5
kernel: Linux 6.2.0-32-generic
os: Ubuntu 23.04 (Lunar Lobster)
cmake version 3.25.1
```

### To Reproduce

See above

**Comment by oharboe** [comment]
@maliberty @vvbandeira I updated the testcase. No need for a giant download, happens with `make DESIGN_CONFIG=designs/nangate45/gcd/config.mk generate_abstract`

Works with `make DESIGN_CONFIG=designs/asap7/gcd/config.mk generate_abstract` though...

**Comment by maliberty** [comment]
@vvbandeira please update

**Comment by rovinski** [comment]
Both I and one of my students ran into this. I think one of the main problems is that there are default designs, e.g. nangate45/gcd, which have equivalence checking turned on. There either needs to be a check for whether `eqy` is actually installed, or `EQUIVALENCE_CHECK = 1` needs to be removed from designs.

**Comment by maliberty** [comment]
@vvbandeira perhaps we can just call eqy from Jenkins (as the default)

**Comment by kush-manchanda** [comment]
I had the same issue and had to follow the comment here https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1513#issuecomment-1741746622 to fix it. Thanks.

**Comment by maliberty** [comment]
This should be resolved once https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1751 is merged

**Comment by vvbandeira** [comment]
[#1751](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1751) was replaced by [#1754](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1754)

**Comment by vvbandeira** [comment]
@kush-manchanda 
Could you try again with the latest code? Please also make sure to `source env.sh` before running the flow if you used `sudo ./setup.sh` to install the dependencies.

**Comment by kush-manchanda** [comment]
@vvbandeira cloned it again and did the build locally. It worked fine.
