### ISSUE TITLE
Improve the router so WRAP_LEFS/LIBS is no longer needed

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4131]
From @rovinski:

"I would hazard that we don't want to develop that(WRAP_LEFS/LIBS) any further. The only point of the LEF wrapper was to shift macro pins to be on-grid because OR was having a lot of difficulty routing to off-grid pins in GF12. Further, it was a stop-gap (hacky) solution because of project deadlines.

Most technologies either 1) don't have that problem or 2) have a cleaner solution (e.g. simply move the pins on-grid). Development time would be better spent on a generalized solution inside the router if it is actually a problem."

_Originally posted by @rovinski in https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1561#issuecomment-1762361668_

**Comment by maliberty** [comment]
@osamahammad21 not top of priority list but good for when we have time
