### ISSUE TITLE
MPL2 is not properly snapping macros when using Nangate45 designs.

### ISSUE THREAD

**Issue by AcKoucher** [The-OpenROAD-Project/OpenROAD#4145]
### Describe the bug

Instead of aligning the pins according to the track-grid, the pins are getting slightly misplaced.

### Expected Behavior

Pins should be centralized according to the track-grid independently of the technology used.

### Environment

```shell
Head of Master
```

### To Reproduce

Run mpl2 in a nangate45 design with macro instances.

### Screenshots

nangate45/bp_be_top - fakeram45_512x64 - some pins in metal3.
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/104802710/9defdcdb-9beb-44ee-bbd2-bb5b768ddb6c)

**Comment by AcKoucher** [comment]
After taking a look at some of the pins of the macro `be_mmu/dcache/tag_mem.macro_mem.mem` in `nangate45/bp_be_top`, I realized it has a arrangement of pins which apparently makes impossible for mpl2 to snap it:

Left boundary pins in metal3 - `nangate45/bp_be_top`, macro `be_mmu/dcache/tag_mem.macro_mem.mem`
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/104802710/1d889dc3-cb62-46f1-9e23-24a7850f550b)


This also happens with some macros in nangate45/tinyRocket, e. g. `dcache/data.data_arrays_0.data_arrays_0_ext.mem`.

On the other hand, some macros which don't have this kind of arrangement (or which have pins that are much larger than the trackgrid pitch) aren't being correctly snapped as well. I'm investigating.

**Comment by maliberty** [comment]
It would be nice to find the position that snaps as many pins as possible as in the image above none are snapped.

What is the name of the block shown above?  Is it a fake ram?

**Comment by AcKoucher** [comment]
In the image: bp_be_top, and the macro is be_mmu/dcache/tag_mem.macro_mem.mem. It's a fake ram.

**Comment by AcKoucher** [comment]
However, in the case of the image, if we snap the lower and upper pins, the middle one (as many others) will be completely out of the track...

**Comment by maliberty** [comment]
Probably we should just fix the RAM to have its pins arranged so that snapping is possible.  Fakeram has been through various iterations of improvements.

**Comment by maliberty** [comment]
See https://github.com/ABKGroup/FakeRAM2.0

**Comment by rovinski** [comment]
At some point it might be prudent to create an IP checker which can more thoroughly check for bad implementations such as off-grid pins, wrong direction routing, etc.

**Comment by maliberty** [comment]
Those could be enhancements to check_placement
