### ISSUE TITLE
project for synthesis

### ISSUE THREAD

**Issue by ripudamank2** [The-OpenROAD-Project/OpenROAD#4158]
### Description

Hi,
1. Can you please provide a link to some more IPs or projects which I can use to do full ASIC flow and do some optimization for my learning.
 2. Can you please let me know which open source tool is similar to ModelSim because i also want to see simulation result before synthesis ? 
 
 Thank you

**Comment by maliberty** [comment]
1. https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts has various designs you can run
2. https://www.veripool.org/verilator/
