### ISSUE TITLE
Add router support for WRONGDIRECTION SPACING

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#4179]
### Description

Add router support for the LEF construct:
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/761514/7a2b4615-060d-4811-b53f-baec906d9ba1)

### Suggested Solution

Update gc and possibly dr.

**Comment by refaay** [comment]
Rule supported by merging PR #4303
