### ISSUE TITLE
Create a pass that reads in all macros and writes out io pin constraint files for all macros at top level

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4197]
### Description

@louiic I have MegaBoom set up with asap7, but it fails in global routing of the top level.

The problem appears to be mainly that the pins are on the wrong sides of the macro.

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/97da5d88-c569-45e7-873a-c8ff712e74b2)

### Suggested Solution

Add a command that can be run at the top level floorplan to create io pin placement constraint files for all the macros.

**Comment by louiic** [comment]
Will take a look

**Comment by oharboe** [comment]
Other than IO pin constraints, I was looking at the routing congestion.

From the global routing routing congestion heatmap and drilling down, I can see that the buffer tree that is having a lot of congestion is the `RegisterRead_1 iregister_read`


![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/1c7e6634-65a8-4d54-a9e0-6fbdab1ecbbc)

**Comment by oharboe** [comment]
Here I can see which areas fail in global routing:

1. hold cell violations
2. around the ALU units that are not pulled out as macros.

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/7f966a8d-751f-45ab-8388-df3337117f32)


![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/9d971db3-655d-4634-b0a2-4b81988b5ee5)
