### ISSUE TITLE
Recommend possible values for [ERROR PPL-0111] 1 constraint(s) does not have available slots for the pins.

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4208]
### Description

It would be nice if the tool could recommend possible changes to allow placing the pins:

```
Using 2 tracks default min distance between IO pins.
[WARNING PPL-0110] Constraint has 881 pins, but only 802 available slots
[ERROR PPL-0111] 1 constraint(s) does not have available slots for the pins.
Error: io_placement_random.tcl, 14 PPL-0111
Command exited with non-zero status 1
```

### Suggested Solution

For instance, if the error message would pick any two of CORE_UTILIZATION, PLACE_DENSITY, CORE_ASPECT_RATIO and print out the third value.

**Comment by eder-matheus** [comment]
For this specific error, it is more related to the region defined by the user than to a design characteristic. I could add an estimative of how many microns the region should be increased to fit all the constrained pins.

However, other error messages in PPL could be enhanced to suggest changes in the design. I'll look into it.
