### ISSUE TITLE
don't write congestion map outside of the routing layers

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#4253]
### Description

I noticed in asap7 that although the min routing layer is M2 we still write out useless congestion map data for M1 into odb.  All the entries are 0.

### Suggested Solution

Skip writing outside of min/max layers

**Comment by maliberty** [comment]
@eder-matheus why was this re-opened?

**Comment by eder-matheus** [comment]
I had to revert my change due to some failures in the CI. I haven't had the chance to get back to it yet.
