### ISSUE TITLE
floorplan.tcl does not identify macros - [WARNING ODB-0208] VIA: duplicate VIA (via5_6_120_288_1_2_58_322) ignored...

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4306]
### Describe the bug

After #4302 was merged, I still get this warning below:

To reproduce unzip https://drive.google.com/file/d/1ymXux_59zURs7Fh35NxYGcnBvkOe8YeN/view?usp=sharing

```
./run-me-BoomTile-asap7-base.sh
```

Output:

```
OpenROAD v2.0-11160-g0728be75e
[deleted]
[WARNING ODB-0208] VIA: duplicate VIA (via5_6_120_288_1_2_58_322) ignored...
[deleted]
```

### Expected Behavior

no error

### Environment

```shell
OpenROAD v2.0-11160-g0728be75e
```

### To Reproduce

See above.

**Comment by maliberty** [comment]
I suppose this is because you have multiple block abstracts with the same via.  We could lower it to an info.

**Comment by oharboe** [comment]
> I suppose this is because you have multiple block abstracts with the same via. We could lower it to an info.

What will the user do with this information?

Who needs to know and why?

**Comment by rovinski** [comment]
A user could have typos or copy/paste errors. Vias that were meant to be different could accidentally have the same name.

**Comment by oharboe** [comment]
@maliberty I no longer see it, close?
