### ISSUE TITLE
global routing congestion.rpt has DRC markers in a strange place

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4391]
### Describe the bug

unzip  https://drive.google.com/file/d/1UrcL0WPXG9tJhBQ_GT3r_GvVwRsrH-ic/view?usp=sharing , start OpenROAD GUI, load 4_cts.odb, then load the congestion.rpt file.

Why are the DRC markers (white x's) at the top and not in the middle of the congested area?

To re-run global routing `$ ./run-me-BoomTile-asap7-base.sh`

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/29f6f8fb-4fa4-4c5a-9d12-26a3bd5be40f)

### Expected Behavior

Congestion markers in the middle of the congested area, not at the edge of the design.

### Environment

```shell
OpenROAD v2.0-11454-g34687e2a9
```

### To Reproduce

See above

**Comment by maliberty** [comment]
Would you zoom in on the area with the markers and post the image.  When zoomed way out we use a X to make things visible.  There could be congestion near the edge of the block.

**Comment by oharboe** [comment]
> Would you zoom in on the area with the markers and post the image. When zoomed way out we use a X to make things visible. There could be congestion near the edge of the block.

I no longer have this available on my computer, but using the reproduction case here you can. I didn't see anything there though, the area looked empty. There were square DRC congestion boxes at the top edge.

**Comment by eder-matheus** [comment]
@oharboe I've run GRT with the files you've attached, and the congestion markers generated in this run are not the same as the one you attached:
<img width="729" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD/assets/43450810/dfd1aab4-815e-406e-8c55-1ef0b456d598">

Is it possible that you loaded a different congestion report file by mistake?

**Comment by oharboe** [comment]
entirely...
