### ISSUE TITLE
Tab completion does not work for all commands with `make open_cts`

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4416]
### Description

Opening OpenROAD in console mode is very useful when working with large designs and logging into remote machines, however tab completion does not work as well:

- Run `make open_cts`
- type `report_`, hit tab, alternatives are shown
- type `report_clock`, hit tab. The alternatives for report_clock are not shown.

Alternatives for `report_clock` in the GUI:

![Screenshot_2023-12-20_07-05-36](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/aac9bb8f-787d-4737-a17f-c23d27a40eaf)

### Suggested Solution

Make tab completion work as well in console mode as GUI mode.

**Comment by maliberty** [comment]
The GUI is custom qt code and not applicable to the console.  We rely on tclreadline there which apparently doesn't work well with imported namespaced:

```
openroad> sta::report_cl
sta::report_clk_infos          sta::report_clock_properties
sta::report_clk_skew           sta::report_clock_skew
sta::report_clock1             sta::report_clock_skew_metric
sta::report_clock_min_period   
```
works fine but 
```
openroad> report_cl
```
produces nothing despite having done ```namespace import sta::*``` at startup.  This seems to be more of a tclreadline issue than OR so I'm not clear on how to resolve it.

**Comment by oharboe** [comment]
@maliberty I see....

**Comment by oharboe** [comment]
Reopen if there this feature request can come with some sort of idea on what to do about it...
