### ISSUE TITLE
Failed to fix all DRC errors in detailed routing

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4426]
### Describe the bug

This is from https://github.com/The-OpenROAD-Project/megaboom/commit/bd036b21c9217355c31a34a2a2ef41c049586a91

untar https://drive.google.com/file/d/1RQeOoC-Al2PHKsCDgaIlKjwMAQz-NTXK/view?usp=sharing

load into GUI and load DRC report

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/f1d381fa-0936-49b6-a0a9-1e1e617cc16a)

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/b9fbfb09-6f4b-496f-8e21-cfec4699a00a)

Route guides for net:

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/7a1432d9-47d2-404a-9af6-4bcddd2b87f7)

### Expected Behavior

No DRC errors

### Environment

```shell
OpenROAD v2.0-11553-gec214a37b
```

### To Reproduce

See above

**Comment by maliberty** [comment]
The guide looks to be very close to a macro where you can't legally drop a via.  @eder-matheus any thoughts on the guide?

**Comment by eder-matheus** [comment]
> The guide looks to be very close to a macro where you can't legally drop a via. @eder-matheus any thoughts on the guide?

Yeah, they look too close to the macro. I'll try the macro extension option to see if it resolves and will investigate how to improve our resource modeling to avoid such guides so near the macros.

**Comment by eder-matheus** [comment]
@oharboe Can you add a reproducible of this issue? Having only the final ODB for the routing will not be enough for debugging the global routing of this design.

**Comment by oharboe** [comment]
@eder-matheus I think you fixed this?
