### ISSUE TITLE
Add Charts even if qt charts is not installed, but with a text saying qt charts not installed

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4433]
### Description

If there are features that are invisible, because some dependency was not installed at compile time, how can the user know about them?

### Suggested Solution

Add Charts even if qt charts is not installed, but with a text saying qt charts not installed. This will tell users what features they are missing out on and think to look up the documentation to build OpenROAD correctly

**Comment by maliberty** [comment]
cmake does print a message but this is better marketing.

**Comment by rovinski** [comment]
Vim has a feature when running `:version` that displays all of the options it was compiled with. Perhaps something similar could be done with OR? Like `openroad --version` prints out

```
OpenROAD v2.0-11454-g34687e2a9
Features included (+) or not (-):
-charts -eqy +GPU +GUI +Python  ...
```

**Comment by maliberty** [comment]
> Vim has a feature when running `:version` that displays all of the options it was compiled with. Perhaps something similar could be done with OR? Like `openroad --version` prints out
> 
> ```
> OpenROAD v2.0-11454-g34687e2a9
> Features included (+) or not (-):
> -charts -eqy +GPU +GUI +Python  ...
> ```

This is a nice idea for text mode but should be a separate issue.
