### ISSUE TITLE
Add sorting on columns in hierarchy view

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4437]
### Description

It would be nice to be able to sort ascending/descending on e.g. area by clicking at the label of the column:

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/f009cd84-cf79-4b81-858d-13403449a910)

### Suggested Solution

Add sorting

**Comment by maliberty** [comment]
@AcKoucher I think there is a Qt option for sorting that just needs to be enabled.

**Comment by maliberty** [comment]
Fixed by https://github.com/The-OpenROAD-Project/OpenROAD/pull/4460
