### ISSUE TITLE
CUDD link failure for openroad

### ISSUE THREAD

**Issue by viyelesay** [The-OpenROAD-Project/OpenROAD#445]
When openroad is compiled with CUDD option, it fails at the link phase.
Can you add following code in the OpenRoad/src/CMakeLists.txt file to add cudd library during openroad link phase?

if (CUDD_LIB)
  target_link_libraries(openroad ${CUDD_LIB})
endif()

**Comment by jjcherry56** [comment]
097098c4 link CUDD_LIB if defined

**Comment by viyelesay** [comment]
Thanks

**Comment by tamimcse** [comment]
This fixes the error.
