### ISSUE TITLE
Detailed routing DRC violation that can be removed

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4478]
### Describe the bug

Toggling routing guides on/off, we can see that the routing guide is too tight. The net is forced too close to the macro.

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/9acc7e51-22d9-4cce-b930-97f5f78c1539)
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/5d74f5d0-c2cc-4df8-a086-23084c7114cd)

Later, a metal spacing DRC error can't be fixed:

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/a52f7411-6f3a-44f6-ab11-7485672511a1)

### Expected Behavior

Better routing guides so that detailed routing can work.

### Environment

```shell
OpenROAD v2.0-11638-g1a366db1e
```

### To Reproduce

1. untar https://drive.google.com/file/d/1sUksInXz7DYJ0fBVSh6JhqbaB5p4p-2x/view?usp=sharing
2. Run `./run-me-BoomNonBlockingDCache-asap7-base.sh`

**Comment by oharboe** [comment]
@maliberty Reproducible case where the routing guide is too close to the macro making it impossible in detailed routing to get away from the macro.

**Comment by oharboe** [comment]
> As a workaround you might try "set_macro_extension 2"

Thanks! 

I am not held up by this, I just provided this test case because, as I recall @eder-matheus was interested in a reproducible case

**Comment by eder-matheus** [comment]
Using the latest version of OpenROAD, the DRCs are being fixed. We had a couple of updates in GRT related to regions near macros that probably solved the issue you was facing with this design.
