### ISSUE TITLE
write_macro_placement writes out empty file

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4511]
### Describe the bug

```
$ make DESIGN_CONFIG=designs/asap7/mock-array/config.mk floorplan
[deleted]
$ make DESIGN_CONFIG=designs/asap7/mock-array/config.mk open_floorplan
[deleted]
OpenROAD v2.0-11723-gde78d0e07 
[deleted]
openroad> write_macro_placement test.tcl
openroad> 
$ cat test.tcl
$ ls -l test.tcl
$ wc -l test.tcl 
0 test.tcl
```

### Expected Behavior

Write out macro placement regardless of how the macros were placed: manually, classic mpl and mpl2.

### Environment

```shell
OpenROAD v2.0-11723-gde78d0e07
```

### To Reproduce

See above.

**Comment by maliberty** [comment]
@AcKoucher you could write this in terms of odb rather than mpl2 internals.  That way it will work regardless.

**Comment by AcKoucher** [comment]
@maliberty Could we do:

If mpl2 was used for macro placement, then, write_macro_placement should include only the macros placed by mpl2.
However, if another method was used, write_macro_placement should include all placed macros? In the latter we'd use odb..

?

**Comment by maliberty** [comment]
I think we can replace the flag with the command and have it cover all cases.  The flag can issue a deprecation warning to use the command instead.  The command itself can live in odb as it no longer depends on the placer.
