### ISSUE TITLE
Macro placement mirrors macros resulting in lots of global routing congestion

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4512]
Global routing failed after ca. 7000 seconds, but upon closer inspection the problem appears to be that macros are mirrored during mpl2, placing pins exactly oposite of optimal.

`make macro_place_issue` reproducible case for mpl2: 

1. untar https://drive.google.com/file/d/1ArnHkISZ-F0_qr0GlJM2dVr_XMszREYT/view?usp=sharing
2. Run command below

```
$ NUM_CORES=16 ./run-me-ChipTop-asap7-base.sh 
OpenROAD v2.0-11723-gde78d0e07 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
[INFO ORD-0030] Using 16 thread(s).
HierRTLMP Flow enabled...
rtl_macro_placer -halo_width 20 -report_directory bazel-bin/objects/asap7/ChipTop/base/rtlmp -write_macro_placement placement.tcl
Floorplan Outline: (0.0, 0.0) (1000.0, 1000.0),  Core Outline: (2.052, 2.16) (997.974, 997.92)
Traversed logical hierarchy
	Number of std cell instances: 1040149
	Area of std cell instances: 130485.91
	Number of macros: 12
	Area of macros: 128316.23
	Area of macros with halos: 233264.55
	Area of std cell instances + Area of macros: 258802.16
	Core area: 991699.31
	Design Utilization: 0.26
	Core Utilization: 0.15
	Manufacturing Grid: 1

openroad> write_macro_placement xxx.tcl
openroad> 
$ cat placement.tcl 
place_macro -macro_name system/bank.ram.mem_ext -location {22.052 960.048} -orientation MY
place_macro -macro_name system/bootROMDomainWrapper.bootrom -location {71.136 964.135} -orientation MX
place_macro -macro_name system/subsystem_l2_wrapper/l2 -location {118.482 946.27} -orientation R180
place_macro -macro_name system/tile_prci_domain/tile_reset_domain_boom_tile/core/FpPipeline -location {181.2 53.04} -orientation MY
place_macro -macro_name system/tile_prci_domain/tile_reset_domain_boom_tile/core/iregfile/regfile_ext -location {22.052 29.856} -orientation MY
place_macro -macro_name system/tile_prci_domain/tile_reset_domain_boom_tile/dcache -location {22.08 625.708} -orientation MX
place_macro -macro_name system/tile_prci_domain/tile_reset_domain_boom_tile/frontend/bpd -location {893.748 566.05} -orientation R180
place_macro -macro_name system/tile_prci_domain/tile_reset_domain_boom_tile/frontend/ftq/meta_ext -location {733.595 46.512} -orientation MX
place_macro -macro_name system/tile_prci_domain/tile_reset_domain_boom_tile/frontend/icache -location {719.172 782.836} -orientation R180
place_macro -macro_name system/tile_prci_domain/tile_reset_domain_boom_tile/ptw/l2_tlb_ram_0_ext -location {907.99 22.153} -orientation MX
place_macro -macro_name system/uartClockDomainWrapper/uart_0/rxq.ram_ext -location {956.968 936.277} -orientation MX
place_macro -macro_name system/uartClockDomainWrapper/uart_0/txq.ram_ext -location {878.578 936.277} -orientation MX
$ cat xxx.tcl 
$
```

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/520a354a-1e5e-42a3-b3c4-090050a08c42)
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/a4a48871-f7c9-4445-aff2-4621b73f551a)
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/199c6c47-e6ba-4471-8f98-1befb9677a22)

Intentionally, BranchPredictor has all the pins on the left side. This is to break the rotational and mirroring symmetry such that mpl2 can try different directions to find one that is better.

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/7272e784-c63e-4209-b0ac-3dd59f43b22d)

This is odd... Why is the macro rotated R180? That puts the pins on the right hand side... I would have thought, looking at the floorplan, that having the pins on the left side was better, given the placement...

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/c54e3016-9444-4b17-805f-9a82a1d003d7)

_Originally posted by @oharboe in https://github.com/The-OpenROAD-Project/OpenROAD/discussions/4504#discussioncomment-8066586_

**Comment by oharboe** [comment]
If I swap the pins from one side to the other of the two macros manually by editing the placement.tcl above,  congestion is dramatically reduced.

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/59a3ef9f-74ca-4d27-840f-125c6ee1f306)

**Comment by maliberty** [comment]
@oharboe I believe you said all the pins are on one side.  That isn't true as clock is on the opposite side to the other pins (it is core facing in this placement)

@AcKoucher I think the clock pin is overweighted in the flipping decision.  The clock net has 121,095 iterms connected to it as we haven't done CTS yet.  calculateRealMacroWirelength will generate a huge value for that one net.  I think it would be better to use HPWL of the net rather than summing all the pin-pair distances.  That would de-emphasize such a large net.

**Comment by maliberty** [comment]
Clock:
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/761514/4104292a-7422-42cf-940c-5a3a91103e4f)

**Comment by maliberty** [comment]
@AcKoucher I tried replacing that method with
```
float HierRTLMP::calculateRealMacroWirelength(odb::dbInst* macro)
{
  float wirelength = 0.0;

  for (odb::dbITerm* iterm : macro->getITerms()) {
    if (iterm->getSigType() != odb::dbSigType::SIGNAL) {
      continue;
    }

    odb::dbNet* net = iterm->getNet();
    if (net != nullptr) {
      const odb::Rect bbox = net->getTermBBox();
      wirelength += bbox.dx() + bbox.dy();
    }
  }

  return wirelength;
}
```
and running this block.  I now see R0 instead of R180.  Please take over from here.
