### ISSUE TITLE
Sink/source verification during a global placement seems to fail on nets connected to pins

### ISSUE THREAD

**Issue by rbarzic** [The-OpenROAD-Project/OpenROAD#454]
When running a global placement on my design, I get an error message (when fastroute is invoked apparently):

Initializing nets...
Checking pin placement...
Checking pin placement... Done!
 > ----Checking sinks/source...
[ERROR] Net CLKIN has invalid sinks/source distribution
    #Sinks: 0; #sources: 1
[ERROR] Net DBG0 has invalid sinks/source distribution
    #Sinks: 0; #sources: 0
[ERROR] Net DBG1 has invalid sinks/source distributio

....

A testcase is available at https://github.com/rbarzic/issues-openroad. directory replace1. It should be self contained
I'm using Openroad, branch openroad  sha1 811dc2ff

**Comment by jjcherry56** [comment]
All of the code that was printing these messages was removed in
6fe55605 Wed Aug 19 19:12:25 2020 -0300 [FastRoute] Remove classes Node, Segment and SteinerTree
