### ISSUE TITLE
Router is assuming all the pins to be in the first layer

### ISSUE THREAD

**Issue by mukul19147** [The-OpenROAD-Project/OpenROAD#455]
Even if I supply pins in the different layer the router is assuming them in the first layer and routing because of which many higher-layer pins remain unconnected. How to fix it?

**Comment by vijayank88** [comment]
@eder-matheus 
Is required any further response?

**Comment by eder-matheus** [comment]
@vijayank88 @mukul19147 I would only add an observation regarding the `set_routing_layers` command, where you can set specific layer ranges for signal and clock nets. But note that even with the layer range defined, the global router needs to create guides to the pin layers for pin access. So you may see routing out of the layer range only for pin access.

**Comment by maliberty** [comment]
@arthurjolo your current work should resolve this
