### ISSUE TITLE
Build error OpenRoad Flow Scripts

### ISSUE THREAD

**Issue by Revenantx86** [The-OpenROAD-Project/OpenROAD#4577]
### Description

I have run the setup.sh and dependency installer but when I try to run build I get the following error. Any Idea how I can solve this issue ? 
<img width="1150" alt="Screenshot 2024-01-23 at 11 54 45 PM" src="https://github.com/The-OpenROAD-Project/OpenROAD/assets/69749268/ade8ef32-18b8-4f43-882b-0e2b44786fca">

**Comment by luarss** [comment]
Hi, for ORFS local installation may I check if you followed these instructions?

```
git clone --recursive https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts
cd OpenROAD-flow-scripts
sudo ./setup.sh
./build_openroad.sh --local
```

**Comment by oharboe** [comment]
@Revenantx86 You probably have a corrupted /usr/local folder that you need to clean out.

When you follow https://openroad-flow-scripts.readthedocs.io/en/latest/user/BuildLocally.html, the files are not installed in /usr/local, but in `OpenROAD-flow-scripts/dependencies`:

```
$ find . -regex .*spdlog/logger\.h
./dependencies/include/spdlog/logger.h
```

**Comment by Revenantx86** [comment]
Thank you very much I have fixed the problem by installing the dependencies properly.
