### ISSUE TITLE
-ltcl shouldn't be used because the TCL library can have different names

### ISSUE THREAD

**Issue by yurivict** [The-OpenROAD-Project/OpenROAD#461]
https://github.com/The-OpenROAD-Project/PDNSim/blob/master/CMakeLists.txt#L24

Names can be libtcl86, libtcl87, etc.

You have FindTCL.cmake, and should use library names returned by it.

**Comment by jjcherry56** [comment]
The PDNSim repository is not used by OpenROAD; the code has been incorporated into the OpenROAD repo.
It doesn't make any sense to transfer this from The-OpenROAD-Project/PDNSim because it is irrelevant.
