### ISSUE TITLE
display "busy" cursor while RUDY is calculating the map

### ISSUE THREAD

**Issue by stefanottili** [The-OpenROAD-Project/OpenROAD#4630]
### Describe the bug

For ispd24 cluster.def (9.8M std cell) it takes RUDY ~30 seconds to compute the map.

### Expected Behavior

Please change the cursor from "pointer" to "busy" while computing RUDY to give the user feedback that OR is doing something.

### Environment

```shell
Feb 6 OR M1 macOS Sonoma
```

### To Reproduce

openroad -gui 
read_lef lef/Nangate.lef
read_def def/cluster.def.gz

show RUDY map

**Comment by maliberty** [comment]
@gudeh

**Comment by gudeh** [comment]
References: 
https://liangrj2014.github.io/ISPD24_contest/
#4618

**Comment by gudeh** [comment]
I noticed that other heatmap calculations also do not indicate when they are busy, and these heatmaps take some time with larger designs as well. Therefore, I have made modifications to show a busy indicator for any heatmap calculation, not just for RUDY.

**Comment by gudeh** [comment]
Covered by #4638.
