### ISSUE TITLE
Add feature to click on bucket in slack endpoint histogram to navigate to timing report

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4633]
### Description

It would be nice to be able to click in the endpoint slack histogram and read in those endpoints in the timing report:

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/82e72ccf-77a1-4268-a90b-2c9ab1acb8af)

### Suggested Solution

Click in endpoint histogram, read in those end points in the timing report.

**Comment by oharboe** [comment]
> My concern here is what happens if you click on a very large bin (eg 7k endpoints above). That could get rather slow to generate in the second model.

You can still respect the filtering option which defaults to maximum 50 endpoints.

The use-case of right clicking in the histogram on something interesting is to see some of the worst endpoints in that range.

**Comment by maliberty** [comment]
That seems reasonable.  @AcKoucher does that answer the question?
