### ISSUE TITLE
RePlAce rips off placement blockages/PG and places logic on top of macros

### ISSUE THREAD

**Issue by kunalg123** [The-OpenROAD-Project/OpenROAD#464]
Hi 
I am noticing, RePlAce is ripping of all placement blockages which I added on top of macros. It also shortens the PG to small rectangle pieces. 
Not only that, it places cells on top of macros. This is a mixed-size placement. 
I am attaching lef/def for you to have a look. Can you please help know if I am missing anything?

[picosoc.tar.gz](https://github.com/abk-openroad/RePlAce/files/2675922/picosoc.tar.gz)

**Comment by maliberty** [comment]
Replace doesn't guarantee it will never violate a blockage.  Recently opendp added code to push such instances off the macro.  Is that sufficient for your needs?
