### ISSUE TITLE
Buffer added immediately after input buffer

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4650]
### Describe the bug

A buffer is added immediately after an input buffer for a signal that goes through (not registered) the macro below. It is as if the buffer after input is added without regards to the existing buffer.

To reproduce, run `make DESIGN_CONFIG=designs/asap7/mock-array/Element/config.mk` with https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1794

To view the problem, run:

1. untar  [extra-buffer.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/14228657/extra-buffer.tar.gz)
2. Run `./run-me-mock-array_Element-asap7-base.sh`
3. Examine the timing path for endpoint `io_lsbOuts_6`
4. Observe the back-to-back buffers on the input

The buffer is inserted during synthesis. Commenting out `insbuf` removes the middle buffer, but also the input & output buffers.

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/b6f7d318f0eb186069acd9af85898e7dcfa64d3a/flow/scripts/synth.tcl#L78

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/d96e50bd-0655-4763-af15-c3ec52fdc54c)

### Expected Behavior

Remove the superflous buffer

### Environment

```shell
OpenROAD v2.0-12143-g4aabf0d3c
```

### To Reproduce

See above

**Comment by maliberty** [comment]
The buffer is kept from synthesis as it directly connects an input port to an output port (you can tell by the name _776_).  Later we buffer the input port and the output port so we get the three buffer chain.  I believe this has come up before.  The location of the buffer is just whatever global placement happens to pick (from an hpwl perspective the X coordinate has no effect).

We could do something like don't buffer the input if it only drives buffer(s) currently.  We would still buffer the output resulting in a two buffer net (prior to any repair).  Is that acceptable?

**Comment by oharboe** [comment]
@maliberty That would be great, but it is a separate concern from being able to answer the question of what happens w zero buffers. I think both have value.

**Comment by maliberty** [comment]
> zero

I don't understand what you comment about zero buffers relates to above.  Having zero buffers is a bad idea.

**Comment by oharboe** [comment]
> > zero
> 
> I don't understand what you comment about zero buffers relates to above. Having zero buffers is a bad idea.

For the mock array, there is a discussion to be had as to how many buffers are needed. Maybe not for every Element. Therefore, it is interesting to do a measurement of what zero buffers would yield as a limit. If with zero buffers one can not.reach acceptable numbers, then that is a useful negative result for architectural feedback.
