### ISSUE TITLE
hv_inflation_ratio always 0,0

### ISSUE THREAD

**Issue by ArEsKay3** [The-OpenROAD-Project/OpenROAD#466]
Hey (it's me again),
    I'm able to run both DAC2012 bookshelf format (on 1.0.0) and ISPD2018 (on 1.1.0) with the routability option enabled and in order to verify it was working I was looking for a print that was non-zero for hv_inflation_ratio but all I see is 0, 0 for all the prints. Am I missing something? I want to play with the max_inflation_ratio parameter to see how results change, but I don't know how to confirm that this argument is taking effect.
Thanks!
ArEsKay3

**Comment by maliberty** [comment]
There is no hv_inflation_ratio in the replace code anymore.
