### ISSUE TITLE
Metal1 assumptions on macro placement

### ISSUE THREAD

**Issue by ax3ghazy** [The-OpenROAD-Project/OpenROAD#470]
Hello,

Why is it assumed that block macros are supposed to have metal1 OBS? (i.e., the size of a macro seems to be calculated based on its obstructions on metal1)

For example, to reproduce, 
1. Try to place a macro that has no OBS shapes on the first metal layer. -> replace exits complaining that the macro has no metal1 OBS statements.
2. Insert a dummy OBS statement on metal1 (e.g., `RECT 0 0 0 0 ;`) -> replace reports such macros as having 0 height.

Thanks.

**Comment by maliberty** [comment]
We are moving away from having replace handle macro placement.
