### ISSUE TITLE
OpenSTA: write_timing_model should add "is_macro_cell : true"

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#4710]
### Description

write_timing_model should add to the generated .lib:
```
is_macro_cell : true;
```
The lack of this confuses
```
bool Resizer::isCombinational(LibertyCell* cell) const
{
  if (!cell) {
    return false;
  }
  return (!cell->isClockGate() && !cell->isPad() && !cell->isMacro()
          && !cell->hasSequentials());
}
```
into thinking a macro is combinational.

### Suggested Solution

Write the requested

**Comment by maliberty** [comment]
asap7/aes-block demonstrates the issue.

**Comment by maliberty** [comment]
Workaround in https://github.com/The-OpenROAD-Project/OpenROAD/pull/4711

**Comment by tspyrou** [comment]
@maliberty update was pushed today.
