### ISSUE TITLE
Correlate RUDY with grt

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#4717]
### Description

All the fixed costs should match (pdn, blockages).  Derating should be correlated as well.

**Comment by gudeh** [comment]
Here are some correlation images for our current RUDY version, using harmonic mean to estimate the wire width: https://drive.google.com/drive/folders/1eR-apgzr45kYF5MM7iiiE1H-AkUZlmN-?usp=sharing

**Comment by maliberty** [comment]
Done?
