### ISSUE TITLE
Replace grt with rudy in gpl's routability

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#4718]
### Description

Seek to replace calls to grt with rudy to improve the runtime performance of gpl without QOR degradation.

**Comment by gudeh** [comment]
RUDY was merged.
ORFS PR: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2060
OR PR:     https://github.com/The-OpenROAD-Project/OpenROAD/pull/5124
