### ISSUE TITLE
[Partitioner] Information group_file format in TritonPart

### ISSUE THREAD

**Issue by ombhilare999** [The-OpenROAD-Project/OpenROAD#4723]
### Description

Hi team,

Can you please point me to acceptable group file format for TritonPart?
I could not find any mentioned reference on the openroad document website.

![image](https://github.com/ABKGroup/TritonPart/assets/40693854/00836694-a266-4904-8a72-1f8918da2c8f)

In the above documentation it forwards to hMETIS manual but as far I know last updated hMETIS did not supported the group constraint feature. It only accepts `input hypergraph file and fixed file`.

![image](https://github.com/ABKGroup/TritonPart/assets/40693854/bc558bd2-9784-4bb0-a37a-3554477908bf)

It would really great if I could any information about group file.

As of now I was using following format, but it seems not working as TritonPart places them in different partitions and at the same time prints that it satisfied the group constraint. So, I believe I must have given non-acceptable group information.

```
1 2 %group of vertices 1 and 2
3 4 %group of vertices 3 and 4
```

Thanks a lot.

**Comment by maliberty** [comment]
https://github.com/The-OpenROAD-Project/OpenROAD/blob/85f541bb67dd0498b0f53c78b572a12d0c4aa7a7/src/par/src/TritonPart.cpp#L1121 does reference hMetis.  I don't know the details but the parser just looks to read a set of integers per line.

I'm trying to get one of the original authors to respond

**Comment by bodhi91** [comment]
For the grouping information, each line consists of vertices belonging to the same group. **Please note that all vertex indices are one-indexed (similar to hMETIS) .** 

For example:
```
1 3 5 6
2 4 9 11
7 8 10
```

In this example:

- Vertices 1, 3, 5, and 6 are assigned to group 0.
- Vertices 2, 4, 9, and 11 are assigned to group 1.
- Vertices 7, 8, and 10 are assigned to group 2.

Please create a file in this format and then use the -`group_file` option to specify its path when running TritonPart.

In this situation, the group file that you are passing looks to be the correct way to pass grouping arguments. 

Can you add the testcase, partition file and log file to this thread so that I can replicate this on my side?

**Comment by maliberty** [comment]
@ombhilare999 is this just a question (and we can close) or is there a problem to fix?

**Comment by ombhilare999** [comment]
Hi @bodhi91,

Sorry for late response. Please find the attached files for reproducing the results:

**sample.hgr:**
```
 3 5 
 1 2 
 2 3 5 
 4 5
``` 
---
**sample.group:**
```
1 2 %Vertex 1 and 2 in group 0
3 4 5 %Vertex 1 and 2 in group 1
```
---
**sample.tcl:**
```
triton_part_hypergraph -hypergraph_file sample.hgr -group_file sample.group -num_parts 2 -balance_constraint 10 -seed 2
exit
```
---

**Execution command used:** ` ../../../TritonPart_from_openroad_repo/OpenROAD/build/src/openroad sample.tcl`

---
**Error encountered:**
```
OpenROAD v2.0-12381-g01bba3695 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
[INFO PAR-0002] Partitioning hypergraph.
Partitioning Parameters
        Number of partitions = 2
        UBfactor = 10.0
        Seed = 2
        Vertex dimensions = 1
        Hyperedge dimensions = 1
        Placement dimensions = 0
        Global net threshold = 1000
[INFO PAR-0038] Display Used Files
        Group file: sample.group
        Hypergraph file: sample.hgr
        Solution file: sample.hgr.part.2
[WARNING PAR-0003] Timing-driven mode is not supported! Disabling timing aware.
group file information
group 0: 0 1 
group 1: 2 3 4 
[INFO PAR-0017] Read hypergraph has 5 vertices and 3 hyperedges.
modified_vertex_balance:
5 
modified_lower vertex_balance:
5 
/usr/include/c++/11/bits/stl_vector.h:1063: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::const_reference = const int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Signal 6 received
Stack trace:
 0# 0x00005615E41B458B in ../../../TritonPart_from_openroad_repo/OpenROAD/build/src/openroad
 1# 0x00007F58BE242520 in /lib/x86_64-linux-gnu/libc.so.6
 2# pthread_kill in /lib/x86_64-linux-gnu/libc.so.6
 3# raise in /lib/x86_64-linux-gnu/libc.so.6
 4# abort in /lib/x86_64-linux-gnu/libc.so.6
 5# 0x00005615E41AD6D8 in ../../../TritonPart_from_openroad_repo/OpenROAD/build/src/openroad
 6# par::GoldenEvaluator::GetBlockBalance(std::shared_ptr<par::Hypergraph> const&, std::vector<int, std::allocator<int> > const&) const in ../../../TritonPart_from_openroad_repo/OpenROAD/build/src/openroad
 7# par::GoldenEvaluator::ConstraintAndCutEvaluator(std::shared_ptr<par::Hypergraph> const&, std::vector<int, std::allocator<int> > const&, float, std::vector<float, std::allocator<float> > const&, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > const&, bool) const in ../../../TritonPart_from_openroad_repo/OpenROAD/build/src/openroad
 8# par::TritonPart::MultiLevelPartition() in ../../../TritonPart_from_openroad_repo/OpenROAD/build/src/openroad
 9# par::TritonPart::PartitionHypergraph(unsigned int, float, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&, unsigned int, int, int, int, char const*, char const*, char const*, char const*, char const*) in ../../../TritonPart_from_openroad_repo/OpenROAD/build/src/openroad
10# par::PartitionMgr::tritonPartHypergraph(unsigned int, float, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&, unsigned int, int, int, int, char const*, char const*, char const*, char const*, char const*, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&, int, int, int, float, int, float, int, int, int, int, int, float, int, bool, int, int, int, int) in ../../../TritonPart_from_openroad_repo/OpenROAD/build/src/openroad
11# 0x00005615E5C17237 in ../../../TritonPart_from_openroad_repo/OpenROAD/build/src/openroad
12# TclNRRunCallbacks in /lib/x86_64-linux-gnu/libtcl8.6.so
13# 0x00007F58C29F1028 in /lib/x86_64-linux-gnu/libtcl8.6.so
14# Tcl_EvalEx in /lib/x86_64-linux-gnu/libtcl8.6.so
15# Tcl_Eval in /lib/x86_64-linux-gnu/libtcl8.6.so
16# sta::sourceTclFile(char const*, bool, bool, Tcl_Interp*) in ../../../TritonPart_from_openroad_repo/OpenROAD/build/src/openroad
17# ord::tclAppInit(Tcl_Interp*) in ../../../TritonPart_from_openroad_repo/OpenROAD/build/src/openroad
18# Tcl_MainEx in /lib/x86_64-linux-gnu/libtcl8.6.so
19# main in ../../../TritonPart_from_openroad_repo/OpenROAD/build/src/openroad
20# 0x00007F58BE229D90 in /lib/x86_64-linux-gnu/libc.so.6
21# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
22# _start in ../../../TritonPart_from_openroad_repo/OpenROAD/build/src/openroad
Aborted (core dumped)
```

For some reason I am not facing this issue on TritonPart from [ABKGroup repository](https://github.com/ABKGroup/TritonPart) but only facing this issue with the TritonPart from the main branch of Openroad. [Current version I am using:  `v2.0-12381-g01bba3695`  ]

Can you please help me here. Thanks a lot.

Please let me know if you need any more information.
