### ISSUE TITLE
Improve error message when design doesn't fit

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#473]
I believe the error message below is simply because there's no way this placement of the RAMs is going to work.

Can the error message be improved for the user?

```
[ERROR] RePlAce divergence detected. 
        Please decrease max_phi_cof value (REPL-4)
```

2_floorplan.def:

![image](https://user-images.githubusercontent.com/2798822/80678340-0378fe80-8abb-11ea-8b3e-e794fbce8d29.png)

**Comment by maliberty** [comment]
There have been improvements to the messages suggesting what knobs might help.
