### ISSUE TITLE
alt+mousewheel no longer scrolls horizontally

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4757]
### Describe the bug

1. open OpenROAD GUI
2. zoom in using ctrl+mousewheel
3. just mousewheel alone moves up and down
4. alt+mousewheel should have moved horizontally, but moves up/down 

OpenROAD v2.0-12475-g1b6a4e128

### Expected Behavior

alt+mousewheel should have moved horizontally, but moves up/down

### Environment

```shell
OpenROAD v2.0-12475-g1b6a4e128
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic
```

### To Reproduce

See above

**Comment by maliberty** [comment]
There is no recent GUI change that I can imagine causing this.  Are you sure it isn't a local issue with your alt key?

**Comment by oharboe** [comment]
Works on my workstation, but not on my laptop. Could this be because the laptop has a mousepad?

**Comment by oharboe** [comment]
@maliberty I'm not able to get alt+mousewheel to work on my laptop, nor am I able to grab the view and move it around with the mouse. What was the key to grab the view and move it again?

Could someone try on an Ubuntu laptop to confirm?

**Comment by maliberty** [comment]
> What was the key to grab the view and move it again?

middle mouse button click and drag

**Comment by oharboe** [comment]
> > What was the key to grab the view and move it again?
> 
> middle mouse button click and drag

I dont have a middle button

**Comment by maliberty** [comment]
Usually there is some way to emulate it on systems that don't have it - some combinations of key press plus button.

**Comment by maliberty** [comment]
https://askubuntu.com/questions/1422992/middle-click-not-emulated-in-22-04

**Comment by oharboe** [comment]
> https://askubuntu.com/questions/1422992/middle-click-not-emulated-in-22-04

Holding down mousewheel to grab works on my workstation.

**Comment by maliberty** [comment]
I don't know that we have anyone with an Ubuntu laptop.  Are you stuck?

**Comment by maliberty** [comment]
@oharboe are you stuck or should we close?

**Comment by oharboe** [comment]
Let's have a look next time we meet, might be trivial.

**Comment by oharboe** [comment]
hold two fingers horizontally and vertically, respectively and move vertical/horizontally
