### ISSUE TITLE
Yosys SDC support

### ISSUE THREAD

**Issue by kentropy** [The-OpenROAD-Project/OpenROAD#476]
I added -constr -s path/to/sdc/constraint.sdc to the script of yosys, but whatever I put in the file, the log always indicates "SDC File Parsing Failed!". Is there any information about what is wrong? E.g.: syntax, brackets evaluation?

**Comment by rovinski** [comment]
This is a yosys question, not really an OpenROAD question.

But the answer is that ABC, the logic optimizer that yosys uses, has very little support for SDC constraints. The only thing that OpenROAD-flow attempts to pass in is 1 clock constraint, a driving cell, and a load. If you want improved support, you'll have to request that from the folks at [yosys](https://github.com/YosysHQ/yosys) and [ABC](https://github.com/berkeley-abc/abc).

If it's any consolation, some internal benchmarking has shown that ABC output doesn't change much regardless of the timing constraints, and OpenROAD does a good job of physically-aware resizing/buffering, which ABC can't do.
