### ISSUE TITLE
Add skew column to timing report

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4762]
### Description

It would be nice to see a clock tree skew column to immediately get a sense for which timing paths that have a problem with a clock tree skew vs. problem with the path itself(such as too much logic). Of course skew can be positive and negative, but as a starting point for investigation, this would be nice.

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/554c727c-3ff4-4303-8781-0d637a87ffc1)

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/b760aa3f-d2f4-4b60-b1f2-2d006dd87273)

### Suggested Solution

Add skew column

**Comment by tspyrou** [comment]
Pls make class clkskew in sta/search/ClkSkew.cc public to allow the GUI access.

**Comment by tspyrou** [comment]
@AcKoucher Cherry will make a proposal on a new API. We discussed it today.

**Comment by AcKoucher** [comment]
@tspyrou Ok!

**Comment by oharboe** [comment]
@tspyrou How can the userinterface indicate if the skew is useful or not for a path?

Could there be a "Useful skew" column where positive is useful and negative is unhelpful skew?

**Comment by jjcherry56** [comment]
Making class ClkKkew (not clkskew) in sta/search/ClkSkew.cc public would not do you any good because there is no api to populate it for a given source/target pair in the timing summary report.
I added PathEnd::clkSkew which is one-to-one with the reported lines in commit
1d7bd5ba PathEndCheck::clkSkew

**Comment by maliberty** [comment]
This API has been integrated to OR with #4906
