### ISSUE TITLE
[WARNING DRT-0422] No routing tracks pass through the center of Term io_outs_up[28]

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4763]
### Describe the bug

Based on `make DESIGN_CONFIG=designs/asap7/mock-array/Element/config.mk`

Untar [detailed-route-warning.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/14558177/detailed-route-warning.tar.gz)

```
$ NUM_CORES=16 ./run-me-mock-array_Element-asap7-base.sh
OpenROAD v2.0-12488-g85f541bb6
 [deleted]
[WARNING DRT-0422] No routing tracks pass through the center of Term clock
[WARNING DRT-0422] No routing tracks pass through the center of Term io_ins_down[0]
[WARNING DRT-0422] No routing tracks pass through the center of Term io_ins_down[10]
[WARNING DRT-0422] No routing tracks pass through the center of Term io_ins_down[11]
[WARNING DRT-0422] No routing tracks pass through the center of Term io_ins_down[12]
[WARNING DRT-0422] No routing tracks pass through the center of Term io_ins_down[13]
[WARNING DRT-0422] No routing tracks pass through the center of Term io_ins_down[14]
[WARNING DRT-0422] No routing tracks pass through the center of Term io_ins_down[15]
[deleted]
```

Looks OK?

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/d1c699b2-9ff4-4a1e-8e77-f6afbdf9ceae)

### Expected Behavior

No warning and no problems

### Environment

```shell
OpenROAD v2.0-12488-g85f541bb6
```

### To Reproduce

See above

**Comment by maliberty** [comment]
It looks like the routing track is not through the center as the message indicates.  How was the pin placed?

**Comment by maliberty** [comment]
It would be helpful to turn off all other layers in the image.

**Comment by oharboe** [comment]
> It looks like the routing track is not through the center as the message indicates. How was the pin placed?

standard orfa flow, no changes.

**Comment by eder-matheus** [comment]
The pins are aligned with the tracks:
<img width="772" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD/assets/43450810/f1f9479a-8ad5-4948-ade1-cc30dd2c0f2d">

I've checked it with the ruler, and the pin placement looks ok. This is probably a false warning from DRT, which I'll investigate this week.
