### ISSUE TITLE
add "-Werror" option to openroad, warnings are errors

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4812]
### Description

It would be nice to enable warnings are errors on testcases in ORFS once they have no errors.

### Suggested Solution

Implement a "-Werror" option. Naming idiom taken from gcc options, so something more openroadesque in terms of naming for option would be a good idea, perhaps `-error_on_warning`?

**Comment by maliberty** [comment]
This already exists https://github.com/The-OpenROAD-Project/OpenROAD/blob/594c45876789352b0aad21b1edbc5892f1a4c070/src/CMakeLists.txt#L180

**Comment by maliberty** [comment]
It is set to OFF in the CI but we don't want to have users get stuck on building with various compiler versions.

**Comment by oharboe** [comment]
I dont mean when compiling openroad, but when running openroad.

**Comment by maliberty** [comment]
We could add the option though I'm not sure if we can commit to zero warnings all the time.

**Comment by maliberty** [comment]
I would make it a command in OR not a command line option.

**Comment by oharboe** [comment]
Hmmm.... perhaps start w a CI perspective? Parse output and add warnings to baseline data(metadata), which would make this specific feature request obsolete.

**Comment by oharboe** [comment]
https://github.com/The-OpenROAD-Project/OpenROAD/pull/4817 is much nicer.
