### ISSUE TITLE
[OpenROAD-flow-public] Error while building on Ubuntu 18.04

### ISSUE THREAD

**Issue by rashmi2383** [The-OpenROAD-Project/OpenROAD#483]
ERROR: ABC contains local modifications! Set ABCREV=default in Yosys Makefile!
Makefile:622: recipe for target 'abc/abc-7a98ef0' failed
make: *** [abc/abc-7a98ef0] Error 1
make: *** Waiting for unfinished jobs....

**Comment by rovinski** [comment]
Try cleaning yosys and rebuilding (using the workaround in #482).

**Comment by rashmi2383** [comment]
This error doesn't go away.

**Comment by rovinski** [comment]
Try a fresh clone.

**Comment by rashmi2383** [comment]
Tried but no luck. Rest everything passes except this.

**Comment by rovinski** [comment]
I don't know what else to tell you, this issue is not reproducible for me on CentOS 6/7 or Ubuntu 18.04. The issue is self-explanatory, your ABC directory is not clean. I don't know what's happening to not make it not clean, but that shouldn't happen if you simply do:
```
git clone https://github.com/The-OpenROAD-Project/OpenROAD-flow OpenROAD-flow
cd OpenROAD-flow
./build_openroad.sh
```

**Comment by rashmi2383** [comment]
Using ./build_openroad.sh without --local switch helped.
