### ISSUE TITLE
Use some reasonable number of buckets in slack histogram

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4841]
### Description

I wanted to demonstrate the slack histogram using the the default target in ORFS.

Run `make && make gui_final` and view the slack histogram.

Only two buckets are created. Perhaps because the units are nanoseconds and all the slack is within 1 nanosecond?

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/ce48ba57-ab40-4644-a038-5d1e1ff87dc8)

### Suggested Solution

Use some better heuristic for number of buckets, say minimum 4-8?

**Comment by AcKoucher** [comment]
Would a solution like changing the scale for improving the visualization be acceptable here? Instead of using decimal numbers in ns we can just use µs:

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/104802710/0b3063fb-2133-45ae-90e8-5104914a192b)

**Comment by oharboe** [comment]
I would prefer a good heuristic and fewer options generally. Note that us, ns, ps are all reasonable units, depending on the design...

**Comment by AcKoucher** [comment]
@oharboe Keeping the unit from sta and using somewhat decimal values:

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/104802710/5057f811-04b1-4899-9478-dfae0f0246ed)

Would it be reasonable?

**Comment by oharboe** [comment]
Very nice.
