### ISSUE TITLE
Fail early on doomed repair_timing TNS_END_PERCENT=0 in CTS

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4843]
### Description

Another test case that includes .lib files for macros.

CTS takes ca. 10 minutes and repair_timing has not completed after 10 hours.

Creating feature request, even if duplicate, to save off this test-case in case it is useful. Feel free to close if duplicate.

untar https://drive.google.com/file/d/1O-WZx1yoG4V3p4vkqRwbk-dIaItKTqeQ/view?usp=sharing

The log doesn't contain exact numbers here, so take running times with a pinch of salt.

This takes ca. 10 minutes:

```
$ ./run-me-BoomTile-asap7-base.sh 
OpenROAD v2.0-12709-g48675cbda 
[deleted]
[INFO CTS-0101]  Average sink wire length 2416.21 um
[INFO CTS-0102]  Path depth 24 - 24
[INFO CTS-0098] Clock net "clock_regs"
[INFO CTS-0099]  Sinks 248576
[INFO CTS-0100]  Leaf buffers 15507
[INFO CTS-0101]  Average sink wire length 1413.18 um
[INFO CTS-0102]  Path depth 35 - 35
[WARNING STA-0450] virtual clock clock_vir can not be propagated.
Warning: There are 173 unconstrained endpoints.
```

The above has completed in 10 minutes.

Now resizing starts, which runs for a good while:

```
[INFO RSZ-0058] Using max wire length 162um.
[INFO RSZ-0047] Found 16 long wires.
[INFO RSZ-0048] Inserted 58 buffers in 16 nets.
Placement Analysis
---------------------------------
total displacement      10750.2 u
average displacement        0.0 u
max displacement           28.0 u
original HPWL        25963874.1 u
legalized HPWL       26193076.1 u
delta HPWL                    1 %
```

Finally, repair timing, not finished after 10 hours:

```
repair_timing -repair_tns 0
[INFO RSZ-0094] Found 4039 endpoints with setup violations.
[INFO RSZ-0043] Swapped pins on 1 instances.
[WARNING RSZ-0062] Unable to repair all setup violations.
[INFO RSZ-0046] Found 8552 endpoints with hold violations.
[WARNING RSZ-0066] Unable to repair all hold violations.
[INFO RSZ-0032] Inserted 2383080 hold buffers.
[still running after 10 hours]
```

### Suggested Solution

Make repair_timing fast.

### Additional Context

Repair timing on CTS is doomed here because there is a mock macro abstract that only went through floorplan. It has a delay of 400000ps for which repair timing is trying to add hold cells, presumably.

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/182dc054-5d45-4736-acf5-793f833418ee)

**Comment by oharboe** [comment]
I only read `[INFO RSZ-0032] Inserted 2383080 hold buffers.` now...

"Well, there's your problem", I believe the expression is...

I believe this is a case of where repair_timing should just fail and put itself out of it's missery...

**Comment by maliberty** [comment]
There is -max_buffer_percent (default 20%) which should have stopped it unless this is a huge design.  How many instances are there?

**Comment by oharboe** [comment]
> There is -max_buffer_percent (default 20%) which should have stopped it unless this is a huge design. How many instances are there?

2-3m for MegaBoom, if I recall.

**Comment by oharboe** [comment]
@maliberty Changed the title of this feature request: this is not a problem in CTS or repair timing as such, but rather than it would be nice if repair timing failed doomed runs early with an actionable error message.

I'll continue to work on the megaboom design. I am updating the abstracts for the macros that BoomTile uses to run through global routing so that the timing should be reasonable at the BoomTile CTS level.

mock abstracts from the floorplan stage are useful for iterating on floorplan and placement in BoomTile, but not through CTS.

**Comment by maliberty** [comment]
It already should stop at the 20% threshold so it isn't an enhancement so much as a potential bug.

**Comment by oharboe** [comment]
Just FYI: when I fix the macro abstracts so that they have .lib files from after global routing, CTS, including repair, completes in 15 minutes, whereas I stopped the report_timing after 10 hours without progress with the macro abstracts made after floorplan.

**Comment by maliberty** [comment]
This design has tremendous negative slack which you probably don't get without the macro .libs

**Comment by oharboe** [comment]
> This design has tremendous negative slack which you probably don't get without the macro .libs

Indeed. This issue is only about giving actionable information timely. Thanks!

The macros have pathologically negative slack because they have abstracts created after floorplanning. If I create the anbstracts after global route, the timing is reasonable. mock abstracts from floorplanning are useful to iterate early on floorplan and placement on hhigher level macros, but of course it cant work with CTS.
