### ISSUE TITLE
45 degrees labels to have more space in endpoint slack histogram

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4887]
### Description

The labels don't fit

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/886ec4a8-b506-42ab-93b7-a1e2340c4a5f)

### Suggested Solution

Make labels 45 degrees to make more space for labels

**Comment by oharboe** [comment]
Use 45 degrees only if necessary and add enough space vertically for the labels....

Something  like:
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/680a0009-aa8b-46a9-a79c-73445ebd2505)

The naive change didn't work, because it uses elipsis unecessarily:

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/88295ce6-5104-492a-ab05-71bd5bfa445b)

**Comment by stefanottili** [comment]
Instead of fiddling with the label presentation, fix the uints.
Just write 50ns, it's much more meaningful then 50000ps in 5000ps increments

**Comment by oharboe** [comment]
> Instead of fiddling with the label presentation, why not fix the units instead ? 50ns is shorter and more meaningful then 50000ps in 5000ps increments

I disagree. for a design where units are in ps, stay in ps.

The reason why you see 500000ps here is pathological and I dont accie
