### ISSUE TITLE
improve macro placement in megaboom

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4951]
### Description

The macro placement results are hard to route, ref https://github.com/The-OpenROAD-Project/OpenROAD/issues/4948

To reproduce:

untar https://drive.google.com/file/d/1Qc13d71MCpUMNGOWs1TLq-KYdBuNH2YK/view?usp=sharing

```
NUM_CORES=16 ./run-me-BoomTile-asap7-base.sh
```

Output:

```
OpenROAD v2.0-13280-gc379c757d 
Features included (+) or not (-):  +Charts +GPU +GUI +MPL2 +PAR +Python
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
[INFO ORD-0030] Using 16 thread(s).
HierRTLMP Flow enabled...
rtl_macro_placer -halo_width 20 -report_directory /home/oyvind/.cache/bazel/_bazel_oyvind/7e6ad621f3f951c3ee6f5b179289b54e/execroot/_main/bazel-out/k8-fastbuild/bin/objects/asap7/BoomTile/base/rtlmp
Floorplan Outline: (0.0, 0.0) (1363.625, 1363.625),  Core Outline: (4.05, 4.05) (1359.612, 1359.45)
Traversed logical hierarchy
	Number of std cell instances: 1450201
	Area of std cell instances: 189822.05
	Number of macros: 72
	Area of macros: 162242.48
	Area of macros with halos: 520130.44
	Area of std cell instances + Area of macros: 352064.53
	Core area: 1837328.62
	Design Utilization: 0.19
	Core Utilization: 0.11
	Manufacturing Grid: 1

openroad>
```

Result:

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/89403caa-0ac9-4431-9121-c077e655e64b)

### Suggested Solution

Make macro placement even better

**Comment by maliberty** [comment]
This is not the same placement shown in https://github.com/The-OpenROAD-Project/OpenROAD/issues/4948 - is this a different problem?

**Comment by AcKoucher** [comment]
Also, the result we see on your image, is it also hard to route as the placement in #4948? It looks like there's a lot of space.

**Comment by oharboe** [comment]
> This is not the same placement shown in #4948 - is this a different problem?

Global route works here. I could look at reproducing the exact conditions last time, but I thought this was a useful test case too.

**Comment by oharboe** [comment]
will reopen new issue if I can reproduce it
