### ISSUE TITLE
Add "Logic delay" column to Timing Report

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4973]
### Description

It is useful to see the logic delay of a path in the Timing Report when doing triage in architectural exploration.

### Suggested Solution

Add "Logic delay" column to Timing Report

**Comment by maliberty** [comment]
This new column would be the sum of the non-buffer gate delays without any wire delay.

**Comment by maliberty** [comment]
The idea is to give an indication of paths that have too much logic and probably need an RTL-modification solution.

**Comment by maliberty** [comment]
Replaces / simplifies https://github.com/The-OpenROAD-Project/OpenROAD/issues/4832

**Comment by maliberty** [comment]
It is the sum of the delays.  I think of logic depth as the number of gates.

**Comment by maliberty** [comment]
It does make me think that would also be a good column.  I think we might need to implement column visibility to prevent this from become a super wide table (eg https://ux.stackexchange.com/questions/110077/best-practices-to-allow-user-to-hide-show-columns-in-a-data-table)

**Comment by maliberty** [comment]
@oharboe any preference on delay vs depth?

**Comment by oharboe** [comment]
> @oharboe any preference on delay vs depth?

I would want to know both. I believe logic depth might be a bit less standard on ASAP7? Isn't ASAP7 missing some things like muxes as primitives? How does a mux count as "levels of logic"? I'm not sure if a mux primitive in the PDK would be enormously much faster than something that is built up of even smaller primitivies. Out of my depth here... Would appreciate some input and guidance...

**Comment by oharboe** [comment]
@rovinski Thanks! This makes sense. It sounds like this is complimentary information that helps to create a more fleshed out understanding of what is going on...

**Comment by maliberty** [comment]
What is the conclusion in terms of this request?

**Comment by oharboe** [comment]
Add both columns. Later on, if there are even more columns, maybe the userinterface should change to  enable/disable columns.

today, startpoint is show, perhaps endpoint column?

**Comment by maliberty** [comment]
> today, startpoint is show, perhaps endpoint column?

I don't know what this means

**Comment by oharboe** [comment]
> > today, startpoint is show, perhaps endpoint column?
> 
> I don't know what this means

There is a Start column today, and I've highlighted what would be the "End" column in Data Path Details:


![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/be426e80-f44b-43f3-bae5-d935e638abce)

**Comment by maliberty** [comment]
So this is a totally unrelated request?

**Comment by oharboe** [comment]
> So this is a totally unrelated request?

Yes. I would leave it be for now.

It is just an example of why I think your consideration of what to do if many columns are added makes sense: https://github.com/The-OpenROAD-Project/OpenROAD/issues/4973#issuecomment-2065614093

**Comment by AcKoucher** [comment]
@maliberty @oharboe So to be clear, the request here is:

1. Add "Logic Delay" column;
2. Add "Logic Depth" column;
3. Column Visibility.

Is that it?

**Comment by maliberty** [comment]
Yes
