### ISSUE TITLE
Python interface problem

### ISSUE THREAD

**Issue by FuxingHuang** [The-OpenROAD-Project/OpenROAD#5011]
### Description

The official way to use the python interface is:
```bash
openroad -python script.py
```
Using the following method will report an error:
```bash
python script.py
```
Because SWIG compiles a static library, not a shared library. Python cannot use static libraries directly.

### Suggested Solution

It would be great if you could use openroad's python package in the same way as other python packages.

**Comment by maliberty** [comment]
Duplicate of https://github.com/The-OpenROAD-Project/OpenROAD/issues/2308
