### ISSUE TITLE
To install LEMON on centos7

### ISSUE THREAD

**Issue by rajatg123** [The-OpenROAD-Project/OpenROAD#503]
I want to install OpenROAD EDA tool on centos. But there are one error while I run the command "cmake ..".

The error was 

CMake Error at src/TritonCTS/CMakeLists.txt:11 (find_package):
  By not providing "FindLEMON.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LEMON", but
  CMake did not find one.

  Could not find a package configuration file provided by "LEMON" with any of
  the following names:

    LEMONConfig.cmake
    lemon-config.cmake

  Add the installation prefix of "LEMON" to CMAKE_PREFIX_PATH or set
  "LEMON_DIR" to a directory containing one of the above files.  If "LEMON"
  provides a separate development package or SDK, be sure it has been
  installed.

Please help me.

**Comment by maliberty** [comment]
You need to install https://lemon.cs.elte.hu/trac/lemon/wiki/Downloads
