### ISSUE TITLE
how to open GUI of OpenROAD

### ISSUE THREAD

**Issue by rajatg123** [The-OpenROAD-Project/OpenROAD#505]

**Comment by mi-and-core** [comment]
There isn't a GUI of OpenROAD yet - but a very small template.  To start call openroad -gui

**Comment by maliberty** [comment]
Any further questions or should I close this?

**Comment by rajatg123** [comment]
thank you sir

I have one doubt that I am not able to understand the whole process of ASIC
design in OpenROAD. Can you give me some references , so that I can do it.

**Comment by maliberty** [comment]
You should look at the https://github.com/The-OpenROAD-Project/OpenROAD-flow-public repo for examples of how to run the tools in a complete flow.
