### ISSUE TITLE
Add tooltips to Skew column

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#5083]
### Description

Add a tooltip to explain in a sentence or two exactly what the Skew column is displaying.

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/1c7d2725-eb2a-4f8f-a3a4-7a0aaada675d)

See also https://github.com/The-OpenROAD-Project/OpenROAD/issues/5002 that has been following some bugfixes in Skew column.

### Suggested Solution

Add a terse exact definition of the Skew column in tooltips.

Using this definition, it should be possible to corroborate that information in the Skew column with report_clock_skew or other sources in mock-array and mock-array/Element from within the OpenROAD GUI.

**Comment by maliberty** [comment]
Do you have some text in mind?

**Comment by oharboe** [comment]
> Do you have some text in mind?

@tspyrou ?

**Comment by AcKoucher** [comment]
Any ideas here?

**Comment by tspyrou** [comment]
How about " path clock skew crpr corrected". Is that too long?

**Comment by oharboe** [comment]
> How about " path clock skew crpr corrected". Is that too long?

Looks good. What is the equivalent OpenSTA syntax to reproduce this skew number?

**Comment by AcKoucher** [comment]
I'll also add the tooltips for the other new columns.

@maliberty Would it be consistent to say:

Logic Delay: Non-buffer gate delays with no wire delay.
Logic Depth: Number of instances apart from buffers and back-to-back inverters.

*One thing I was thinking is that we're also counting registers in the logic depth. Would that be concise?

@oharboe Any opinions on these being too long?

**Comment by oharboe** [comment]
Looks good!
