### ISSUE TITLE
OpenROAD-flow-public

### ISSUE THREAD

**Issue by RatkoFri** [The-OpenROAD-Project/OpenROAD#509]
Why is OpenROAD-flow-public repo archived?

**Comment by rovinski** [comment]
#408 isn't a direct answer to your question but it's the best we have at the moment. It is archived to make it read-only.

**Comment by maliberty** [comment]
This is the new area for the flow. https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts  (from #408)
