### ISSUE TITLE
Add "rats nest" display prior to routing

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#5102]
### Description

It would be easier to do floorplaning(macro placement) and io constraints if it was possible to see wires prior to them being routed.

Example from KiCad

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/d8243c27-5ba2-4934-9fd8-40eae460e31f)

### Suggested Solution

Add "rats nest" routing layer prior to routing.

This already exists for clock tree prior to routing.

```
make cts
make gui_cts
```

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/7d0dbb54-0545-4241-b671-02012f0366d0)

**Comment by oharboe** [comment]
Thanks! We will give it a go.

**Comment by rovinski** [comment]
Also I believe the more standard term for this is "fly lines" 🙂
