### ISSUE TITLE
src/gui/src/scriptWidget.cpp is missing '#include <sys/errno.h>' for EINVAL

### ISSUE THREAD

**Issue by yurivict** [The-OpenROAD-Project/OpenROAD#511]
Please add it.

**Comment by maliberty** [comment]
On which OS was this an issue?

I think it should be #include <errno.h> based on https://man7.org/linux/man-pages/man3/errno.3.html

**Comment by yurivict** [comment]
This is on FreeBSD.

Yes, it should be ```#include <errno.h>```.

**Comment by maliberty** [comment]
I've fixed this and it will show up in our next push to github.
