### ISSUE TITLE
[ICeWall] Invalid "FIXED" nets in the defok files

### ISSUE THREAD

**Issue by ax3ghazy** [The-OpenROAD-Project/OpenROAD#513]
These files have a "FIXED" attribute attached to some of the nets, which doesn't conform to the DEF standard. I am not sure yet how those were output by defout though.

Some examples:
https://github.com/The-OpenROAD-Project/OpenROAD/blob/41a93c7cfbdb35241553540897618108c4a8ccff/src/ICeWall/test/soc_bsg_black_parrot_nangate45.defok#L3879

https://github.com/The-OpenROAD-Project/OpenROAD/blob/openroad/src/ICeWall/test/soc_bsg_black_parrot_nangate45.flipchip.defok#L4030

Also, it's worth noting that there are a couple of "empty" nets (e.g., https://github.com/The-OpenROAD-Project/OpenROAD/blob/openroad/src/ICeWall/test/soc_bsg_black_parrot_nangate45.defok#L3860-L3861).

**Comment by Colin-Holehouse** [comment]
The DEF in these files maches the DEF written out by OpenROAD to confirm the testcase is running as expected.
@maliberty - can you take a look at this from the point of view of the DEF writer

**Comment by maliberty** [comment]
@Colin-Holehouse this looks like a ICeWall issue where it is created a fixed special wire but not assigning any shapes to it.

**Comment by maliberty** [comment]
@ax3ghazy is this resolved?
