### ISSUE TITLE
Build failure: OpenDB/src/zutil/misc_functions.cpp:237:3: error: no matching function for call to 'time'

### ISSUE THREAD

**Issue by yurivict** [The-OpenROAD-Project/OpenROAD#515]
```
/wrkdirs/usr/ports/cad/openroad/work/OpenROAD-0.9.0-beta-637-gc3706485/src/OpenDB/src/zutil/misc_functions.cpp:237:3: error: no matching function for call to 'time'
  time(&wtn);
  ^~~~
/usr/include/time.h:160:8: note: candidate function not viable: no known conversion from 'long *' to 'time_t *' (aka 'int *') for 1st argument
time_t time(time_t *);
       ^
```

The code above isn't in the latest revision of OpenDB.

You might want to update git module's revision in OpenROAD.

**Comment by maliberty** [comment]
It would be helpful if you said which branch you are discussing.  I see that openroad branch (our development branch) is pointed at the head.

**Comment by yurivict** [comment]
I use 0.9.0-beta-637-gc3706485 - the current master branch.

**Comment by osamahammad21** [comment]
@yurivict can you specify which OS are you working on?

**Comment by yurivict** [comment]
> can you specify which OS are you working on?

FreeBSD 12.2
