### ISSUE TITLE
Improve speed of filtering in endpoint slack histogram

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#5162]
### Description

Larger designs can render no filter in seconds and yet it takes as much as an hour to filter regreg, regio, etc.

This is a problem with a larger design I cant provide a public test case for. When I tried with sky130hd/microwatt (largest design in ORFS?), performance for filtering was tolerable.

### Suggested Solution

Improve performance.

**Comment by tspyrou** [comment]
@AcKoucher can you create a standalone openroad testcase that shows the long runtime. This will make it easier to measure the new OpenSTA pathgroups feature speedup that will get implemented.
@oharboe I am working with the OpenSTA author to get cycles on this. We have discussed in detail and agreed on the approach.
