### ISSUE TITLE
how to initialize floorplan

### ISSUE THREAD

**Issue by rajatg123** [The-OpenROAD-Project/OpenROAD#518]
command units uninitialized. Use the read_liberty or set_cmd_units command to set units.
while evaluating {initialize_floorplan -utilization 70 -site FreePDK45_38x28_10R_NP_162NW_340}

**Comment by rovinski** [comment]
The answer is right there. You need to read a liberty file with `read_liberty` or set the units manually with `set_cmd_units`.

**Comment by rajatg123** [comment]
Where I will get liberty file

**Comment by maliberty** [comment]
We provide some platforms in https://github.com/The-OpenROAD-Project/OpenROAD-flow-public
