### ISSUE TITLE
CTS with min & max libraries in TritonCTS

### ISSUE THREAD

**Issue by nickson-jose** [The-OpenROAD-Project/OpenROAD#520]
Is there a facility to build clock tree in Triton CTS using min and max libraries? The example designs and steps in the documentation only show the CTS with typical library.

**Comment by rovinski** [comment]
In terms of optimizing the clock tree for multiple corners? No, we do not have any multi-corner optimization in OpenROAD yet. We only have multi-corner timing available.

It is on our todo list but we have no ETA on that.
