### ISSUE TITLE
Make info message more actionable `[INFO GPL-0100] worst slack -1.54e-09`

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#5203]
### Description

What is OpenROAD trying to tell me here?

Is OpenROAD trying to tell me that removing `-timing_driven` could speed things up?

For architectural exploration, I initially want fast turnaround time with less accurate results.

```
[INFO GPL-0100] worst slack -1.54e-09
[INFO GPL-0103] Weighted 41603 nets.
```

### Suggested Solution

Make the error message more actionable.

**Comment by gudeh** [comment]
Hi @oharboe, this message is not an error message actually. This is printing the worst slack after calling repair design with resizer. Maybe we should transform this into a debug message.

**Comment by oharboe** [comment]
@gudeh  Understood. However, it may be useful for the user to know that they can relax the optimization target to improve running times. If message can be rearticulated to communicate this, it would be helpful.

**Comment by maliberty** [comment]
It seems that having some document or global options on fast analysis is better than sprinkling hints throughout the log

**Comment by oharboe** [comment]
@rovinski Had an idea to collect data on running times vs quality of results and creating a tool that recommended options?

**Comment by gudeh** [comment]
I am closing this issue. I am currently working on the timing driven mode in global placer, which is what generates the mentioned logs. We should have further modifications on timing driven in the near future.
