### ISSUE TITLE
klayout installation error

### ISSUE THREAD

**Issue by honeysh08** [The-OpenROAD-Project/OpenROAD#522]
I tried to install klayout-0.26.8 and faced the following error.

Project ERROR: Unknown module(s) in QT: designer multimedia multimediawidgets xmlpatterns svg

Running build (gmake  all) ..
gmake: *** No targets specified and no makefile found.  Stop.

how do I resolve this?

**Comment by maliberty** [comment]
KLayout is a separate project, you should try their forum at https://www.klayout.de/forum/

It sounds like you have an incomplete Qt installation.
