### ISSUE TITLE
Update `[ERROR PPL-0061] Pins for set_io_pin_constraint command were not found.` to list pins not found

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#5236]
### Description

I removed some pins and now my io constraints file doesn't work.

### Suggested Solution

It would be nice to have the pins that don't exist listed

**Comment by eder-matheus** [comment]
@oharboe I've created a PR with the requested change. Notice that if your list of pins has at least one pin that exists in the design, it will not fail, but warnings will be generated similar to this one: https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/ppl/test/top_layer_error.ok#L6
