### ISSUE TITLE
issue while repairing hold violation on input pin

### ISSUE THREAD

**Issue by quentinw91** [The-OpenROAD-Project/OpenROAD#524]
Hi, 
I am trying to repair a hold violation on an input pin (forced with a negative input delay in the testcase sdc constraint).
[testcase_repair_hold_pin.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/5334743/testcase_repair_hold_pin.zip)

The buffers are connected correctly in the DEF file, because the net name is changed at the PIN definition:

```
PINS 4 ;
    - CLK + NET CLK + DIRECTION INPUT + USE SIGNAL + PLACED ( 200070 201530 ) N + LAYER metal2 ( -70 -70 ) ( 70 70 ) ;
    - IN1 + NET net1 + DIRECTION INPUT + USE SIGNAL + PLACED ( 70 174580 ) N + LAYER metal3 ( -70 -70 ) ( 70 70 ) ;
    - OUT + NET OUT + DIRECTION OUTPUT + USE SIGNAL + PLACED ( 200190 27020 ) N + LAYER metal3 ( -70 -70 ) ( 70 70 ) ;
    - RESETN + NET RESETN + DIRECTION INPUT + USE SIGNAL + PLACED ( 190 70 ) N + LAYER metal2 ( -70 -70 ) ( 70 70 ) ;
END PINS
```
but this causes an issue with the .v file, where the DFF is still connected at the input PIN...

```
module testcase_repair_hold_pin (CLK,
    IN1,
    OUT,
    RESETN);
 input CLK;
 input IN1;
 output OUT;
 input RESETN;

#_2_ should be connected to hold2 output, not IN1
 DFFR_X1 _2_ (.D(IN1),
    .RN(RESETN),
    .CK(CLK),
    .Q(\DLY[0] ),
    .QN(_0_),
    .VDD(VDD),
    .VSS(VSS));
...
#here net1 comes from nowhere, and the hold buffer drives the input pin...
 BUF_X1 hold1 (.A(net1),
    .Z(net2));
 BUF_X1 hold2 (.A(net2),
    .Z(IN1));
```
So the DEF and the .v file do not correspond...
Would it be possible to change the net naming in the buffer insertion, to have the pin name kept at the pin net, and the new net name at the buffer output ?

**Comment by jjcherry56** [comment]
Your testcase works in the latest release of openroad. But it turns out the problem just migrated to output ports. I fixed this and some similar issues in the following commit.
6c121963 Merge pull request #207 from The-OpenROAD-Project-private/resize_net_names
