### ISSUE TITLE
Multiple warnings with ihp-sg13g2/aes on master

### ISSUE THREAD

**Issue by gudeh** [The-OpenROAD-Project/OpenROAD#5290]
### Describe the bug

This warning is surpassing the maximum allowed: `[WARNING GRT-0041] Net VSS has wires/vias outside die area`.
They seem to happen during grt stage, after cts is finished.

We do seem to have the power grid outside the die area:

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/37420320/5da69611-dfd5-4d27-b354-5a4452c9fa57)
 

### Expected Behavior

Not print warnings.

### Environment

```shell
They are happening on master, in jenkins also.
```

### To Reproduce

download the artifacts from jenkins nightly.

**Comment by gudeh** [comment]
If someone would like to point out what can be done to fix, I can try it myself.

**Comment by maliberty** [comment]
It looks like the pdn setup for the outside ring has a core offset that exceeds the core spacing in the design config

**Comment by gudeh** [comment]
I tried changing the following parameters but I see the same PDN after floorplan:
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/37420320/e6300847-7ac4-4949-a076-8f19eba075dd)

**Comment by gudeh** [comment]
This design's config.mk file is the following, I am not sure if this parameters would impact the PDN:
```
export DESIGN_NICKNAME = aes
export DESIGN_NAME = aes_cipher_top
export PLATFORM    = ihp-sg13g2

export VERILOG_FILES = $(sort $(wildcard ./designs/src/$(DESIGN_NICKNAME)/*.v))
export SDC_FILE      = ./designs/$(PLATFORM)/$(DESIGN_NICKNAME)/constraint.sdc

export CORE_UTILIZATION = 20 
export CORE_ASPECT_RATIO = 1
export CORE_MARGIN = 2

export PLACE_DENSITY = 0.65
export TNS_END_PERCENT = 100

export USE_FILL = 1

```

**Comment by gudeh** [comment]
This is what we get with master now:
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/37420320/7509843c-dff7-45e7-b9c0-8990dc58902b)
