### ISSUE TITLE
RePlAce crash

### ISSUE THREAD

**Issue by thesourcerer8** [The-OpenROAD-Project/OpenROAD#532]
I am trying to build my caravel/openlane based design: https://github.com/thesourcerer8/caravel-stdcelllib-stdcells/ and I am getting a crash in the placement:
http://pdk.libresilicon.com/caravel-build4.html

**Comment by maliberty** [comment]
Please provide a packaged up test case or a set of steps to run in order to reproduce the crash.  Its not obvious how to do so from a url.

**Comment by rovinski** [comment]
It should be noted the OpenROAD version used is 2 months old.

**Comment by maliberty** [comment]
No testcase.
