### ISSUE TITLE
Harsh error message

### ISSUE THREAD

**Issue by thesourcerer8** [The-OpenROAD-Project/OpenROAD#533]
In openlane we get the error messages
Error: cannot open '/.openroad'.
and in opensta:
Error: cannot open '/.sta'
When I changed $HOME to /home/philippX then I get this error message: Error: cannot open '/home/philippX/.openroad'.
So openroad and sta are trying to read user-defined configurations.
From my point of view, these missing directories should create a warning instead of an error.

**Comment by jjcherry56** [comment]
fixed in opensta
4ed9f0e7 no error on missing init file
openroad
1abe4c77 no error on missing init file
