### ISSUE TITLE
drc takes surprisingly long with fuzzed yosys input

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#5388]
### Describe the bug

This is from https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2142 where detailed route went from ca. 2 hours to ca. 2 days. The only change is that the synthesis input is fuzzed. Very slightly different initial conditions to Yosys causes slightly different yosys output.

untar [drc-slow.tar.gz](https://github.com/user-attachments/files/16264418/drc-slow.tar.gz)

```
./run-me-riscv32i-sky130hs-base.sh
```

After a while, it no longer converges. Notice that all the time is spent in the 90-100% on 37 violations.

I don't know if it eventually finds resolves all the violations.

```
OpenROAD v2.0-14511-gedb4e7e37
[deleted]
[INFO DRT-0195] Start 55th optimization iteration.
    Completing 10% with 37 violations.
    elapsed time = 00:00:00, memory = 3372.71 (MB).
    Completing 20% with 37 violations.
    elapsed time = 00:00:00, memory = 3372.71 (MB).
    Completing 30% with 37 violations.
    elapsed time = 00:00:00, memory = 3372.71 (MB).
    Completing 40% with 37 violations.
    elapsed time = 00:00:00, memory = 3372.71 (MB).
    Completing 50% with 37 violations.
    elapsed time = 00:00:00, memory = 3372.71 (MB).
    Completing 60% with 37 violations.
    elapsed time = 00:00:00, memory = 3372.71 (MB).
    Completing 70% with 37 violations.
    elapsed time = 00:00:00, memory = 3372.71 (MB).
    Completing 80% with 37 violations.
    elapsed time = 00:00:00, memory = 3372.71 (MB).
    Completing 90% with 37 violations.
    elapsed time = 00:00:00, memory = 3372.71 (MB).
    Completing 100% with 37 violations.
    elapsed time = 00:21:32, memory = 3372.67 (MB).
[INFO DRT-0199]   Number of violations = 37.
Viol/Layer        met1   met2
Metal Spacing        2      0
Short               24     11
[INFO DRT-0267] cpu time = 00:21:32, elapsed time = 00:21:32, memory = 3372.67 (MB), peak = 3932.95 (MB)
```

### Expected Behavior

Converge reasonably quickly or give up on hopeless problems

### Environment

```shell
OpenROAD v2.0-14511-gedb4e7e37
```

### To Reproduce

See above

**Comment by eder-matheus** [comment]
As mentioned in https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2142, this is more of a GRT problem than DRT. The input guides are bad due to a wrong configuration for resource reductions.

**Comment by oharboe** [comment]
It would be nice if detailed routing gave up more quickly on hopeless cases. Is this test-case interesting in that regard or should it just be closed?

**Comment by eder-matheus** [comment]
> It would be nice if detailed routing gave up more quickly on hopeless cases. Is this test-case interesting in that regard or should it just be closed?

That's a good point. I think we can keep this issue open to keep track of it. I have the artifacts of the design downloaded, so I can investigate it.

**Comment by oharboe** [comment]
@eder-matheus Perhaps you can file a new github issue using the test-case of this one so that it is more obvious what feature is being requested?

There is no need to read over and over again the history of this issue since it is now "solved".

**Comment by maliberty** [comment]
Its hard to know what's hopeless.  Sometimes it finishes on iter 50.
