### ISSUE TITLE
Add find by name to CTS viewer

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#5463]
### Description

To track:

From @precisionmoon `We want to find a register by name in the main GUI and see the matching sink in the clock tree viewer.`

### Suggested Solution

From @gadfort `It should be fairly easy to implement since you can piggy-back on the inspect connection to emit a second call to a sink in the viewer that can highlight it.`

**Comment by maliberty** [comment]
@gadfort do you want to tackle this or should I pass to @AcKoucher ?

**Comment by gadfort** [comment]
@maliberty if @AcKoucher has time that would probably be best right now.

**Comment by maliberty** [comment]
@AcKoucher please help @LucasYuki with this as a first project.

**Comment by AcKoucher** [comment]
Should we have a "Find" option exclusively for the ClockTreeViewer or this sink highlighting should be triggered by the main window "Find"?

**Comment by maliberty** [comment]
I think the existing find mechanism is fine.  The CTS viewer should just listen for selection in a similar fashion to the layout viewer.

**Comment by LucasYuki** [comment]
While talking to @arthurjolo and @AcKoucher we have the following question:

The existing find mechanism can find multiple instances in one search.
In this case, how is the CTS viewer expected to behave?

What if we implement in the inspector a button, or an option with the right-click menu, to "find in the CTS viewer"?

**Comment by maliberty** [comment]
Is there a reason we couldn't support multi-select in the CTS viewer?  When you get a select you zoom to the bounds of the selected object(s).
