### ISSUE TITLE
Ruler cannot snap to via enclosures when debugging pin access

### ISSUE THREAD

**Issue by titan73** [The-OpenROAD-Project/OpenROAD#5465]
### Describe the bug

The ruler can snap to the green site boundary and the edges of the metal1 pin (blue shape which goes to the top of the picture).
However it's impossible to snap to the via metal1 via enclosure  (in blue) and metal2 via enclosure (in red). Same for the yellow marker.
So it's not possible to mesure the distance and understand the debug messages as the ruler cannot measure distance freely (without snapping).

<img width="294" alt="via" src="https://github.com/user-attachments/assets/85110519-33e0-4018-9646-030357ccfa40">

### Expected Behavior

This is an enhancement request

### Environment

```shell
Latest git version. Ubuntu.
```

### To Reproduce

Pin access issue debugged with detailed_route_debug.

**Comment by maliberty** [comment]
The via is a temporary object inside the router and though we draw it as a graphic it doesn't exist in the db so there is nothing to snap to.  There is no plan to enhance the debug graphics for this purpose.
