### ISSUE TITLE
Make the ruler more flexible

### ISSUE THREAD

**Issue by titan73** [The-OpenROAD-Project/OpenROAD#5471]
### Description

With the current ruler, making a measurement requires to snap to 2 edges. Unfortunately in some cases and particularly in debug mode where we deal with temporary object, there is not way to do a measurement and it's not practical at all. That would be really convenient to chooses arbitrary locations. This is possible with commercial tool such as Innovus and Calibre.

### Suggested Solution

To be defines. In Calibre, there is a option to choose arbitrary location. With Innovus, it's mixed. We can choose arbitrary locations and when we're close to an edge, the tool snap to it.

**Comment by maliberty** [comment]
You can do that with ctrl-click

**Comment by titan73** [comment]
Just tried. Great. Thanks!
