### ISSUE TITLE
Make it easier to use `./build_openroad --local` with local changes

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#5564]
### Description

Use-case: I want to modify e.g. tools/OpenROAD or tools/OpenROAD/src/sta (a submodule), build and try it locally.

I would have expected `./build_openroad.sh --local` to allow this, but it will fail do this, but it will fail with:

```
$ ./build_openroad.sh --local
[INFO FLW-0028] Compiling with 20 threads.
[INFO FLW-0027] Saving logs to build_openroad.log
[INFO FLW-0028] ./build_openroad.sh --local
[INFO FLW-0002] Updating git submodules.
error: Your local changes to the following files would be overwritten by checkout:
	sdc/Sdc.tcl
Please commit your changes or stash them before you switch branches.
Aborting
fatal: Unable to checkout 'cf4bd0523330a7a4989fd9ea9957a55bc2d90187' in submodule path 'tools/OpenROAD/src/sta'
fatal: Failed to recurse into submodule path 'tools/OpenROAD'
```

### Suggested Solution

It is surprising to me that `./build_openroad.sh` checks out the current version and tries to overwrite local changes. My expecation from other projects that I use, is that checking out and modifying code is not linked to building, the build scripts just builds, it doesn't check out or modify versions.

Suggested change:

My preference would be an option `--current` that does the same as today, build with currently checked out ORFS and the OpenROAD module(and submodules) for that ORFS version. This is along the lines of the `--latest` option that checks out the latest OpenROAD with the current ORFS.

Without any options, I suggest that `./build_openroad.sh` compiles whatever is checked out and modified.

If it is a lot to ask to change the current interface in `./build_openroad.sh`, then I propose a new option to allow compiling locally checked out and modified code, for the lack of a better suggestion a `--modified` option.

**Comment by eder-matheus** [comment]
In ORFS, we have the `--no_init` flag that will preserve any modifications you have in the OpenROAD submodule.
