### ISSUE TITLE
Pin Overlapping Issue with Power Switch Cells in Sky130 Library

### ISSUE THREAD

**Issue by bingyuew** [The-OpenROAD-Project/OpenROAD#5583]
### Description

The power switch described here: [src/pdn/test/sky130_power_switch/power_switch.lef](https://github.com/The-OpenROAD-Project/OpenROAD/blob/bf8a6a7a1c86511cbcfd56556743d1af4c0f2ac0/src/pdn/test/sky130_power_switch/power_switch.lef) has an overlap between the VDDG and SLEEP_OUT pins. 

![image](https://github.com/user-attachments/assets/37b2d591-eac9-49be-a479-51e0f6e819ca)

This overlap will cause an error during pin access in the routing stage. Furthermore, the test script located at https://github.com/The-OpenROAD-Project/OpenROAD/blob/bf8a6a7a1c86511cbcfd56556743d1af4c0f2ac0/src/pdn/test/power_switch_daisy.tcl appears to be incorrect due to this issue.

**Comment by maliberty** [comment]
@gadfort any comments?

**Comment by gadfort** [comment]
@maliberty the pin is overlapping (I can fix that although it doesn't matter for PDNs sake). I'm not sure what @bingyuew means by the tcl script is invalid.

**Comment by maliberty** [comment]
The script mentioned is a unit test that only runs pdn.  It would be problematic to routing if we were running it.  Is that the concern?

**Comment by vikrg23** [comment]
Hi @gadfort , I work with @bingyuew  , sorry the tcl script is not the issue, we misunderstood. Just the overlap in the power switch LEF is the issue. Thanks.

**Comment by maliberty** [comment]
In that case it looks like this is resolved by https://github.com/The-OpenROAD-Project/OpenROAD/pull/5586
