### ISSUE TITLE
Warning / error in floorplan

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#5584]
Untar https://drive.google.com/file/d/1893fWw-vCFPkQY1swQF68vDPSkCdcIay/view?usp=sharing

Interesting: this is a warning about an error... Normally something is either a warning or an error.

```
$ ./run-me-BoomTile-asap7-base.sh 
OpenROAD v2.0-15055-gdb7d56e4d 
Features included (+) or not (-): +Charts +GPU +GUI +Python
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
[INFO ODB-0227] LEF file: /home/oyvind/megaboom/foo/platforms/asap7/lef/asap7_tech_1x_201209.lef, created 24 layers, 9 vias
[INFO ODB-0227] LEF file: /home/oyvind/megaboom/foo/platforms/asap7/lef/asap7sc7p5t_28_R_1x_220121a.lef, created 212 library cells
[WARNING ODB-0177] error: undefined via (VIA45_1_2_58_58) referenced
[WARNING ODB-0177] error: undefined via (VIA45_1_2_58_58) referenced
[rest deleted]
```

_Originally posted by @oharboe in https://github.com/The-OpenROAD-Project/bazel-orfs/issues/99#issuecomment-2290597986_

**Comment by oharboe** [comment]
@jeffng-or FYI

**Comment by maliberty** [comment]
We want to generate a full set of problems rather than stop on the first one (similar to c++ compilation).  So we give warnings and then error at the end.

**Comment by oharboe** [comment]
@maliberty Makes sense now that I know this, maybe the output could make it more clear? No specific suggestions.

**Comment by maliberty** [comment]
Is ebtb_128x40.lef new?  It seems like this would always have been a problem.

**Comment by oharboe** [comment]
> Is ebtb_128x40.lef new? It seems like this would always have been a problem.

Yes, generated same [version](https://github.com/The-OpenROAD-Project/megaboom/blob/cf6c7eecc80183e3526e2d821d7f9013acbe880e/MODULE.bazel#L27) as megaboom

**Comment by oharboe** [comment]
@maliberty Helpful? 

[pdn_ebtb_128x40_asap7_base_2024-08-15_16-05.tar.gz](https://github.com/user-attachments/files/16625995/pdn_ebtb_128x40_asap7_base_2024-08-15_16-05.tar.gz)

**Comment by maliberty** [comment]
@gadfort not properly in what way?  I do see it in the .lef but we only read vias from the tech lef today.

**Comment by maliberty** [comment]
@gadfort I see we read vias if they have a via rule but these vias don't.  I'm guessing this relates to your recent pdn change.  Thoughts?

**Comment by gadfort** [comment]
Since that via is a block via, the abstract lef would have to write it out as boxes instead of referencing it by name

**Comment by gadfort** [comment]
I don't immediately see how it was included in the lef from https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/odb/src/lefout/lefout.cpp (it looks like the shapes should have been extracted)

**Comment by maliberty** [comment]
From the LEF manual
```
If a LEF MACRO block needs its own locally defined VIA definition that is not already defined,
it should use a unique via name. One way to do so is to use the MACRO name in the VIA
definition name. For example, MACRO my_block1 might have a unique via named VIA
my_block1_via1 inside the same LEF file.
```
so it sounds like there is an intention that LEF could have extra vias.

**Comment by maliberty** [comment]
I presume it can from lefout::writeBlockVia

**Comment by gadfort** [comment]
we don't do the name ubiquitination which would be a good idea. Do macro lef vias get added to the techvias during lefin?

**Comment by maliberty** [comment]
No that's the issue here:
```
void lefin::via(lefiVia* via, dbTechNonDefaultRule* rule)
{
  if (!_create_tech && !via->hasViaRule()) {
    return;
  }
```
The question is should we add them as dbTechVia - it seems we should and just remove the if.  Agree?

**Comment by maliberty** [comment]
(We hit this earlier with viarule in https://github.com/The-OpenROAD-Project/OpenROAD/commit/0728be75e10f0cfbb8d18a3e4ddc1300a9eff291)

**Comment by gadfort** [comment]
@maliberty I think they should just be added to the Tech (if there is an issue in the future they could tagged as foreign vias).  If we do add them I think it makes sense to follow the LEF guidance about making the names unique
