### ISSUE TITLE
Printing messages to stderr?

### ISSUE THREAD

**Issue by aolofsson** [The-OpenROAD-Project/OpenROAD#559]
I am getting a small set of messages printed to stderr that seem like the would be more appropriate for stdout considering the rest of the openroad messages.

Notice 0: Reading LEF file:  nangate45.tech.lef
Notice 0:     Created 22 technology layers
Notice 0:     Created 27 technology vias
Notice 0: Finished LEF file:  nangate45.tech.lef
Notice 0: Reading LEF file:  NangateOpenCellLibrary.macro.lef
Notice 0:     Created 134 library cells
Notice 0: Finished LEF file:  .....

Seems like the "info" messages are coming from the following file:

https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/OpenDB/src/lefin/lefin.cpp

Not a big deal...but it's different from all the other messages printed in openroad.

**Comment by maliberty** [comment]
We are going through a major transition into standardized logging facilities.  OpenDB has not yet been converted but when it has this should be resolved.
