### ISSUE TITLE
DRT creates redundant arc net when connecting to reconfigurable cell

### ISSUE THREAD

**Issue by titan73** [The-OpenROAD-Project/OpenROAD#5607]
### Describe the bug

The cell is reconfigurable. Its base layers are the same and the function can be changed with different metal2 connections.

Interesting area are show in orange.

DRT tries to connect to the Q pins of the cell:

<img width="352" alt="cell" src="https://github.com/user-attachments/assets/7efabb73-d517-4b04-af4b-533a778e0c28">

Since the Q pins are connected together in the cell with metal2, DRT connects to the metal2 shape

<img width="352" alt="routing" src="https://github.com/user-attachments/assets/1e26737c-60bb-40a0-b2e9-98d176661d35">

But the router create a useless arc wich causes a min hole violation.

<img width="352" alt="arc" src="https://github.com/user-attachments/assets/e3421544-69d5-42ce-b311-ee48e7093736">

This happens often. I have around 100 violations like this in my desgin.

I can try to make a testcase if needed.

### Expected Behavior

No redundant arc

### Environment

```shell
penROAD v2.0-15230-g858535dfe
```

### To Reproduce

No testcase yet

**Comment by maliberty** [comment]
Its hard to say much without a test case.

**Comment by titan73** [comment]
I reproduce the issue in a test case:

[arc.zip](https://github.com/user-attachments/files/16747119/arc.zip)

**Comment by titan73** [comment]
Any news on this issue?

**Comment by titan73** [comment]
Why closing this issue without any explanation? A test case is provided.

**Comment by maliberty** [comment]
The issue was fixed and you can see the link to the fixing commit above.

**Comment by titan73** [comment]
Oups sorry. Didn't pay attention. :s I'll test the fix. Thanks for fixing.
