### ISSUE TITLE
DRT io/io_guide.cpp refactor

### ISSUE THREAD

**Issue by osamahammad21** [The-OpenROAD-Project/OpenROAD#5612]
### Description

Refactor code for guide processing in src/drt/src/io/
The following image shows the code complexity of io_guide.cpp
![image](https://github.com/user-attachments/assets/c41d9332-61f0-43f1-8e99-184b8a3d5d10)

**Comment by maliberty** [comment]
are you using https://github.com/terryyin/lizard ?

**Comment by osamahammad21** [comment]
> are you using https://github.com/terryyin/lizard ?

yes

**Comment by osamahammad21** [comment]
![Image](https://github.com/user-attachments/assets/f0afcd65-d0eb-4789-9c12-b49e194bf44a)
