### ISSUE TITLE
Tapping distance not being strictly applied

### ISSUE THREAD

**Issue by ax3ghazy** [The-OpenROAD-Project/OpenROAD#562]
The attached test case specifies a 14um tapping distance, which is not being strictly applied

[tapping_distance_issue.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/5797974/tapping_distance_issue.tar.gz)

To reproduce, run the attached script and check the distances between taps/end-caps, which exceed the specified 14um.

Moreover, it's not completely clear to me what type of tap spacing rule is being targeted by the tool, but I believe that
it should eventually implement (or support) the worst case scenario (end-of-tap to end-of-cell spacing).

![screenshot_20210111_21-36-16](https://user-images.githubusercontent.com/19731159/104229515-0c490f00-5455-11eb-9aaf-699e09280c29.png)

**Comment by eder-matheus** [comment]
The fix for this issue is already available at the master branch.

**Comment by ax3ghazy** [comment]
The fix improves things, but the same test case still fails (distance is still being above the specified 14um).

![screenshot_20210217_13-31-21](https://user-images.githubusercontent.com/19731159/108198544-7031b800-7124-11eb-8043-918a269821ac.png)
