### ISSUE TITLE
Incorrect LEF generated when there are pins with names that are similar to cell name

### ISSUE THREAD

**Issue by ayeung-fw** [The-OpenROAD-Project/OpenROAD#563]
When your cell name (e.g. abc) is part of the name of the pins (such as abc_data), mergeLef.py would generate an incorrect LEF:
![image](https://user-images.githubusercontent.com/73253857/104777839-43f3d780-5731-11eb-97a7-67255c577741.png)

**Comment by maliberty** [comment]
Note that this script also exists in openroad-flow-scripts too when fixing.

**Comment by tspyrou** [comment]
Ibrahim can you fix this script?

**Comment by ibrahimkhairy** [comment]
Hi Tom, 
Sure, I'll have a look

**Comment by ibrahimkhairy** [comment]
#587  Pull request should address this issue, please let me know if you have any further concerns
