### ISSUE TITLE
Pruning short rows after row cutting

### ISSUE THREAD

**Issue by donn** [The-OpenROAD-Project/OpenROAD#5648]
### Description

After `cut_rows`, some of the remaining rows may be too small and  unable to be connected to a PDN (see top right.)

![Screenshot 2024-08-25 at 20 47 56](https://github.com/user-attachments/assets/20026460-809d-44f2-96d0-461cb9e15fc5)

This would normally be addressed with just placing the macro a bit to the left, but there's no way around this for `mpl2`-based macro placements.

### Suggested Solution

`cut_rows` could take an argument to eliminate any rows that are shorter than a given threshold.

**Comment by maliberty** [comment]
We could add that.  It could be possible to setup a pdn that would cover that region depending how dense the stripes are.
