### ISSUE TITLE
SRAM compiler

### ISSUE THREAD

**Issue by stephenry** [The-OpenROAD-Project/OpenROAD#569]
Thank you for the work that you are doing. A question: for the Skywater-PDK, do free SRAM compilers exist that support the OpenROAD flow? VLSIDA/OpenRAM does not appear to support Skywater and I see that you folks have a "fake ram" module that looks like a single ported SRAM. Just wondering what people are using.

**Comment by mithro** [comment]
OpenRAM should support SkyWater "real soon now" -- please poke @mguthaus about the current status.

**Comment by maliberty** [comment]
I think this is more in the scope of openlane (https://github.com/efabless/openlane) as openroad itself doesn't provide this functionality.
