### ISSUE TITLE
gds read/write corruption (SREF)

### ISSUE THREAD

**Issue by beantowel** [The-OpenROAD-Project/OpenROAD#5813]
### Describe the bug

using the `GDSReader` and `GDSWriter` to test on some file created by `klayout`. The reader reports "corruption, expect XY...". And the `klayout` also reports "corruption" on file written by GDSWriter.

### Expected Behavior

After this process:

`klayout` create file -> GDSReader -> GDSWriter -> `klayout` read file

we shall get the same layout file (clean XOR result) 

### Environment

```shell
Linux 3.10.0
cmake 3.27.2
CXX compiler GNU 9.5.0
anyway, this doesn't matter
```

### To Reproduce

read/write a gds file with SREF record: [lib_test.gds](https://github.com/KLayout/klayout/blob/master/testdata/gds/lib_test.gds)

### Additional Context

I suggest the fix is:

```powershell
>git diff
diff --git a/src/odb/src/gdsin/gdsin.cpp b/src/odb/src/gdsin/gdsin.cpp
index 7e5804d..3affd59 100644
--- a/src/odb/src/gdsin/gdsin.cpp
+++ b/src/odb/src/gdsin/gdsin.cpp
@@ -397,9 +397,9 @@ dbGDSElement* GDSReader::processSRef()
     sref->_transform = processSTrans();
   }

-  readRecord();
   if (_r.type == RecordType::COLROW) {
     sref->_colRow = {_r.data16[0], _r.data16[1]};
+    readRecord();
   } else {
     sref->_colRow = {1, 1};
   }
diff --git a/src/odb/src/gdsin/gdsout.cpp b/src/odb/src/gdsin/gdsout.cpp
index fb8db0f..460642e 100644
--- a/src/odb/src/gdsin/gdsout.cpp
+++ b/src/odb/src/gdsin/gdsout.cpp
@@ -361,7 +361,6 @@ void GDSWriter::writeSRef(dbGDSSRef* sref)
   } else {
     r.type = RecordType::AREF;
   }
-  r.type = RecordType::SREF;
   r.dataType = DataType::NO_DATA;
   writeRecord(r);
```

**Comment by maliberty** [comment]
Thanks.  Do you have the klayout script to perform the xor comparison?

You could also have opened a PR since you already know the fix.
