### ISSUE TITLE
pgpins with name ending with ! (inherit) are not supported in liberty files

### ISSUE THREAD

**Issue by titan73** [The-OpenROAD-Project/OpenROAD#5831]
### Describe the bug

When reading .lib with e.g voltage_map(vdd!, 1.55);
The following error occurs:
[ERROR STA-0026] xxx.lib line 82, syntax error

### Expected Behavior

No error

### Environment

```shell
Latest version
```

### To Reproduce

Take whatever test case with modified .lib with ! on a pgpins.

**Comment by titan73** [comment]
Note that lef parser does not complain.

**Comment by titan73** [comment]
Ah. liberty parser seems to be in OpenSTA. Should I create a issue or move this one there?

**Comment by maliberty** [comment]
Create an issue in https://github.com/parallaxsw/OpenSTA

**Comment by maliberty** [comment]
Be sure to include a small test case

**Comment by titan73** [comment]
> Create an issue in https://github.com/parallaxsw/OpenSTA

Ok. I'll do that.

So once it fixed there, how long will it take to get integrated in https://github.com/The-OpenROAD-Project/OpenSTA which OR uses?

Btw, how is it that https://github.com/The-OpenROAD-Project/OpenSTA is not a fork of the parallaxsw repo?

**Comment by maliberty** [comment]
It varies, we tend to pull sta when needed.  You can always request an update.

Its not a fork for historical reasons.  Don't file issues there.
