### ISSUE TITLE
invalid macro placement leads to detailed routing problems with pins on more than one metal layer

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#5854]
### Describe the bug

Standalone bugreports broken out from https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2412

untar [detail-route-problem-with-pins-on-multiple-metals.tar.gz](https://github.com/user-attachments/files/17232782/detail-route-problem-with-pins-on-multiple-metals.tar.gz)

Detailed routing eventually completes with lots of DRC errors:

```
$ ./run-me-mock-array-asap7-base.sh 
OpenROAD v2.0-16219-g56c3c86ba 
[deleted]
[WARNING DRT-0418] Term ces_0_0/clock has no pins on routing grid
[WARNING DRT-0418] Term ces_0_0/io_ins_down[0] has no pins on routing grid
[WARNING DRT-0418] Term ces_0_0/io_ins_down[10] has no pins on routing grid
[lots]
[deleted]
```

The root cause might be macro placement, broken out as a standalone test here:

[macro-place-multi-metal-pins.tar.gz](https://github.com/user-attachments/files/17232833/macro-place-multi-metal-pins.tar.gz)

```
$ ./run-me-mock-array-asap7-base.sh 
OpenROAD v2.0-16219-g56c3c86ba 
Features included (+) or not (-): +Charts +GPU +GUI +Python
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
HierRTLMP Flow enabled...
rtl_macro_placer -halo_width 0 -halo_height 2.16 -boundary_weight 0 -report_directory ./objects/asap7/mock-array/base/rtlmp -target_util 0.30
Floorplan Outline: (0.0, 0.0) (358.56, 388.8),  Core Outline: (2.16, 2.16) (356.4, 386.64)
	Number of std cell instances: 129
	Area of std cell instances: 23.37
	Number of macros: 64
	Area of macros: 119439.39
	Halo width: 0.00
	Halo height: 2.16
	Area of macros with halos: 131383.38
	Area of std cell instances + Area of macros: 119462.77
	Core area: 136198.20
	Design Utilization: 0.88
	Core Utilization: 0.00
	Manufacturing Grid: 1

openroad> 
```

### Expected Behavior

No error

### Environment

```shell
OpenROAD v2.0-16219-g56c3c86ba
```

### To Reproduce

See above

**Comment by maliberty** [comment]
@AcKoucher I suspect that the snapping the macro so the pins are on the routing grid may need some enhancing in the case where we have pins on multiple layers for H & V.
