### ISSUE TITLE
2021.03.09 unnecessarily installs bundled OpenSTA project

### ISSUE THREAD

**Issue by yurivict** [The-OpenROAD-Project/OpenROAD#597]
It installs ```include/sta/*``` and ```lib/libOpenSTA.a``` files that are only needed during build.

**Comment by maliberty** [comment]
@jjcherry56 could we conditionalize the install (only when standalone?)

**Comment by yurivict** [comment]
It probably shouldn't ever be installed when OpenSTA is used as a bundled project.

**Comment by maliberty** [comment]
Refile with https://github.com/parallaxsw/OpenSTA if still relevant as no mechanism exists there to support this request.
