### ISSUE TITLE
[ERROR STA-0572] -setup_margin '-500' is not a positive float.

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#6001]
### Description

Negative setup margin is useful to pick a clock period that is fixed and at the target speed while developing and adjusting the setup margin from negative to 0 as one is working towards better quality of results.

A negative setup margin will should cause the retiming to exit early when spending more time on retiming is futile.

```
repair_timing -verbose -setup_margin -500 -repair_tns 100 -skip_last_gasp
[ERROR STA-0572] -setup_margin '-500' is not a positive float.
Error: floorplan.tcl, 112 STA-0572
```

### Suggested Solution

Allow negative setup and hold margins

**Comment by maliberty** [comment]
@eder-matheus please allow negative values here

**Comment by oharboe** [comment]
@maliberty Also for HOLD_SLACK_MARGIN: a negative value can speed up the build while "flushing the pipe" and keeping the target clock rate constant + it is easier to sweep(try different values) of HOLD_SLACK_MARGIN than clock period/set_input_delay.
