### ISSUE TITLE
Loading congestion.rpt for global route appears to do nothing

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#6035]
### Describe the bug

1. load congestion.rpt
2. Nothing appears to happen
3. Select DRC from dropdown
4. DRCs are now available

![image](https://github.com/user-attachments/assets/9e654bc9-2e41-4fd6-932c-7230a16d354d)

![image](https://github.com/user-attachments/assets/a1826530-297f-45c7-9b63-16bdca3b4213)

### Expected Behavior

Switch to the first dropdown selection that has any DRCs in it

### Environment

```shell
OpenROAD v2.0-16787-gcd519bb5e
```

### To Reproduce

I think the instructions above should be clear, if not there really should be a way in ORFS to easily test this part of the GUI.

**Comment by maliberty** [comment]
@gadfort I've noticed this too as a minor usability issue.  Do you have time to look at it?
