### ISSUE TITLE
OpenRCX SEGV in extMain::addRCCorner() due to Logger issues

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenROAD#608]
I tried enabling OpenRCX and I got a SEGV in `extMain::addRCCorner()`. The `logger_` pointer doesn't match the pointer in the calling function (`Ext::define_process_corner()`). Assuming it should match, something needs to either update it, or pass in the logger pointer.

**Comment by GeraldoPradipta** [comment]
I will take a look into this.

**Comment by jjcherry56** [comment]
I am already way deep into fixing it. Whoever wrote the initialization code was seriously confused.

**Comment by jjcherry56** [comment]
This was fixed by 12dd3fc61
