### ISSUE TITLE
report_power hangs, loops continually through a subset of cells

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenROAD#610]
The following test case: [report_power-hang.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/6201614/report_power-hang.tar.gz) gets stuck in `report_power`. Adding some debug shows it looping continually through the same 336 standard cells.

**Comment by jjcherry56** [comment]
fixed by c9bb911c sta power activity prop with latches
