### ISSUE TITLE
gui: M2 tracks are not visible when Nets->Signal is checked

### ISSUE THREAD

**Issue by titan73** [The-OpenROAD-Project/OpenROAD#6114]
### Describe the bug

As described in the title.

### Expected Behavior

Should be visible.

### Environment

```shell
v2.0-16855-ga15114a95
```

### To Reproduce

Use test case from https://github.com/The-OpenROAD-Project/OpenROAD/issues/6097.

Execute script until line "place_pins -hor_layers M3 -ver_layers M2" included.
Show only layer M then enable tracks visualisation. Nothing visible.
Unchecked Nets->Signal and M2 tracks appears.
Before "place_pins ..." things work correctly.

**Comment by gadfort** [comment]
@titan73 pictures might be helpful in describing this issue.

**Comment by maliberty** [comment]
Shape Types/Pins has a similar effect:
![image](https://github.com/user-attachments/assets/19bc0097-9eb0-4901-aea9-776774fb4b66)

**Comment by gadfort** [comment]
@maliberty yeah, I'll take a stab at this

**Comment by titan73** [comment]
Thanks for the fix.
