### ISSUE TITLE
odb: write_odb fails with not so pretty iostream message

### ISSUE THREAD

**Issue by titan73** [The-OpenROAD-Project/OpenROAD#6120]
### Describe the bug

See title.

### Expected Behavior

write_db should succeed.

### Environment

```shell
v2.0-16855-ga15114a95
```

### To Reproduce

openroad test.tcl

[write_db.zip](https://github.com/user-attachments/files/17669683/write_db.zip)

**Comment by eder-matheus** [comment]
@titan73 If I manually create the dbs directory, the command don't fail. I'm not sure if any of our write commands should create directories. @maliberty any comments?

**Comment by titan73** [comment]
@eder-matheus yeah indeed I've just figured out that dbs folder was removed but the error message was not very helpful and I couldn't pinpoint the problem. I don't expect write_db to create the folder that that would be good to have a error message complaining about the missing "dbs" folder.

**Comment by maliberty** [comment]
What was the message?

**Comment by maliberty** [comment]
I don't think there is any change here so "anymore" seems inaccurate.

**Comment by eder-matheus** [comment]
> What was the message?

@maliberty This: `Error: test.tcl, 8 basic_ios::clear: iostream error (failed to open 'dbs/floorplan.odb.1'): iostream error`.

My guess is that we are not checking if the file was properly created before trying to write to it.

**Comment by maliberty** [comment]
"failed to open" is pretty clear that it is a file system error but we could make it prettier.

**Comment by titan73** [comment]
Updated title.

Indeed the message says what's wrong. I got confused with its complicated message (like an assert) and thought there was a bug.
So nothing wrong actually but yes a better message could be nice.
Btw is this message sent to the logger?
And I don't understand. The message refers to file 'dbs/floorplan.odb.1' but the file is 'dbs/floorplan.odb'. What is this '.1'?

**Comment by titan73** [comment]
Fixed  by merged PR https://github.com/The-OpenROAD-Project/OpenROAD/pull/6133.
