### ISSUE TITLE
gui: drc violation blinking disappears after selecting violation in drc viewer

### ISSUE THREAD

**Issue by titan73** [The-OpenROAD-Project/OpenROAD#6149]
### Describe the bug

In drc viewer, mousing over a violation make it highlighted with blinking yellow in the renderer but when clicking on this very violation the highlighting disappears. That would be more natural to keep it highlighted.

In addition to this issue a possible enhancement could be to keep the selected violation highlighted when mouse cursor is not on any violations.

### Expected Behavior

Highlight is kept when clicking on a violation.

### Environment

```shell
v2.0-16941-g1452788e1
```

### To Reproduce

Whatever design with drc violations.

**Comment by titan73** [comment]
You can assigned it to me. I have make it working and will send a PR.

**Comment by gadfort** [comment]
@titan73 do you have `highlight selected` turned off?

**Comment by titan73** [comment]
Yes it was was off. I turned it on. The selection becomes yellow but there is not blinking like we have with the mouse over.

**Comment by titan73** [comment]
@gadfort Should we still keep this issue opened?
As you said in related PR:
`It seems like this exposes and masks some odd behavior of the GUI, but in the short run it seems fine. I think we should keep the issue open to track fixing the inspector animation behavior.`
Shouldn't we close this issue and open a new one for other issues?

**Comment by maliberty** [comment]
What was the related PR?  I see nothing to fix here.  If there is another issue please open a new one.

**Comment by titan73** [comment]
> What was the related PR? I see nothing to fix here. If there is another issue please open a new one.

The PR is https://github.com/The-OpenROAD-Project/OpenROAD/pull/6150 which has been merged.
