### ISSUE TITLE
ci: build test pr-head and pr-merge failed for several PRs

### ISSUE THREAD

**Issue by titan73** [The-OpenROAD-Project/OpenROAD#6153]
### Describe the bug

The latest PRs failed with the same issue for C++20 compilation which seems due to "lemon".
Something odd, when clicking on "details", C++20 compilation is green and when clicking on has actually failed with red.

### Expected Behavior

First, C++20 compilation should be marked as red when failing in "details"
Then, C++20 should succeeds

### Environment

```shell
CI on github
```

### To Reproduce

Create a PR.

**Comment by maliberty** [comment]
We are aware of the issue and working on fixing it.  I believe the next build of master will be green.
