### ISSUE TITLE
Make OpenROAD icon easier to see

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#6177]
### Description

The OpenROAD icon distinguishes it, but it is pretty much a mushy green blob on a grey background on Ubuntu:

![image](https://github.com/user-attachments/assets/dc34ec4a-25aa-4225-b739-f48e055d257f)

Some other icons for comparison:

![image](https://github.com/user-attachments/assets/fd0e9bd2-c65e-4063-8502-f9898bddd956)

### Suggested Solution

Fix color scheme.

I asked ChatGPT to fix the icon and it came up with a better colorscheme:

![image](https://github.com/user-attachments/assets/2a3670bd-7543-4f7b-8d9e-893bad79ce04)

**Comment by maliberty** [comment]
What size is the icon on your screen in pixels?

**Comment by oharboe** [comment]
> What size is the icon on your screen in pixels?

See image below for details(screenshot), but ca. 50x40.

![image](https://github.com/user-attachments/assets/82d845e5-fc72-4bd8-a6dc-c663f9d8b904)

**Comment by maliberty** [comment]
The icon has a transparent background so the window manager must be choosing the gray color.  How does it look if you use
![Logo with Text (1)](https://github.com/user-attachments/assets/407ae041-b323-4fa4-b566-24e200540781)

**Comment by oharboe** [comment]
> The icon has a transparent background so the window manager must be choosing the gray color.

That's a .jpg file, how do I "try" it?

I'll try latest master and see if I can tweak icon.png a bit.

**Comment by oharboe** [comment]
An idea I was going to try, but [I still get no icon](https://github.com/The-OpenROAD-Project/OpenROAD/issues/6173#issuecomment-2482021927) when I try with master

![icon_modified](https://github.com/user-attachments/assets/6e2f7fca-90d9-4ecc-a398-5a71efeabcbc)

**Comment by maliberty** [comment]
> That's a .jpg file, how do I "try" it?

Replace the src/gui/resources/icon.png and make install should do it

**Comment by oharboe** [comment]
> > That's a .jpg file, how do I "try" it?
> 
> Replace the src/gui/resources/icon.png and make install should do it

But it is a .jpg? icon.png is a png... I thought .jpeg did not encode transparency.

I reopend https://github.com/The-OpenROAD-Project/OpenROAD/issues/6173#issuecomment-2482021927 as I don't get an icon.

**Comment by oharboe** [comment]
Example from https://github.com/The-OpenROAD-Project

![image](https://github.com/user-attachments/assets/8f263273-8a74-4de0-8fb1-3351b0f312eb)
