### ISSUE TITLE
where is the unit test for c++ function level ?

### ISSUE THREAD

**Issue by zhongweidee** [The-OpenROAD-Project/OpenROAD#622]
I have checked the path of OpenROAD/src/OpenDB/src/db/test, there is only 240 lines test.
but there at least 87,565 lines C++ code for OpenDB. how we can do C++ function level or object level test?
Could you tell us that whether will release full test ?
thanks!
wei

**Comment by maliberty** [comment]
Much of the testing is done through the swig API in tcl rather than in c++.  Virtually every other test in the system uses opendb as well for further coverage.   There is nothing else to release in terms of testing.

**Comment by zhongweidee** [comment]
thanks for your comment
