### ISSUE TITLE
make grt::have_routes return silent 0 when elements are not placed

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#6316]
### Description

```
make gui_floorplan
```

Results in:

```
>>> grt::have_routes
[ERROR GRT-0010] Instance ctrl.state.out\[0\]$_DFF_P_ is not placed.
[ERROR GUI-0070] GRT-0010
```

### Suggested Solution

silently return 0

### Additional Context

Useful in scripting

**Comment by maliberty** [comment]
Didn't you already make a PR for this?

**Comment by oharboe** [comment]
> Didn't you already make a PR for this?

This is the next bug in the same vein

**Comment by maliberty** [comment]
Are you planning to fix this?  I assigned the last one only to have you fix it.

**Comment by oharboe** [comment]
> Are you planning to fix this?  I assigned the last one only to have you fix it.

No, I have a workaround. The last one turned out to be trivial to fix and it was blocking me.

This one is more about consistency, hopefully trivial too though.
