### ISSUE TITLE
Documentation for reports generated by check_antennas

### ISSUE THREAD

**Issue by ahmednofal** [The-OpenROAD-Project/OpenROAD#634]
Thank you for your work on this project. The antenna violations reported by `check_antennas` command are dumped in a report file. It is not clear what the syntax of that file is and how to read it.

Can you please offer some documentation or guidance for that ?

**Comment by ahmednofal** [comment]
Hello, thank you for the response, any progress in this regard, should I close the issue?

**Comment by maliberty** [comment]
I know @msaligane is busy with a tapeout at the moment so it might be a bit until he responds.  If you have a specific question I can try to help.

**Comment by msaligane** [comment]
Sorry for the delay. 
@maliberty where should I add the doc for this?

**Comment by maliberty** [comment]
You can make a src/ant/doc directory to hold your module docs.  Please add a link to it from the top-level README.

**Comment by donn** [comment]
You never ended up committing that documentation file. We're kind of blocked by this. Any ETA?

**Comment by maliberty** [comment]
@msaligane please give an eta

**Comment by msaligane** [comment]
I will work on this tonight. Apologies I have been busy with the tapeout and other misc. things.

**Comment by msaligane** [comment]
@ahmednofal can you be more specific on what is unclear on the report? I can maybe add some explanations if the report is unclear.

**Comment by donn** [comment]
How to interpret the report at all. There are many symbols and abbreviations that do not appear to be standard. All the report can successfully tell us now is that there are violations, the data without context is not particularly useful.

**Comment by maliberty** [comment]
Mehdi is working on a document but I suggest you look at the lef/def manual as it is the basis for all the checking and has a lot of explanation of the terms.

**Comment by msaligane** [comment]
I added some more documentation.  You will need to dig a little more to understand how the ratios are calculated. I added a simple example of how it is done (step-by-step).

**Comment by donn** [comment]
https://openroad.readthedocs.io/en/latest/search.html?q=antenna&check_keywords=yes&area=default
