### ISSUE TITLE
Make  `estimate_parasitics -spef_file foo.spef` write to foo.spef, not foo_default.spef

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#6420]
### Description

It is surprising that the _default suffix is added to the filename.

To work around this, I have to add a mv command:

```tcl
estimate_parasitics -placement -spef_file $::env(RESULTS_DIR)/4_cts.spef
exec mv $::env(RESULTS_DIR)/4_cts_default.spef $::env(RESULTS_DIR)/4_cts.spef
```

### Suggested Solution

Write to the exact file that was specified on the command instead of writing to some other file.

**Comment by maliberty** [comment]
If you have multiple corners then multiple files need to be written with unique names.  With just one corner we can do as you suggest.
