### ISSUE TITLE
OpenRCX regression testing

### ISSUE THREAD

**Issue by Yang-Yihang** [The-OpenROAD-Project/OpenROAD#643]
After changing the extRules file from the default file `ext_pattern.rules` to `patterns.rules` (the same as existing `patterns.rulesok`) generated by `generate_rules.tcl`
https://github.com/The-OpenROAD-Project/OpenROAD/blob/be6a3a955857542f34bf8c46cf7cc3fde5763977/src/rcx/test/gcd.tcl#L15

I got the following `gcd.log`

> 

[INFO ODB-0222] Reading LEF file: sky130hs/sky130hs.tlef
[INFO ODB-0223]     Created 13 technology layers
[INFO ODB-0224]     Created 25 technology vias
[INFO ODB-0226] Finished LEF file:  sky130hs/sky130hs.tlef
[INFO ODB-0222] Reading LEF file: sky130hs/sky130hs_std_cell.lef
[INFO ODB-0225]     Created 390 library cells
[INFO ODB-0226] Finished LEF file:  sky130hs/sky130hs_std_cell.lef
[INFO ODB-0127] Reading DEF file: gcd.def
[INFO ODB-0128] Design: gcd
[INFO ODB-0130]     Created 54 pins.
[INFO ODB-0131]     Created 8171 components and 33894 component-terminals.
[INFO ODB-0132]     Created 2 special nets and 0 connections.
[INFO ODB-0133]     Created 411 nets and 1210 connections.
[INFO ODB-0134] Finished DEF file: gcd.def
Notice 0: Split top of 102 T shapes.
[INFO RCX-0033] Defined process_corner X with ext_model_index 0
[INFO RCX-0029] Defined extraction corner X
[INFO RCX-0008] extracting parasitics of gcd ...
[INFO RCX-0035] Reading extraction model file patterns.rulesok ...
[INFO RCX-0036] Database dbFactor= 1.0  dbunit= 1000
ERROR segmentation violation

What is the difference between `ext_pattern.rules` and `patterns.rulesok`?
How to get an extRules file that would work for `extract_parasitics`?

Running `run_130.sh` under folder `calibration/` also leads to a segmentation fault for the same reason.

**Comment by GeraldoPradipta** [comment]
@Yang-Yihang Please make sure that you are using the latest repo version of rcx, I couldn't reproduce the error on my end.
The rcx regression test is working just fine on my end.
