### ISSUE TITLE
Unable to install OpenROAD using clone and build from sources

### ISSUE THREAD

**Issue by nishita2626** [The-OpenROAD-Project/OpenROAD#686]
Hi -

I am using Ubuntu 20.04 in WSL (Windows Subsystem for Linux). I am trying to install OpenROAD using clone and build and getting error. 

[https://openroad.readthedocs.io/en/latest/user/GettingStarted.html](url)

$ git clone --recursive https://github.com/The-OpenROAD-Project/OpenROAD-flow
$ cd OpenROAD-flow
$ ./build_openroad.sh --local

I have installed all the install dependencies tools and libraries given here [https://github.com/The-OpenROAD-Project/OpenROAD](url)

Getting the error. See image -

![error](https://user-images.githubusercontent.com/84976778/119995872-b03dec00-bfeb-11eb-85ea-eeb36f45192c.jpg)

Please help. 

Thanks,
Nishita

**Comment by maliberty** [comment]
I think the docs need a bit of updating.  Please run etc/DependencyInstaller.sh -dev which should get you the needed Qt library.

**Comment by QuantamHD** [comment]
To add some more context I believe the issue is related to this question https://askubuntu.com/questions/1034313/ubuntu-18-4-libqt5core-so-5-cannot-open-shared-object-file-no-such-file-or-dir

With the solution being to run the strip command `sudo strip --remove-section=.note.ABI-tag /usr/lib64/libQt5Core.so.5`

Which if you follow @maliberty's advice will be run as part of etc/DependencyInstaller.sh -dev

**Comment by nishita2626** [comment]
> I think the docs need a bit of updating. Please run etc/DependencyInstaller.sh -dev which should get you the needed Qt library.

Hey I'm getting this message after executing - 

-bash: etc/DependencyInstaller.sh: No such file or directory

**Comment by maliberty** [comment]
Are you running it in your OpenROAD directory?  You might try ./etc/DependencyInstaller.sh in case you don't have the current directory in your PATH.

**Comment by nishita2626** [comment]
> Are you running it in your OpenROAD directory? You might try ./etc/DependencyInstaller.sh in case you don't have the current directory in your PATH.

Please check this image. 

![error2](https://user-images.githubusercontent.com/84976778/120057706-cc30a480-c062-11eb-851e-7cfb2ddf5aa9.jpg)

**Comment by maliberty** [comment]
You need to cd into tools/OpenROAD

**Comment by nishita2626** [comment]
There is no such directory named tools/OpenROAD

**Comment by maliberty** [comment]
Then you forgot to do 'git submodule update --init --recursive'

**Comment by nishita2626** [comment]
> Then you forgot to do 'git submodule update --init --recursive'

Yes I had forgotten but even after executing this I'm getting the same error. Kindly help. 

![error4](https://user-images.githubusercontent.com/84976778/120078195-d9ce4480-c0cb-11eb-8d27-530c1d24722b.jpg)

**Comment by maliberty** [comment]
You need to run as root, you can use sudo

**Comment by nishita2626** [comment]
Thank you so much! OpenROAD has been installed successfully. You've been a great help. Thanks again.

**Comment by maliberty** [comment]
Glag you succeeded.
