### ISSUE TITLE
Update documentation on the existence of the python openroad interpreter

### ISSUE THREAD

**Issue by QuantamHD** [The-OpenROAD-Project/OpenROAD#688]
In issue #685 a user asked about the python support in OpenROAD. Since OpenROAD put in the effort to enable this feature we should publicize it in the documentation and explain its current limitations.

**Comment by maliberty** [comment]
@osamahammad21 would you take care of this?  We just need a short entry in the docs about it and the limitations (ie only opendb apis are present)
