### ISSUE TITLE
Unable to build PDNSim

### ISSUE THREAD

**Issue by nishita2626** [The-OpenROAD-Project/OpenROAD#700]
Hi -

I have installed all the pre-requisites mentioned here [https://github.com/The-OpenROAD-Project/PDNSim](url) but I am unable to build it. Could you please let me know how do I solve this error?

![PDNerror1](https://user-images.githubusercontent.com/84976778/120447714-7cc2df00-c3a8-11eb-96b8-51f84a02a538.jpg)

Thanks.

**Comment by maliberty** [comment]
The standalone repo is archived as pdnsim has been integrated to openroad.  I suggest just using openroad but if you required the standalone version then @VidyaChhabria is the author and could help.

**Comment by nishita2626** [comment]
Okay, thanks!

**Comment by VidyaChhabria** [comment]
I would agree with @maliberty here.  The latest of pdnsim is integrated into OpenROAD and the standalone is not being developed anymore so I suggest using openroad. The related commands for PDNSim can be found at the far end of the [README ](https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/README.md) and a simple test to run PDNSim is [here](https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/psm/test/gcd_no_vsrc.tcl) after you have an openroad binary.
