### ISSUE TITLE
make: *** No rule to make target 'platforms//config.mk.'

### ISSUE THREAD

**Issue by nishita2626** [The-OpenROAD-Project/OpenROAD#713]
Hi -
I have added a new design in Makefile, vedic8x8 and have commented the default design. See image

![makefile](https://user-images.githubusercontent.com/84976778/121157297-0bcb6d80-c867-11eb-86f0-8ef0f92f0d54.jpg)

This is the config.mk file for vedic multiplier in the OpenROAD-flow/flow/designs/nangate45/vedic8x8

![configmk](https://user-images.githubusercontent.com/84976778/121157846-85fbf200-c867-11eb-8687-f7a05ed8a9db.jpg)

After writing the make command I am getting error

![new](https://user-images.githubusercontent.com/84976778/121157968-9f04a300-c867-11eb-92e3-eaf745d94429.jpg)

Please help. Thanks

**Comment by maliberty** [comment]
The 'Permission denied' is likely the root of the problem.  Can you do

cat designs/nangate45/vedic8x8/config.mk

and see if the file is readable?

**Comment by nishita2626** [comment]
It shows permission denied.

**Comment by maliberty** [comment]
Sounds like you have a basic unix file permission issue.  Try chmod u+r designs/nangate45/vedic8x8/config.mk

**Comment by nishita2626** [comment]
chmod: cannot access 'designs/nangate45/vedic8x8/config.mk': Permission denied

**Comment by maliberty** [comment]
This really a file permission issue rather than an openroad issue that you'll need to resolve at your side.  ls -l designs/nangate45/vedic8x8/config.mk is your starting point to see what's going on.
