### ISSUE TITLE
Security Scan is currently throwing an error

### ISSUE THREAD

**Issue by QuantamHD** [The-OpenROAD-Project/OpenROAD#726]
@tspyrou @jjcherry56 it looks like PR #723 introduced a new lib file that isn't in the security repo. 
![image](https://user-images.githubusercontent.com/3784748/121634998-64069900-ca3a-11eb-9a1a-2bf3712a614e.png)

**Comment by rovinski** [comment]
Looks like it needs to be updated to ignore symlinks.

**Comment by jjcherry56** [comment]
@rovinski that's what I thought, but the real issue is that the test directory was not whitelisted because it was new. it should be working now.
