### ISSUE TITLE
Setting up enviroment for hardware designer is little bit  challanging

### ISSUE THREAD

**Issue by dhavalshukla1512** [The-OpenROAD-Project/OpenROAD#74]
I have attended VLSID2020 in Bangalore, where I build my interest to work on OpenROAD Project.

I am hardware designer having background of Physical Design and Timing Checks.With the help of Presenters ,I cloned the different packages like OpenRoad, OpeRoadSTA, Yosys for PnR, Timing Analysis and Synthesis respectively.

I found it little tricky to setup the build environment to start working on project.If this could be resolved it will be easy to go through in further steps.

Can we have pre-built  binaries  for all  the tool which require to execute frontend and backend flow in VLSI?

**Comment by rovinski** [comment]
Hi @dhavalshukla1512,

This repository is currently intended only to build the OpenROAD app from source. For getting started as a user, we recommend using the [OpenROAD-flow](https://github.com/The-OpenROAD-Project/OpenROAD-flow) repository, which eases the build process and contains an example flow to get you up and running quickly.
