### ISSUE TITLE
how to write def file for a new design for IR analysis

### ISSUE THREAD

**Issue by nishita2626** [The-OpenROAD-Project/OpenROAD#743]
@VidyaChhabria could you please help me with the commands for writing a def file for a new design? The def file for the default gcd design was already present in the folder OpenROAD/src/psm/test. Now that I want IR report for a new design, which requires reading def file, what are the steps to be followed to write one?

**Comment by PDN-BeGAN** [comment]
@nishita2626  What is the the file that you havethat represents the new design you want to run?  If you do not have a DEF, I am guessing you have RTL/gate-level netlist? PDNSim requires at minimum a placed design with PDN stripes defined as input.   Refer the [OpenROAD-flow-scripts](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts) repo on how to perform floorplan, placement and generate a PDN-synthesized and placed-DEF from a RTL/gate-level netlist. You can also refer the OpenROAD [test](https://github.com/The-OpenROAD-Project/OpenROAD/tree/master/test) to generate the same files with a simple write_def. 

However, if you want to use PDNSim within any  of the above environments either the OpenROAD-flow-scripts or the OpenROAD test directory you do not really need a "write_def" per se.  Once you clone and build OpenROAD-flow-script using the instructions in the readme, just do a make for a sky130hd design for example and you should see IR drop reports as a part of the final reports. If you use OpenROAD test directory just uncomment the last two lines in flow.tcl file.

**Comment by VidyaChhabria** [comment]
@nishita2626 What is the the file that you havethat represents the new design you want to run? If you do not have a DEF, I am guessing you have RTL/gate-level netlist? PDNSim requires at minimum a placed design with PDN stripes defined as input. Refer the OpenROAD-flow-scripts repo on how to perform floorplan, placement and generate a PDN-synthesized and placed-DEF from a RTL/gate-level netlist. You can also refer the OpenROAD test to generate the same files with a simple write_def.

However, if you want to use PDNSim within any of the above environments either the OpenROAD-flow-scripts or the OpenROAD test directory you do not really need a "write_def" per se. Once you clone and build OpenROAD-flow-script using the instructions in the readme, just do a make for a sky130hd design for example and you should see IR drop reports as a part of the final reports. If you use OpenROAD test directory just uncomment the last two lines in flow.tcl file.
