### ISSUE TITLE
how to install full dependencies on MacOS?????

### ISSUE THREAD

**Issue by JiaDYuan** [The-OpenROAD-Project/OpenROAD#807]
jiadyuan@JiadongdeMacBook-Pro OpenROAD % ./etc/DependencyInstaller.sh -dev
Darwin is not supported
we only support Linux at the moment
usage: ./etc/DependencyInstaller.sh -run[time]
       ./etc/DependencyInstaller.sh -dev[elopment]

**Comment by maliberty** [comment]
mac is not a platform we support directly.  There are some mac users but they have to setup their environment.  If you can use docker that is simpler to get going, otherwise try homebrew.
