### ISSUE TITLE
cpp_tests fails

### ISSUE THREAD

**Issue by yurivict** [The-OpenROAD-Project/OpenROAD#909]
Results directory: https://people.freebsd.org/~yuri/openroad-test-results.tgz

Version: 2.0
OS: FreeBSD 13

**Comment by maliberty** [comment]
There is no plan for OR to support FreeBSD.  We welcome patches but can't spend the resources to track down issues.

**Comment by yurivict** [comment]
I didn't ask to support FreeBSD. This issue is about a QA failure.

**Comment by maliberty** [comment]
There is no such failure on other platforms
