### ISSUE TITLE
Building OpenROAD without OpenSTA sources

### ISSUE THREAD

**Issue by just22** [The-OpenROAD-Project/OpenROAD#943]
Greetings,

I've just started the OpenROAD porting to OpenBSD; in the official port tree we already have OpenSTA as standalone tool; I'm wondering if it's possible to build OpenROAD without compiling the OpenSTA sources too.

If that's is supported (or even not fully supported, but the effort is low), please give me some hints on how to proceed.

Thanks and Regards

--
Alessandro

**Comment by maliberty** [comment]
It isn't supported and I don't think it would make sense as many parts of the system depend on opensta.
