### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by praharshapm** [The-OpenROAD-Project/OpenROAD#964]
I am trying to install the dependencies using etc/DependencyInstaller.sh, but I am getting error that:
E: The repository 'http://ppa.launchpad.net/saltmakrell/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

I am attaching screenshot as well. Am I missing any step?
![Screenshot from 2021-08-05 00-22-20](https://user-images.githubusercontent.com/69325690/128238944-b3bf5d70-71ef-48d5-96fe-438dc8297db0.png)

**Comment by vvbandeira** [comment]
@praharshapm this looks unrelated to OpenROAD. Does the error also occurs if you run `sudo apt update`?

**Comment by praharshapm** [comment]
Oh, you are right. I am also getting same error for `sudo apt update`. Looks like there is some other issue. Thanks
